### ISSUE TITLE
Zero crossing point

### ISSUE THREAD

**Issue by alexey-lysiuk** [kcat/openal-soft#103]
_It's not a bug report but a feature request_

Is possible to play/pause/stop source functions to start/stop playback at zero crossing points?
Having this as an extension will be great.

_A little bit of background information_

At the moment OpenAL is the single sound backend in GZDoom.
Moreover I believe you was the person behind its implementation.
FMOD Ex one has been dropped recently in order to change linsence to GPL.
And OpenAL Soft implementation is used on all major platforms.

[Here](https://forum.zdoom.org/viewtopic.php?f=3&t=55212) is the initial discussion about the issue on ZDoom forum.
However it's quite problematic to take zero crossing point into account at the level of the sound backend itself.
That's why I would like to ask you to add such feature to OpenAL Soft.

Thanks in advance!

**Comment by kcat** [comment]
Rather than starting/stopping at zero crossing, I think I'd prefer fading from/to silence. So instead of having check each sample until (if) it crosses zero, it simply ramps the volume from/to zero. The mixer already does volume ramping anyway to handle moving sources, so it will be overall easier to integrate.

Ramping on start shouldn't be hard to do. It simply needs to check if it's starting at the beginning of the sound, and if not, start with the volume at 0 and ramp it up to the intended target when mixing.

Ramping on pause/stop will be a bit more tricky. The main issue here is that when a source is paused or stopped, the source's state is changed right away and there's specific things the app is allowed to immediately do or expect afterward that it couldn't while playing. However, to ramp (this applies to zero crossing too) the mixer would need to continue processing the source as if it hadn't yet stopped, just with an added step to bring it to silence using some criteria. It is something I want to do, and have done some work toward that goal, but it will still take a while.

**Comment by kcat** [comment]
Commits 87479b4b3207a0600586c919c03b5cee7af5154e and 106671d45185576e9386eaf0c27211446c8ebce5 make sounds try to more gracefully ramp down to 0 amplitude if it ends prematurely. I know GZDoom now already implements its own method of fading out sounds before truly stopping them, but this should also help prevent clicks and pops from sources stopping in the middle of a sound.

**Comment by alexey-lysiuk** [comment]
Great, thank you.
