### ISSUE TITLE
Hrtf makes the sources sound like they have a high pass filter applied to them

### ISSUE THREAD

**Issue by the-byte-bender** [kcat/openal-soft#1034]
Hello,
I don't really know how to best describe this, but sounds through hrtf sound a bit strange. It's not the normal hrtf processing, it's like the source has some high pass applied and is being played out of a low quality speaker or inside a plastic bottle. It does process hrtf properly, but the sounds just become low quality as a result for some reason.
Is there a way around that?

Thanks.
P.S: I can provide audio samples if you want to listen to difference.

**Comment by kcat** [comment]
Audio samples could help. HRTF normally has a bit of a high-pass effect since it simulates external sounds, and too much bass makes it harder to localize its position, but if you think it's more than the normal HRTF processing, perhaps something else is going on. A trace log could help too, if you're able to create one (set the `ALSOFT_LOGLEVEL` environment variable to `3` and `ALSOFT_LOGFILE` to a full path+filename to write the log to, when running the app).

**Comment by the-byte-bender** [comment]
[Here](https://the-byte-bender.me/demo.flac) is an audio sample demoing this. At first you will hear me walking around in a space with an hrtf model from the viking dataset, which seems to be more authentic and does not high pass audio. Then you will hear me switch to the built-in hrtf and move around using that. You should be able to hear how the built-in hrtf kind of high-passes the audio.

**Comment by kcat** [comment]
That's likely a difference in the measurements themselves (the built-in one does seem to have a bit more attenuation in the lower frequencies). The built-in HRTF is created from the MIT KEMAR dataset, which was originally created in the late 90s, whereas the viking datasets were created by the University of Iceland much more recently, so there may be a difference caused by the quality of equipment and processing methods. And since HRTFs can be fairly dependent on how closely the measured subject matches the particular listener, a less fitting one may sound more filtered compared to a better fitting one.
