### ISSUE TITLE
WASAPI backend doesn't support mono output mode

### ISSUE THREAD

**Issue by MausGames** [kcat/openal-soft#1070]
Trying to use the **ALC_SOFT_output_mode** extension with **ALC_MONO_SOFT** doesn't seem to produce mono output on Windows, while it seems to work on other platforms (e.g. Linux/PipeWire, macOS/CoreAudio).

Looking further into it, the issues seems to be present on the **WASAPI** backend but not the **DirectSound** backend.

I tried looking a bit at the **WASAPI** code, but I don't have enough experience with the API to find a proper solution.

I've attached a verbose log of my application and setup:
[log_openal.txt](https://github.com/user-attachments/files/17879553/log_openal.txt)

The issue is present on both v1.24.0 and v1.23.1.

As a workaround I currently set the backend priority of **DirectSound** higher than **WASAPI** in alc.cpp (even though **DirectSound** is deprecated and probably just a wrapper over **WASAPI**).

**Comment by kcat** [comment]
The problem is that WASAPI doesn't (normally) accept a channel configuration different from what the device is configured for, unlike most other audio systems. Without an appropriate APO installed, it doesn't allow creating a mono playback stream on a device configured for stereo, for example. There are some workarounds for certain modes, for example OpenAL Soft can output stereo when the device is 5.1 because the first two channels are front-left and front-right on both cases, it simply leaves the other channels silent. But it's not that simple if trying to play mono with non-mono output.

It may not be too hard to allow for mono mixing with stereo output, though. It would just need to allow doing a mono mix to the front-left channel while leaving all the other channels silent, and do an extra step to copy the front-left to the front-right before finishing.

**Comment by kcat** [comment]
Should work now with commit 03c783df35669afdee38a369623433984dfac815.

**Comment by MausGames** [comment]
Thank you so much for the fast response!

I tried it out and mono output works now with WASAPI exactly like with DirectSound.

The only issue I found was when switching from mono to stereo output with alcResetDeviceSOFT, the new nMonoUpsample variable is not set back to false, because finalizeFormat is not called when the requested format is properly supported and wfx is a nullptr:
https://github.com/kcat/openal-soft/blob/03c783df35669afdee38a369623433984dfac815/alc/backends/wasapi.cpp#L2012

**Comment by kcat** [comment]
Good catch. Fixed in commit e47b70733cde5d649b9ee9cc6ee7fd82e6c0dc5a.

**Comment by MausGames** [comment]
Thank you again, I think that should work now. :)
I will close the issue.
