### ISSUE TITLE
CoraAudio backend tries to resolve wrong property when getting channel count

### ISSUE THREAD

**Issue by Berstanio** [kcat/openal-soft#1086]
When I try to enumarate all devices on macOS using `ALC_ALL_DEVICES_SPECIFIER` (`alcGetString(NULL, ALC_ALL_DEVICES_SPECIFIER)`) I get the following error:
`[ALSOFT] (EE) kAudioDevicePropertyStreamConfiguration size query failed: 'who?' (2003332927)`

This seems to be caused by this code: https://github.com/kcat/openal-soft/blob/ff497ad11182b48d1bfa57216c51a2ac0c723c7d/alc/backends/coreaudio.cpp#L201
This tries to get the `kAudioUnitProperty_AudioChannelLayout` (which is a property on an AudioUnit) on an AudioDevice.

Probably introduced here: https://github.com/kcat/openal-soft/commit/068a54212d7139258c0f666d668497c928ff86b4

**Comment by kcat** [comment]
Possibly a result of https://github.com/kcat/openal-soft/pull/1056/commits/29b03d133e5382ce51fa002d30c9b33440b61541. That originally used `kAudioDevicePropertyPreferredChannelLayout`, but was changed to `kAudioUnitProperty_AudioChannelLayout` because it caused [a build failure on iOS](https://github.com/kcat/openal-soft/pull/1056#issuecomment-2457102257). Perhaps the instances in `GetDeviceChannelCount` should be changed back since it's excluded on iOS.

The channel layout handling in `CoreAudioPlayback::reset` probably also needs some looking at, since it sets the `kAudioUnitProperty_StreamFormat` with a channel count the `ALCdevice` has, but then changes the `ALCdevice`'s channel configuration based on `kAudioUnitProperty_AudioChannelLayout`, which seems like it could cause a mismatch between the stream format request and the `ALCdevice` configuration if the `kAudioUnitProperty_AudioChannelLayout` query doesn't align with what was set for `kAudioUnitProperty_StreamFormat`  (if that query is even working and not silently failing). But I'm not familiar with CoreAudio to know how this should work.

**Comment by kcat** [comment]
Try now with commit 53a2ec1d5cab8670b974e5e1dd68cc424eb6cf30.

**Comment by Berstanio** [comment]
I tried it and unfortunatly it is not resolved. I added some extra debug log to mine and this is what I got:
```
[ALSOFT] (II) Extensions: +NEON
[ALSOFT] (II) Initialized backend "core"
[ALSOFT] (II) Added "core" for playback
[ALSOFT] (II) Added "core" for capture
[ALSOFT] (II) Got device: Externe Kopfhörer = ID 87
[ALSOFT] (II) Try reading device: LG ULTRAWIDE = ID 94
[ALSOFT] (II) Got device: LG ULTRAWIDE = ID 94
[ALSOFT] (II) Try reading device: USB Audio = ID 51
[ALSOFT] (II) Got device: USB Audio = ID 51
[ALSOFT] (II) Try reading device: USB Audio = ID 50
[ALSOFT] (EE) kAudioDevicePropertyStreamConfiguration size query failed for deviceID 50: 'who?' (2003332927)
[ALSOFT] (II) Try reading device: Mac mini-Lautsprecher = ID 81
[ALSOFT] (II) Got device: Mac mini-Lautsprecher = ID 81
```

**Comment by Berstanio** [comment]
Using `kAudioDevicePropertyStreamConfiguration` as the property fixes it completly for me

**Comment by kcat** [comment]
Interesting that only one device failed with `kAudioDevicePropertyPreferredChannelLayout`, but the others were fine. I guess not all devices are required to have a channel layout defined for querying?

Does the latest git version work now?

**Comment by Berstanio** [comment]
```
[ALSOFT] (II) Added "core" for playback
[ALSOFT] (II) Added "core" for capture
[ALSOFT] (II) Got device: Externe Kopfhörer = ID 79
[ALSOFT] (II) Try reading device: LG ULTRAWIDE = ID 86
[ALSOFT] (II) Got device: LG ULTRAWIDE = ID 86
[ALSOFT] (II) Try reading device: USB Audio = ID 101
[ALSOFT] (II) Got device: USB Audio = ID 101
[ALSOFT] (II) Try reading device: USB Audio = ID 108
[ALSOFT] (II) Try reading device: Mac mini-Lautsprecher = ID 73
[ALSOFT] (II) Got device: Mac mini-Lautsprecher = ID 73
```
Seems to work now, thanks a lot!
Closing as resolved.

**Comment by colincornaby** [comment]
> The channel layout handling in CoreAudioPlayback::reset probably also needs some looking at, since it sets the kAudioUnitProperty_StreamFormat with a channel count the ALCdevice has, but then changes the ALCdevice's channel configuration based on kAudioUnitProperty_AudioChannelLayout, which seems like it could cause a mismatch between the stream format request and the ALCdevice configuration if the kAudioUnitProperty_AudioChannelLayout query doesn't align with what was set for kAudioUnitProperty_StreamFormat (if that query is even working and not silently failing). But I'm not familiar with CoreAudio to know how this should work.

Apologies for commenting on a closed issue. I've been away from the holidays but this issue was brought to my attention.

I'm curious what the proper behavior should be here. What would be the best way forward? Should I open another issue for discussion?

**Comment by kcat** [comment]
I was mainly curious if the `kAudioUnitProperty_AudioChannelLayout` property updates when setting `kAudioUnitProperty_StreamFormat`. Since the code previously would set `kAudioUnitProperty_StreamFormat` according to the AL device format, and then query `kAudioUnitProperty_AudioChannelLayout` and update the AL device's channel configuration. If the channel layout property doesn't automatically update itself, it would cause a discrepancy between the CoreAudio stream format and what OpenAL Soft gets set for.

However, I changed that with commit 530aee883c0d5a83ff2d60322936e5e9e5bdf8d6, querying `kAudioUnitProperty_AudioChannelLayout` and updating the AL device's channel configuration first, then set `kAudioUnitProperty_StreamFormat` given the AL device configuration. I think it should be okay now, but my knowledge of CoreAudio is limited.
