### ISSUE TITLE
Linux: Static Cmake Compilation Failed from FMT

### ISSUE THREAD

**Issue by SavorSauc3** [kcat/openal-soft#1088]
OS: Linux Pop!_OS
Branch: master
Issue:
When statically compiling on linux I get the following error 
```
CMake Error:
  Error evaluating generator expression:

    $<BUILD_LOCAL_INTERFACE:alsoft::fmt>

  Expression did not evaluate to a known generator expression
```

Based on the message I think the issue might be related to this line / area of code in the CMakeLists.txt, but I am not a C++ guru or anything. I think maybe downgrading my submodule could fix the issue so I will notify after trying the code prior to #0a15b37

![Screenshot from 2024-12-25 23-24-00](https://github.com/user-attachments/assets/f9b3dfb0-3229-4369-8d62-40b61bb8b14f)

**Comment by SavorSauc3** [comment]
Compilation worked at commit: 0a15b378133adfa0548ed8f8f68fadf4ffc3911d
But if the issue is on my end please let me know, otherwise if you know what the issue is maybe you or I can fix it.

**Comment by kcat** [comment]
Looks like the `BUILD_LOCAL_INTERFACE` generator expression was added in [CMake 3.26](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:BUILD_LOCAL_INTERFACE), so an older CMake version would fail with it. Upgrading CMake should fix it, but it wasn't my intention to require that version of CMake, so I would still consider it a problem with OpenAL Soft.

However, it doesn't seem that simple to fix. Simply removing the generator expression and linking the target normally causes its own error:
```
CMake Error in CMakeLists.txt:
  export called with target "OpenAL" which requires target "alsoft.fmt" that
  is not in any export set.
```
This oddly only affects static builds, the dynamic build doesn't error there or require that target for exporting. I'd probably consider this error a CMake problem. Unfortunately, the only workaround I can find is that generator expression, which hides `alsoft::fmt` from being on the OpenAL target when generating the install/export commands.

That earlier commit was when the static build used a header-only version of `fmt`, and it copied the necessary build properties manually instead of linking to it. However, that really bloated the library size (since more things are being inlined/duplicated for each compiled file) and caused a ton of warnings with inlining failures. So it was changed to use an object library (which is a CMake construct like a static library, except it skips creating the `.a` file and includes the object files directly in whatever links to the object library target), allowing it to be linked into a static library without creating in two separate static libraries.

**Comment by SavorSauc3** [comment]
For now I am probably just going to work with the older version of this repository, but in the future I may upgrade the required version of cmake to match 3.26, since I probably should be working with a newer version anyways. I am closing this issue since it does seem to be more of my problem than yours.
