### ISSUE TITLE
UT2004: Sounds being muffled with 1.24.1

### ISSUE THREAD

**Issue by NOOTLORD** [kcat/openal-soft#1089]
I am aware that there is a post about the same issue for GZDoom, but this issue also affects UT2004 both the 32 and the 64-bit version suffer from muffled sound.

I tried older versions of the binary's but all produced the same muffled sound, unfortunately i don't have any understanding of the openal codebase, but if you need more information or things to test please let me know!

I made a quick recording of the difference, when i tick the system driver box it will use the defopenal32.dll that comes with the game. i grabbed the latest soft_oal.dll and renamed it to DefOpenAL32.dll (if this is not the intended way please let me know 🤭)

https://youtu.be/CEkBYtnapxo

**Comment by ThreeDeeJay** [comment]
Isn't that just HRTF being active? It inherently changes the audio to simulate audio outside your head.
If you didn't enable it yourself, you might've added an alsoft.ini that turned on HRTF.
Otherwise, your playback device might have been detected as headphones (using front panel headphones port?), which OpenAL Soft enables HRTF for.

Otherwise, if this really is a bug, it'd help to have a log file, opening a command prompt window in the executable's folder and running these commands:
```
Set ALSOFT_LOGFILE=alsoft_error.txt
Set ALSOFT_LOGLEVEL=3
UT2004.exe
```
Or you could just drag the exe into this script [Run executable with logging enabled.zip](https://github.com/user-attachments/files/18262680/Run.executable.with.logging.enabled.zip)

In the meantime, you can also try finding the exact version where it started happening by testing older builds.
You can find older developer versions here (click a green checkmark then scroll down to artifacts): https://github.com/kcat/openal-soft/actions
For older, major releases, check out https://openal-soft.org/openal-releases/

**Comment by QmwJlHuSg9pa** [comment]
Probably a dupe of https://github.com/kcat/openal-soft/issues/1085.

**Comment by NOOTLORD** [comment]
> UT2004.exe

Its HRTF 😅 i added alsoft.ini to my %appdata% and set HRTF to false and it sounds like it should again.
Interesting that newer versions of openal do this, many thanks for the help 😄

**Comment by QmwJlHuSg9pa** [comment]
> Its HRTF 😅 i added alsoft.ini to my %appdata% and set HRTF to false and it sounds like it should again.
> Interesting that newer versions of openal do this, many thanks for the help 😄

If you really want to "fix" it, leave HRTF enabled and set:

```
[general]
resampler=spline
```
This is the old default setting; the next release will probably revert to this as default anyway.
