### ISSUE TITLE
Loading Files into the Buffer

### ISSUE THREAD

**Issue by flaccidware** [kcat/openal-soft#117]
How difficult would it be to include a routine for loading a buffer from an audio file. Wav, Ogg AIF etc?
I believe this can be achieved using ALUT but that's another load of libraries to be included.

If it can already be done excuse my ignorance but I can't se how.

**Comment by kcat** [comment]
OpenAL doesn't handle files directly, since it's system-dependent. Loading a file on Android, for instance, can't really be done with standard file I/O. Different apps will want to support different formats too, not all of which can be easily included (due to patents, or decoder licenses). Not to mention compatibility issues if an app wants a particular format, and the lib happens to be built without that format.

So it's generally best to leave the file loading and decoding to the app, so it can ensure it has what it wants. Companion libs like ALUT and Alure provide easy, general-purpose methods to handle it for apps it's suitable for, while not burdening the main library for apps that need something else.

**Comment by flaccidware** [comment]
Thanks very much for your concise explanation as to why it is not a sensible thing to do.  Given the cross platform usage my request, in retrospect, was somewhat silly.

I would like to write, in C# a file handler for loading the buffer but my programming experience in C# and the use of OpenAL is limited to say the least.  Do you know where I might find a code snippet to give me a starting place?  I've tried with no success to get ALUT to work - my problem not the programmes authors.

Regards and apologies for a stupid request!

Al

**Comment by kcat** [comment]
Unfortunately I'm not experienced with C# either. I know of a wrapper for using OpenAL in C#, but I don't know about a wrapper for using ALUT or any other ways for loading audio files.

**Comment by Zuzu-Typ** [comment]
I would be very much +1 on this, if it wasn't for the necessary libraries (libogg, libopus, libopusfile, etc.) that would have to ship with OpenAL Soft (more or less unnecessarily).
Nevertheless I have a working audio file loader in my (work in progress) game engine that is based on some examples I found doing a simple Google search for "OpenAL opus" (and ogg vorbis respectively).

I would love to have something like ALUT Soft, because alut (and freealut) are no longer updated and I couldn't get freealut to compile using MSVC 2017 (with included runtimes, so there's no need for the redistributable DLL).
If I were a little more skilled, I would even do it myself, but I've never done anything like developing a library.

**Comment by kcat** [comment]
> I would love to have something like ALUT Soft, because alut (and freealut) are no longer updated

You can try [Alure](https://github.com/kcat/alure). It's essentially a C++ wrapper on top of OpenAL, and includes file loading (using various decoder libs) and other things.

**Comment by Zuzu-Typ** [comment]
Thanks for the info, but I now have my own wrappers for Python, "PyOpenAL" and "PyOgg", which supports wave, opus, vorbis and flac file types.
I also recommend OpenAL-soft in PyOpenAL's readme, because I really love your work ;)
