### ISSUE TITLE
alGetSourcei (src, AL_BUFFER, &buf) returns 0 for streaming sources in OpenAL 1.18.0

### ISSUE THREAD

**Issue by ReactorScram** [kcat/openal-soft#126]
My app plays from one buffer while the other is being written to, and since installing 1.18.0, it loops wrong because `alGetSourcei (.., AL_BUFFER, ..)` is always AL_NONE. (I use this call to decide which buffer is 'front' and which is 'back')

If I revert to 1.17.2 from my package cache, it works. Then if I reinstall 1.18.0, it fails. Same app binary.

It seems to be because of this: https://github.com/kcat/openal-soft/blob/a35b9bbd3eac75771ca90d5755068cf88d5406aa/OpenAL32/alSource.c#L1322

In 1.17.2, GetSourceiv would return current_buffer for streaming sources. In 1.18.0 for some reason it returns NULL / AL_NONE.

I can make a minimal test case tomorrow if necessary.

Maybe my queueing method is wrong and I shouldn't even be calling this?

**Comment by kcat** [comment]
The spec doesn't actually mention that ```AL_BUFFER``` should give anything for a streaming source. This was changed with commit 5c859af24ea44dabbbb31631309bb08a858a523e, which restructured how the source's buffer queue is handled to be saner, more streamlined, and less reliant on the mixer voice state.

The value isn't very useful since you can't modify a buffer that's still queued on a source, and it previously created a behavioral oddity (when a streaming source finished playing, ```AL_BUFFER``` would become 0 because there's no active buffer, while a non-streaming source that finishes playing retains the same ```AL_BUFFER``` value that was set). You can only modify the buffer once it's been unqueued with ```alSourceUnqueueBuffers```, and that method gives you the buffer ID so there's no need for ```AL_BUFFER```.

> Maybe my queueing method is wrong and I shouldn't even be calling this?

I don't know exactly what your queueing method is like, but the typical way is to query the source's ```AL_BUFFERS_PROCESSED``` to get the number of 'finished' buffers, and if there's any use ```alSourceUnqueueBuffers``` to get those buffer IDs, refill them with the next bit of audio, then requeue them back onto the source with ```alSourceQueueBuffers```.

**Comment by ReactorScram** [comment]
I will try that method instead.

I was reading the 1.1 spec PDF which maybe is out of date? For AL_BUFFER the words "static" and "streaming" don't even appear. (On page 35, section 4.3.2)

**Comment by kcat** [comment]
> For AL_BUFFER the words "static" and "streaming" don't even appear. (On page 35, section 4.3.2)

Right. However, ```AL_SOURCE_TYPE``` does describe that setting ```AL_BUFFER``` to a valid non-0 buffer ID results in a ```AL_STATIC``` source, setting ```0```/```AL_NONE``` results in an ```AL_UNDETERMINED``` source, and calling ```alSourceQueueBuffers``` on an ```AL_UNDETERMINED``` source results in a ```AL_STREAMING``` source.

The way these properties generally work is, if you specify a value using ```alSource*``` for some property, then later call ```alGetSource*``` with the same property, you get back the same value you last set. There's a few exceptions to this, but it's mentioned when it's different. In this case, ```AL_BUFFER``` is 0 by default. If it's ever set to a non-0 value, it must be set to 0 again before ```alSourceQueueBuffers``` can be used on it for streaming. So for a streaming source the last value set for ```AL_BUFFER``` must have been 0, so that's what's returned.

**Comment by ReactorScram** [comment]
Okay, I skimmed over that part because I was not setting AL_BUFFER directly so I figured it wasn't important. Human factors, I guess. Now I have to remember what yak I was shaving before my audio broke.

**Comment by Swyter** [comment]
Oh boy, I just had the same problem. Let's just say that the OpenAL documentation is not that nuanced, so most of the time I just tend to follow the specification.

My streaming code was working perfectly fine in Windows (with the precompiled `ALSOFT 1.17.2` .dll) and terribly in macOS and Linux. Now I know why I was getting a zero in `AL_BUFFER` while `AL_SOURCE_STATE` returned `0x1012` (`AL_PLAYING`).

I never set `AL_BUFFER` for streaming, only when I want to empty the entire queue. But I did use `AL_BUFFER` to get the currently playing chunk and retrieve the correct offset in my virtual ring buffer emulation. I know that there's a _DirectSound_-like extension ([`AL_SOFT_buffer_sub_data`](https://github.com/openalext/openalext/wiki/AL_SOFT_buffer_sub_data)), but I want to keep things portable.

Anyway. Thanks to @kcat for the great library (and for keeping OpenAL alive) and to @ReactorScram  for the heads up and for the descriptive issue title. I'm sure that many others will find this in Google like I did.

I was scratching my head for a while.
