### ISSUE TITLE
Examples improperly link with both SDL2 and SDL

### ISSUE THREAD

**Issue by yurivict** [kcat/openal-soft#137]
They shouldn't mix.

```
# ldd work/stage/usr/local/bin/alloopback 
work/stage/usr/local/bin/alloopback:
	libSDL_sound-1.0.so.1 => /usr/local/lib/libSDL_sound-1.0.so.1 (0x800827000)
	libSDL2-2.0.so.0 => /usr/local/lib/libSDL2-2.0.so.0 (0x800a51000)
```

**Comment by yurivict** [comment]
See details here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220931

**Comment by kcat** [comment]
It seems like SDL_sound may be linked to SDL1, which implicitly pulls that in while the examples explicitly use SDL2. SDL_sound can be linked to SDL2, but there's no easy way to check which it's using.

**Comment by kdhp** [comment]
@kcat  None of the examples that use SDL_sound call SDL directly, so would adding a CMake flag to override the version of SDL added to `SDL_SOUND_LIBRARIES` be an acceptable solution?

**Comment by kcat** [comment]
I don't think that'll work, since SDL_sound's shared lib will have an implicit dependency on SDL1's shared lib, regardless of what's in `SDL_SOUND_LIBRARIES`.

**Comment by kdhp** [comment]
`cmake/FindSDL_sound.cmake` defaults to adding SDL 2 if both are found, so allowing an override would give someone on an affected system the ability to compile the examples in question without the knowledge and modification of the OpenAL-Soft build system by forcing `SDL_SOUND_LIBRARIES` to use SDL 1.  This is possible because the SDL library is solely a dependency of SDL_sound for those examples, and is not used directly.

A more automated, but complicated, solution would be to inspect the library with something like `ldd` to decide which version of SDL to put in `SDL_SOUND_LIBRARIES`.

**Comment by kcat** [comment]
SDL_sound is no longer used with the examples since commit cae78e79e81afbc47a9a5802c4cfcc62dbc07f8e, so they shouldn't try to pull in both SDL1 and SDL2 anymore.
