### ISSUE TITLE
Audio glitches on high sampling rate (Android/Termux/mpv)

### ISSUE THREAD

**Issue by tomty89** [kcat/openal-soft#154]
Hi. I am using openal-soft (1.18.2) on Android (Termux) with mpv. I notice stutter-ish glitches occur when the requested sampling rate is higher than 128kHz (at least starting from 160kHz).

From mpv's messages, I can see that the "device buffer" (apparently a value reported by OpenAL, since there's a "soft buffer" that can be set to a value no less than that with its `--audio-buffer` switch) is fixed at 32000 samples. In the case when mpv outputs to OpenSL ES directly, the device buffer is 50ms (i.e. the size increases with the requested sampling rate).

The reaaon I specifically tested the two sample rates (in addition to common ones) is that, 32000 samples will be a 250ms and a 200ms buffer respectively, which are in turn 5 and 4 times of the device buffer reported by OpenSL ES. (I am not sure what backend openal-soft on Termux is using but probably OpenSL ES?)

Increasing the size of the soft buffer in mpv doesn't help working around the problem.

P.S. By requested sampling rate I was referring to the rate mpv requested to OpenAL, not the rate set in alsoftrc or so (none is being used).

**Comment by kcat** [comment]
It could be that the default buffer metrics openal-soft itself uses to handle the "real" audio device (1024 samples per update, with 3 updates in queue) is too small when running at high sample rates. At 160khz, each update is only 6.4 milliseconds. With 3 updates in the queue, that means the entire buffer queue that openal-soft needs to keep filled is 19.2 milliseconds. In less than 20ms the entire buffer goes from completely full to completely empty, which gives openal-soft too little time to properly wake up and process the necessary number of samples.

Ideally, the sample rate set for openal-soft should match the device so that no extra resampling needs to occur after the mix is done, and I'd be surprised if the Android device is actually using a 160khz (or higher) sample rate. If openal-soft is set to 160khz, that means it needs to resample everything up to 160khz only for the device to then resample back down to 44.1khz or 48khz (whichever the hardware is actually using). It's a lot of unnecessary work that just adds noise to the final output since there's no such thing as a perfect resampler.

If the input stream is a high rate like 160khz, you can play buffers created with that high rate so that openal-soft resamples it down to 44.1khz or 48khz (resampling down is more efficient than resampling up, since there's fewer samples to generate). That 44.1khz or 48khz mix can then go right to the device without any extra resampling.

**Comment by tomty89** [comment]
But I wasn't talking about the rate/buffer between OpenAL and its backend, rather it's the rate/buffer between OpenAL and an input stream from a program.

Apparently OpenAL accepts streams up to 192kHz, since if mpv goes higher, OpenAL rejects it (which seems to be another flaw coz ideally it should request back to mpv its higher limit so that mpv will know to resample appropriately, which is what it is actually doing for request belows 8kHz, its apparent lower limit):
```
[ao] Trying audio driver 'openal'
[ao/openal] requested format: 200000 Hz, stereo channels, s16p
[ao/openal] Channel layouts:
[ao/openal]  - #fl
[ao/openal]  - #fr
[ao/openal]  - #fc
[ao/openal]  - #lfe
[ao/openal]  - #bl
[ao/openal]  - #br
[ao/openal]  - #bc
[ao/openal]  - #sl
[ao/openal]  - #sr
[ao/openal] result: stereo
AL lib: (EE) ALCopenslPlayback_reset: engine->CreateAudioPlayer: Content unsupported
[ao/openal] using soft-buffer of 0 samples.
[ao/openal] Couldn't probe device buffer size.
[ao] Failed to initialize audio driver 'openal'
[cplayer] Could not open/initialize audio device -> no sound.
```

Otherwise the device buffer got probed is always 32000 samples:
```
[ao] Trying audio driver 'openal'
[ao/openal] requested format: 192000 Hz, stereo channels, s16p
[ao/openal] Channel layouts:
[ao/openal]  - #fl
[ao/openal]  - #fr
[ao/openal]  - #fc
[ao/openal]  - #lfe
[ao/openal]  - #bl
[ao/openal]  - #br
[ao/openal]  - #bc
[ao/openal]  - #sl
[ao/openal]  - #sr
[ao/openal] result: stereo
[ao/openal] device buffer: 32000 samples.
[ao/openal] using soft-buffer of 32000 samples.
[cplayer] AO: [openal] 192000Hz stereo 2ch s16p
```

```
[ao] Trying audio driver 'openal'
[ao/openal] requested format: 1000 Hz, stereo channels, s16p
[ao/openal] Channel layouts:
[ao/openal]  - #fl
[ao/openal]  - #fr
[ao/openal]  - #fc
[ao/openal]  - #lfe
[ao/openal]  - #bl
[ao/openal]  - #br
[ao/openal]  - #bc
[ao/openal]  - #sl
[ao/openal]  - #sr
[ao/openal] result: stereo
[ao/openal] device buffer: 32000 samples.
[ao/openal] using soft-buffer of 32000 samples.
[cplayer] AO: [openal] 8000Hz stereo 2ch s16p
```

Shouldn't the buffer size vary as per the requested sampling rate, like what happens with OpenSL ES?
```
[ao] Trying audio driver 'opensles'
[ao/opensles] requested format: 192000 Hz, stereo channels, s16p
[ao/opensles] device buffer: 9600 samples.
[ao/opensles] using soft-buffer of 9600 samples.
[cplayer] AO: [opensles] 192000Hz stereo 2ch s16
```
```
[ao] Trying audio driver 'opensles'
[ao/opensles] requested format: 8000 Hz, stereo channels, s16p
[ao/opensles] device buffer: 400 samples.
[ao/opensles] using soft-buffer of 400 samples.
[cplayer] AO: [opensles] 8000Hz stereo 2ch s16
```

I am wondering if this is a backend-neutral issue (at least in terms of the fixed buffer size), I have yet to test on desktop Linux where more backends are available though.

To be honest I wasn sure if this is the relevant to the glitch problem, and the tested values might not be accurate because I didn't test for long, it's just this fixed buffer size thing doesn't seem right to me anyway.

**Comment by tomty89** [comment]
`logcat` outputs show that OpenAL to device (OpenSL) buffer is increased as the sampling rate goes up:
```
11-04 19:22:37.624  8837  8837 D openal  : AL lib: UpdateDeviceParams: Pre-reset: Stereo, Float, *44100hz, 1024 update size x3
11-04 19:22:37.630  8837  8837 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
11-04 19:22:37.638  8837  8837 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 16146
11-04 19:22:37.638  8837  8837 D AudioTrack: Client defaulted notificationFrames to 8073 for frameCount 16146
11-04 19:22:37.641  8837  8837 D openal  : AL lib: UpdateDeviceParams: Post-reset: Stereo, Signed Short, 44100hz, 1024 update size x3
```
```
11-04 19:22:56.085  9046  9046 D openal  : AL lib: UpdateDeviceParams: Pre-reset: Stereo, Float, *88200hz, 2048 update size x3
11-04 19:22:56.091  9046  9046 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
11-04 19:22:56.102  9046  9046 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 88200 Hz, output 44100 Hz
11-04 19:22:56.107  9046  9046 D AudioTrack: Client defaulted notificationFrames to 10764 for frameCount 32292
11-04 19:22:56.108  9046  9046 D openal  : AL lib: UpdateDeviceParams: Post-reset: Stereo, Signed Short, 88200hz, 2048 update size x3
```
```
11-04 19:23:18.136  9092  9092 D openal  : AL lib: UpdateDeviceParams: Pre-reset: Stereo, Float, *176400hz, 4096 update size x3
11-04 19:23:18.140  9092  9092 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
11-04 19:23:18.150  9092  9092 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 176400 Hz, output 44100 Hz
11-04 19:23:18.153  9092  9092 D AudioTrack: Client defaulted notificationFrames to 21516 for frameCount 64548
11-04 19:23:18.154  9092  9092 D openal  : AL lib: UpdateDeviceParams: Post-reset: Stereo, Signed Short, 176400hz, 4096 update size x3
```
So again, why is the program to OpenAL buffer of a fixed size?

**Comment by kcat** [comment]
> But I wasn't talking about the rate/buffer between OpenAL and its backend, rather it's the rate/buffer between OpenAL and an input stream from a program.

Right, but it appears mpv tries to set the OpenAL device to use the specified sample rate (rather than just the input stream), which means the rate/buffer between OpenAL, OpenSL, and the hardware device is possibly too much to keep up at higher rates, causing the glitching (it would also explain why setting it higher than 192khz fails, because OpenSL doesn't accept that rate). It doesn't matter what the input buffer is like if OpenAL is having trouble with the output buffer.

The output buffer does seem to be growing with higher sample rates, but it still might be too much extra work in too short of time for the CPU to keep up. OpenAL should be set to match the hardware and the input stream will be resampled as needed.

> So again, why is the program to OpenAL buffer of a fixed size?

mpv is probably using its own fixed buffer size for the input stream since OpenAL's output buffer metrics don't matter much (as long as the input is big enough, which it is).

**Comment by tomty89** [comment]
AFAIK it is a general approach of mpv that it will not resample if the output driver (OpenAL in this case) can accept the original stream, and apparently OpenAL is happy to take streams range from 8kHz to 192kHz and passes them to OpenSL ES, which apparently in turn passes them to AudioTrack for up/downsampling and mixing. I am not sure what you mean by "mpv tries to set the OpenAL device to use the specified sample rate". Were you implying that it is doing something wrong? (and I don't know how that would be possible if OpenAL doesn't allow it)

> OpenAL should be set to match the hardware and the input stream will be resampled as needed.

This doesn't sound right either. Even when mpv or other programs talk to OpenSL ES directly, OpenSL ES doesn't not expose information about the actual hardware. Neither should it do that coz the hardware can change from time to.time during the playback (from Speakers to Bluetooth to USB Audio and so on...). It is not OpenSL ES doing the resampling either but AudioTrack, which handles the final routing.

I am not sure how (sampling rate / 44100) x 1024 x 3 would be too small when 1024 x 3 is fine for 44.1kHz. But are you suggesting that maybe they should be bumped?

mpv does have a soft buffer for the output driver, by default the size will be set to that of the device buffer, which would normally be reported by the output driver (see the cases of `-ao openal`), unless the reported value is less than a 200ms-equivalent size. It doesn't help work around the issue if I increase the soft buffer size.

I doubt that 32000 originates from mpv's code tho, but I cannot tell for sure it originates from openal-soft's either.

**Comment by tomty89** [comment]
NVM I was wrong, 32000 does originate from mpv:

https://github.com/mpv-player/mpv/blob/037c37519b305bb5d5ea0379122d62ba356cc103/audio/out/ao_openal.c#L280

```
#define NUM_BUF 128
#define CHUNK_SAMPLES 256
...
queued = NUM_BUF - queued - 3;
...
return queued * CHUNK_SAMPLES;
```

Apparently it ends up being `(128 - 0 - 3) * 256 = 32000`, wonder how were the three constants decided and why it is not a value calculated from sampling rate...but that's a question for mpv dev I guess.

In that case perhaps the mpv -> OpenAL buffer really isn't relevant to the OP, probably why `--audio-buffer` doesn't help...

**Comment by kcat** [comment]
> AFAIK it is a general approach of mpv that it will not resample if the output driver (OpenAL in this case) can accept the original stream, and apparently OpenAL is happy to take streams range from 8kHz to 192kHz and passes them to OpenSL ES, which apparently in turn passes them to AudioTrack for up/downsampling and mixing. I am not sure what you mean by "mpv tries to set the OpenAL device to use the specified sample rate". Were you implying that it is doing something wrong?

mpv shouldn't be trying to set the OpenAL device's sample rate to the input stream's sample rate (using the ```ALC_FREQUENCY``` context creation attribute), it should let OpenAL handle it. It can give the stream to OpenAL with the original sample rate, which would let OpenAL resample it as needed for output.

> This doesn't sound right either. Even when mpv or other programs talk to OpenSL ES directly, OpenSL ES doesn't not expose information about the actual hardware. Neither should it do that coz the hardware can change from time to time during the playback (from Speakers to Bluetooth to USB Audio and so on...). It is not OpenSL ES doing the resampling either but AudioTrack, which handles the final routing.

The idea with using OpenAL is that the output system is abstracted away. Apps shouldn't concern itself with whether it's using OpenSL ES or something else. Unless there's a serious issue, it should trust that OpenAL does the right (or good enough) thing.

There is currently an open issue with regards to latency problems with OpenAL Soft's OpenSL backend, but that's actually a result of OpenAL's output (sample rate, update size) not correctly matching what the AudioTrack wants. It also just adds latency, not any stuttery-type glitching. Forcing OpenAL's output to match the input, rather than matching the output system, isn't going to fix that.

> I am not sure how (sampling rate / 44100) x 1024 x 3 would be too small when 1024 x 3 is fine for 44.1kHz. But are you suggesting that maybe they should be bumped?

I'm not sure. I'd need to get more detailed information about what's happening that's causing the glitching. If the CPU is just having too much trouble keeping up, it might need to be bumped. Perhaps it's not properly utilizing NEON extensions, which would slow it down. It might also just be a timing issue rather than a CPU power issue, in which case it would need the mixing thread priority bumped.

**Comment by tomty89** [comment]
> mpv shouldn't be trying to set the OpenAL device's sample rate to the input stream's sample rate (using the ALC_FREQUENCY context creation attribute), it should let OpenAL handle it. It can give the stream to OpenAL with the original sample rate, which would let OpenAL resample it as needed for output.

Why would there be such a method / possibility (`ALC_FREQUENCY`) if an app is not supposed to use it? (In other word, why does `ALC_FREQUENCY` not do the latter? any pointer to what an app should uss instead so that maybe I can file an issue to mpv?)

Btw I alao tested with mpd. Somehow it resamples to 44100 instead of sending stream in the original sampling rate to OpenAL. But from the code it doesn't seem like that's intentional. Could it be because it wrongly have the sampling rate set after the context is created instead of before? Has it adopted the "recommended way" you mentioned?

https://github.com/MusicPlayerDaemon/MPD/blob/91ce76af9d6c86e77acb1f2cdb9cd9aad5847f16/src/output/plugins/OpenALOutputPlugin.cxx#L169

> The idea with using OpenAL is that the output system is abstracted away. Apps shouldn't concern itself with whether it's using OpenSL ES or something else.

True. But what I meant was, OpenAL itself probably need to concern what the backend is and decide whether to perform resample or not. For example, in the OpenSL ES (more precisely the current Android) case, it most likely should not, because not even OpenSL ES appears to keep track of the hardware sampling rate.

> There is currently an open issue with regards to latency problems with OpenAL Soft's OpenSL backend, but that's actually a result of OpenAL's output (sample rate, update size) not correctly matching what the AudioTrack wants.

Well it should not? Why should OpenAL even be aware of AudioTrack? It only needs to match with what OpenSL ES can take (which is not necessarily what AudioTrack can take and let alone the hardware)

**Comment by kcat** [comment]
> Why would there be such a method / possibility (ALC_FREQUENCY) if an app is not supposed to use it?

In the olden days (early to late 2000s) OpenAL could be used with direct hardware, and setting ALC_FREQUENCY could modify the hardware's output (you can still if you happen to have the hardware and appropriate drivers, but it's exceedingly rare and was Windows-only). These days OSs handle audio output at a fixed sample rate, and apps give their streams to the system for mixing and routing to hardware output. The system may do resampling on behalf of the app in case the app has hard requirements for its output sample rate, but the system still plays back at a fixed rate.

In some cases it could also be useful to set a lower sample rate for OpenAL than the system uses, so OpenAL processes and mixes fewer samples and the system upsamples the result (this may or may not help overall CPU usage, depending on how much lower OpenAL's sample rate is and the CPU cost of the system's resampler).

> any pointer to what an app should use instead so that maybe I can file an issue to mpv?

Unless the app has reason to otherwise, it should let the OpenAL device use the default sample rate. The stream it gives to OpenAL can be whatever sample rate the input is.

> Has it adopted the "recommended way" you mentioned?

The code you linked to seems to do the correct thing, yes. OpenAL outputs to 44100hz because that's the typical sample rate used by Android devices, so that's what the system will see the app provide.

> But what I meant was, OpenAL itself probably need to concern what the backend is and decide whether to perform resample or not.

Given that OpenAL is designed for 3D game audio, mixing multiple sounds from various sources with various effects, it can't presume it won't need to resample. It's not like SDL_audio which provides a system-agnostic audio interface and passes the audio you give it to the underlying system. OpenAL is a fully featured sound renderer/mixer.

> Why should OpenAL even be aware of AudioTrack?

Because an app can only get the ```AUDIO_OUTPUT_FLAG_FAST``` feature if the sample rate and update size are specific device-specific sizes, and unfortunately OpenSL doesn't provide that information. It needs to use the Java interface to get those details, and without that feature, you can get latencies of half a second or more (on top of the latency inherent to OpenAL's mixing buffer) because the system needs to do more bookkeeping with the stream before it can safely give it to the real output. For real-time game audio, 500+ms latency is unacceptable.

**Comment by tomty89** [comment]
> OpenAL outputs to 44100hz because that's the typical sample rate used by Android devices, so that's what the system will see the app provide.

That's not really right, at least not for recent/modern Android version.

AFAIK in older Android versions, audio streams will be unnecessarily resampled to the 44100Hz regardless of what the hardware support, then it will be resampled again to meet the need of the hardware. But this is not the case anymore, at least doesn't have to be.

When I play a 48KHz audio on my phone (with either `mpv -ao openal` or `mpv -ao opensles`), I can see that AudioTrack got it unresampled. When I am on Bluetooth Audio, where the input needs to be 44.1KHz, AudioTrack resamples it as needed. But when I am on / switch to the phone speakers / headset jack, AudioTrack does not perform any resampling because the SoC sound card expects 48KHz.

When I play a 44.1KHz audio, I can see AudioTrack got it unresampled as well, and does not perform any resampling when I am Bluetooth. But if I am on / switch to phone speakers / headset jack (SoC sound card), AudioTrack upsamples it to 48KHz as needed.

So in terms of the behaviour of resampling, while both are using OpenAL to get to OpenSL ES, I can see that mpv guarantees the right thing happens, while mpd on the other hand, resamples streams to 44.1KHz unnecessarily beforehand, regardless of the hardware.

And when mpv and mpd speaks to OpenSL ES directly, things are right with both of them. So it would seem to me that, either mpd is not using OpenAL appropriately, or, OpenAL does not do the right thing when it is used in the "recommended way".

> Because an app can only get the AUDIO_OUTPUT_FLAG_FAST feature if the sample rate and update size are specific device-specific sizes, and unfortunately OpenSL doesn't provide that information.

To be honest, it would seem to me that, if OpenAL needs to make use of this feature, it should support AudioTrack directly as a backend (like OpenSL ES does?). I am not sure OpenSL ES is ever supposed to provide the information (or the way to get to AudioTrack if the feature is needed) because it is not what keep track of device changes (AudioTrack is). Also whether the feature is available can change at any point during playback (Bluetooth Audio on, USB Audio inserted...), OpenAL will need to know to reset / adjust dynamically, I would suppose.
