### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by sztomi** [kcat/openal-soft#158]
I'd like to create a conan package for this library. As I understand, this is the de-facto opensource OpenAL implementation, and Debian packages it as `openal`. Is it correct to use that name, or should the package be called `openal-soft`?

**Comment by kcat** [comment]
I'm not familiar with conan packages. I'm not exactly sure why, but my best guess is Debian packages it as ```openal``` because it's the only viable OpenAL implementation for Linux and it helps with package dependencies (apps that use OpenAL just depend on ```openal``` rather than a specific implementation; if other implementations were to appear, they'd probably move it to ```openal-soft``` and make ```openal``` a virtual package provided by the different implementations).

**Comment by sztomi** [comment]
Thanks for the info. I think I'll go with "openal" because I don't see any viable open source implementations on any platforms besides openal-soft. We can always move the same way as Debian if a new implementation would arise.

Conan can be found here: https://conan.io

The package I'm creating will be available in this repository initally: https://bintray.com/bincrafters/public-conan/flac%3Abincrafters
