### ISSUE TITLE
Unreal Tournament 2004: sounds play incorrectly

### ISSUE THREAD

**Issue by Hiradur** [kcat/openal-soft#16]
**Setup:**
tested with build no. 1486 from http://ci.newdawnsoftware.com/view/OpenAL/job/OpenAL-win32/ on Windows 7 x64, M-Audio Fast Track pro sound card
perhaps related to legacy device name rerouting (#14)

**Issue:**
All ingame sounds either
* don't play at all
* are incorrectly positioned in relation to their graphical representation
* play on one speaker only
* don't update with movement of the listener's position

Menu sounds also sometimes don't play.

**Notes:**
Unreal Tournament 2004 offers 4 audio settings:
* Safe mode
* 3D Audio
* H/W 3D Audio
* H/W 3D Audio+EAX

The latter 3 settings offer the same audio experience as described above. In Safe mode sounds either come only from the left, right or center position.

ALSoft Logfile with Loglevel=3:
```
AL lib: (II) alc_initconfig: Supported backends: mmdevapi, dsound, winmm, null, wave
AL lib: (II) ReadALConfig: Loading config C:\Users\Hiradur\AppData\Roaming\alsoft.ini...
AL lib: (II) GetConfigValue: Key disable-cpu-exts not found
AL lib: (II) FillCPUCaps: Detected max CPUID function: 0xa (ext. 0x80000008)
AL lib: (II) FillCPUCaps: Vendor ID: ""
AL lib: (II) FillCPUCaps: Name: "Intel(R) Core(TM)2 Quad  CPU   Q8200  @ 2.33GHz"
AL lib: (II) FillCPUCaps: Extensions: +SSE +SSE2 +SSE4.1
AL lib: (II) GetConfigValue: Key rt-prio not found
AL lib: (II) GetConfigValue: Key resampler not found
AL lib: (II) GetConfigValue: Key trap-al-error not found
AL lib: (II) GetConfigValue: Key trap-alc-error not found
AL lib: (II) GetConfigValue: Key reverb/boost not found
AL lib: (II) GetConfigValue: Key reverb/emulate-eax not found
AL lib: (II) GetConfigValue: Key drivers not found
AL lib: (II) ALCmmdevProxy_messageHandler: Starting message thread
AL lib: (II) ALCmmdevProxy_messageHandler: Message thread initialization complete
AL lib: (II) ALCmmdevProxy_messageHandler: Starting message loop
AL lib: (II) alc_initconfig: Initialized backend "mmdevapi"
AL lib: (II) alc_initconfig: Added "mmdevapi" for playback
AL lib: (II) alc_initconfig: Added "mmdevapi" for capture
AL lib: (II) GetConfigValue: Key excludefx not found
AL lib: (II) GetConfigValue: Key default-reverb not found
AL lib: (II) GetConfigValue: Key channels not found
AL lib: (II) GetConfigValue: Key sample-type not found
AL lib: (II) GetConfigValue: Key frequency not found
AL lib: (II) GetConfigValue: Key periods not found
AL lib: (II) GetConfigValue: Key period_size not found
AL lib: (II) GetConfigValue: Key sources not found
AL lib: (II) GetConfigValue: Key slots not found
AL lib: (II) GetConfigValue: Key sends not found
AL lib: (II) GetConfigValue: Key midi/internal-synth not found
AL lib: (II) SSynth_create: Not using internal MIDI synth
AL lib: (II) ALCmmdevProxy_messageHandler: Got message 1024 (lparam=0A65DCD0, wparam=0018C5C8)
AL lib: (II) alcOpenDevice: Created device 0A64EFE0, "Line 1/2 (5- M-Audio FastTrack Pro) on OpenAL Soft"
AL lib: (II) GetConfigValue: Key frequency not found
AL lib: (II) GetConfigValue: Key sends not found
AL lib: (II) GetConfigValue: Key hrtf not found
AL lib: (II) UpdateDeviceParams: Pre-reset: Stereo, Float, *44100hz, 1024 update size x4
AL lib: (II) ALCmmdevProxy_messageHandler: Got message 1025 (lparam=0A65DCD0, wparam=0018C590)
AL lib: (II) UpdateDeviceParams: Post-reset: Stereo, Float, 44100hz, 882 update size x4
AL lib: (WW) UpdateDeviceParams: SSE performs best with multiple of 4 update sizes (882)
AL lib: (II) GetConfigValue: Key stereo-mode not found
AL lib: (II) GetConfigValue: Key hrtf-mode not found
AL lib: (II) UpdateDeviceParams: HRTF disabled
AL lib: (II) GetConfigValue: Key cf_level not found
AL lib: (II) UpdateDeviceParams: BS2B disabled
AL lib: (II) GetConfigValue: Key layouts/stereo/type not found
AL lib: (II) ALCmmdevProxy_messageHandler: Got message 1026 (lparam=0A65DCD0, wparam=0018C590)
AL lib: (II) alcCreateContext: Created context 0A65DDF0
AL lib: (II) ALCmmdevProxy_messageHandler: Got message 1024 (lparam=0A777450, wparam=0018C584)
AL lib: (II) ALCmmdevProxy_messageHandler: Got message 1025 (lparam=0A777450, wparam=0018C584)
AL lib: (EE) ALCmmdevCapture_resetProxy: Did not get matching format, wanted: Mono Signed Short 16000hz, got: 2 channel(s) 32-bit 44100hz
AL lib: (II) ALCmmdevProxy_messageHandler: Got message 1028 (lparam=0A777450, wparam=0018C568)
AL lib: (II) FreeContext: 0A65DDF0
AL lib: (II) ALCmmdevProxy_messageHandler: Got message 1027 (lparam=0A65DCD0, wparam=0018F268)
AL lib: (II) FreeDevice: 0A64EFE0
AL lib: (II) ALCmmdevProxy_messageHandler: Got message 1028 (lparam=0A65DCD0, wparam=0018F238)
```

**Comment by kcat** [comment]
That's weird. I installed the Linux 64-bit version of UT2004, which uses OpenAL by default, and it works fine. Aside from the device name, I don't imagine the OpenAL code is much different.

What if you try setting the ```__ALSOFT_SUSPEND_CONTEXT``` environment variable to ```ignore```? I'd be surprised if that's the issue since OpenAL Soft's new ```alcSuspendContext``` and ```alcProcessContext``` behavior was designed to match what Creative's Windows drivers did, but the behavior you're describing seems to fit with the idea that it's not updating sources properly.

**Comment by Hiradur** [comment]
```__ALSOFT_SUSPEND_CONTEXT=ignore``` fixes it!

**Comment by kcat** [comment]
I think I may have fixed the problem with commit db0f29f6d86d301b5f57f7dbe97c1544a0f79a10, can you check (make sure not to set ```__ALSOFT_SUSPEND_CONTEXT=ignore```)?

**Comment by Hiradur** [comment]
It's better but not fixed completely. 

Now sounds either
- are correctly played and their position matches their graphical representation
- don't play at all

**Comment by kcat** [comment]
Sounds like the game doesn't like that ```alSourcePlay``` (along with ```alSourcePause```) get deferred too. Likely for certain sources it tries to play when the context is suspended, then checks all active sources and removes the ones that aren't playing (which those newly started ones aren't, if it hasn't processed updates).

One possible way to fix this is to not defer those state changes, but I'm not keen on that since one of the purposely designed abilities here was that you could pause one source and play another while updates are deferred, and be guaranteed that one source stops playback and another starts at the same time. It would also slightly increase the amount of processing since a source would have to have an extra forced synchronous update if it was played while deferred.

Another, slightly more palatable, option is to report the deferred state when queried. So if updates are suspended when ```alSourcePlay``` or ```alSourcePause``` is called, it would still defer those actions but it would report that the source is in a playing or paused state respectively. My hesitation comes from that it would be a lie... I worry that apps could get confused by seeing the source in a playing/paused state when it's not actually playing or paused. I'm not discounting the option, just concerned about it.

**Comment by Hiradur** [comment]
I see. For me it's not that much of an issue since I know ``` __ALSOFT_SUSPEND_CONTEXT=ignore ``` fixes it (is there any downside to this?). But of course it doesn't work out of the box this way.
Perhaps you should leave this issue for a while, maybe another option comes to your mind.

**Comment by kcat** [comment]
> For me it's not that much of an issue since I know __ALSOFT_SUSPEND_CONTEXT=ignore fixes it (is there any downside to this?).

Not really, except there won't be batching updates, which isn't usually a problem.

**Comment by kcat** [comment]
As an update, it's now not too difficult to make a source play right away while updates are deferred, without a forced synchronous update. However, there's some things I'm not sure about.

In particular, say the app calls ```alcSuspendContext``` to defer updates, changes properties on a non-playing source, then calls ```alSourcePlay```. Should those changes apply to the started source, or should the source sound as it would've when ```alcSuspendContext``` was called? And similarly for the listener, if the app suspends updates, changes things on the listener, then plays a source, should the source reflect the most current values or the pre-defer state?

**Comment by Hiradur** [comment]
Tricky question but I'd expect it to use pre-defer state values because it makes more sense.

**Comment by kcat** [comment]
I agree it makes more sense, though it also complicates things a bit. It means I'll have to specify updates (copy all the properties into a separate ```ALsourceProps``` struct) for even non-playing sources in case the app will suspend updates, make more changes, then play; it'd need to have a record of what it should use when the suspend happened, instead of making the updates as-needed. Similarly, if the app suspends updates, then generates a new source, sets it all up, then plays it, I don't think it's the intention that it'll play with completely default properties values.

But the other way also has its issues. If it's intended to use the values as specified when played, that means it'll need to keep specifying Listener updates so a played source will be up-to-date with the listener. And while listener updates don't have a direct effect on the output mix (it instead just stores internal properties that future source updates use), it creates a potential race condition. Say for instance
```
     App Thread         Mixer Thread
---------------------   ------------
Playing Source Update        .
   Listener Update 1         .
      Suspend Ctx            .
   Listener Update 2         .
          .            Internal Update
          .                  .
```
The internal update will process the second listener update made after the suspend, which will affect the already-playing source which made an update before the suspend. The playing source will be influenced by the second listener update even though updates were suspended for it.

I suppose a compromise would be to use the latest source properties at the time of the ```alSourcePlay``` call, but the older listener properties as of the time of ```alcSuspendContext```, and say that playing a source while updates are suspended is just a bad idea because the source's playback state is isn't going to be well defined.

**Comment by fatalfeel** [comment]
can openal hrtf play stereo source music? 16bits 2 channels 44100hz
today i try stereo source no effect, only for mon0 soruce 1 channel

**Comment by kcat** [comment]
Yes, it can play stereo music with HRTF. If you're having problems with that, please open a new issue and provide more information that can help track the problem down (preferably with tests showing it).

**Comment by fatalfeel** [comment]
my code base on git is download on 2016/06/25
is that already can do?

**Comment by kcat** [comment]
@Hiradur I think this should work now with commit 4b153dade82b0558c96d54828bd2f9f86dc808fd. Can you check?

**Comment by fatalfeel** [comment]
finish it by modify code~~~tks~~~~

**Comment by Hiradur** [comment]
> @Hiradur I think this should work now with commit 4b153da. Can you check?

Do you offer prebuilt binaries for Windows of developer versions somewhere (http://ci.newdawnsoftware.com/view/OpenAL/job/OpenAL-win32/ looks outdated)?

**Comment by kcat** [comment]
Hmm, seems Jenkins stopped doing builds for some reason. I'll need to look into that. For now, here's win32 and win64 DLLs of the latest commit:
http://kcat.strangesoft.net/alsoft-win-build-8d3a2865775e1747.7z

**Comment by Hiradur** [comment]
Fixed in https://github.com/kcat/openal-soft/commit/4b153dade82b0558c96d54828bd2f9f86dc808fd
