### ISSUE TITLE
CMake 32bit Builds for MinGW-w64?

### ISSUE THREAD

**Issue by tekrongames** [kcat/openal-soft#161]
Hi, I would like to know how I can do a 32bit build using MinGW-w64 (x86_64-w64-mingw32)? Is there a flag or option of some sort? thanks.

**Comment by iSLC** [comment]
If you're generating a Code::Blocks project, there should be an option like `CMAKE_CODEBLOCKS_MAKE_ARGUMENTS`, or if you're just generating a simple make script, then a similar option should be available. And in that option you should try to add `-m32` to the command line to force the compiler to generate 32-bit output. Kinda like when you specify `-j3` to compile using 3 threads/instances of the compiler.

Might not work perfectly but it's worth a try. Since the library is not using c++11 features then you should not get any compiler errors. Which can occur when using the `<random>` header and trying to compile for x32 using an x64 MinGW-64 compiler.

**Comment by kcat** [comment]
I don't know if x86_64-w64-mingw32 can produce 32-bit binaries. You can setting the ```-m32``` switch like iSLC said (though you can set ```CMAKE_C_FLAGS```, ```CMAKE_CXX_FLAGS```, and ```CMAKE_LINKER_FLAGS``` instead of the CodeBlocks or Make arguments option).

Otherwise, you're better off getting a 32-bit build of MinGW-w64 (i686-w64-mingw32), which will give you the proper 32-bit headers, libs, and DLLs. that the code may need.

**Comment by iSLC** [comment]
I assume (_and nothing more_) that the reason you've chosen this path is because you find it annoying to change the environment path each time you want to switch compilers. And sometimes it might even require a logoff for changes on the path system variable to work.

Which is why you can use tools like docs.microsoft.com/en-us/sysinternals/downloads/junction to create a symbolic link folder that points to the desired compiler. Create some batch files and pin them somewhere easily accessible. This way, you only change the main symbolic link folder to point to which compiler you want and not have to change the path system variable. I'm using it for a multi-compiler architecture/version setup and it makes life much easier.

**Comment by tekrongames** [comment]
Ah thanks @kcat @iSLC CMake `-m32` flag does work, problem solved. 👍

**Comment by sayoojmandodi** [comment]
I tried adding this flag -m32 and am getting a different error now 
"fatal error: bits/c++config.h: No such file or directory"

do I need to add any other flags.
