### ISSUE TITLE
Feature Request: Lazy load all openal functions

### ISSUE THREAD

**Issue by shomarisharpe** [kcat/openal-soft#191]
Hi,
I was wondering if you could implement lazy loading of all functions in OpenAL similar to the way GLEW does it. This way one does not have to call GetProcAddress() for any OpenAL functions. I've found myself having to do this especially for EFX. It would be good if all i had to do is just check for the extension and i'm ready to start calling the functions.

**Comment by kcat** [comment]
Lazy-loading needs to be done on the application's side. A library simply exposes the functions and variables it provides as the public interface, and they get loaded into your program at runtime. GLEW works by defining pointers for all possible GL functions and pairing macro overrides, regardless if they're available or not, and has an explicit initialization function you call to set the pointers for the available functions (e.g. when you call `glUseProgram(...)`, you're actually calling `(*__glewUseProgram)(...)`, where `__glewUseProgram` was set to the address of the real `glUseProgram` function when you called `glewInit()`).

It makes no sense to have this functionality as part of the library itself, since it would depend on directly linking to an appropriate version of OpenAL Soft for those function pointers to exist, which then means you can just use the functions directly without having to load them.

At best, I could provide a separate ALEW type of static library that does a similar thing as GLEW, and can work with any OpenAL library. Although it might be a bit trickier since the AL and ALC APIs aren't as separate as the GL and WGL/GLX APIs (some extensions may have new `alc` functions, which depend on a specific device handle to get or call with, but the ALC API needs to already be set up to get the device handle; it's a catch-22).


A possible alternative to lazy loading could be weak symbols. In this case, you would declare the functions using `__attribute__((weak))` or equivalent, then it will either refer to that function if it exists when loading, or it becomes a null reference (it can be checked like a function pointer prior to being called). I don't have much experience with weak symbols though, so there may be things to watch out for when using them.

**Comment by jhasse** [comment]
I've done this for OpenAL on Windows, so that I could run the installer if needed. The code is here: https://github.com/jhasse/jngl/blob/66ecca5cd1e4a7d7fe36cf50ec978a552ad7ee34/src/win32/openal.hpp
It's C++ though, checks `OpenAL32.dll` and requires `dlfcn.h`.

**Comment by kcat** [comment]
The unfortunate thing with that is it incurs a run-time check for almost every call to the API, even though you know the check will only ever be false the first time it's invoked and never again afterward. I'm also not sure if `std::function` is no-overhead compared to a plain function pointer.

It actually makes me wonder if it's possible to manipulate the PLT or something so that the first time you call to a library's function, it calls a loader function to load the library and get the symbol's address, and then rewrites the table entry to go to the desired function directly every time it's called afterward.

Though in either case, you can reduce the overhead by utilizing GCC's `__builtin_expect`. That can optimize for the case where the check is false, so it's a bit slower on the first call (it'll jump farther away to "cold" memory to load the library) but faster on subsequent calls (it'll flow more efficiently when it doesn't need to load).

**Comment by jhasse** [comment]
IIRC branch prediction will think an if is false (i.e. jump) by default.

Anyway: it should be pretty easy to benchmark the performance impact, I highly doubt it will be noticable.

(std::function should be as fast as function pointers when optimizations are enabled)
