### ISSUE TITLE
Merge freealut?

### ISSUE THREAD

**Issue by tinspin** [kcat/openal-soft#208]
Hi, to make usage of OpenAL easier with MinGW can you include libopengl32.a into the binary download and maybe integrate freealut: https://github.com/vancegroup/freealut

**Comment by kcat** [comment]
Including the OpenGL library is out of the scope of the OpenAL binary download. MinGW should come with it by default anyway (if it doesn't, bug them). I have no plans on merging freealut, since it works just fine separately. Different projects may or may not want to use it, so it's best to leave each project to pick what higher-level library they want to use (if any).
