### ISSUE TITLE
Issue with AL_DIRECT_CHANNELS_SOFT and AL_FORMAT_51CHN.

### ISSUE THREAD

**Issue by LAGonauta** [kcat/openal-soft#209]
Some time ago I sent the following to the mailing list:

> Good day everyone,
> 
> I am doing various changes to MPV's OpenAL output driver and one of those
> is adding multichannel support through MC extensions.
> 
> While experimenting with "AL_FORMAT_51CHN16" (actually "AL_FORMAT_51CHN32"
> but my point stands) I noticed that the back left and back right speakers
> were not being played with "AL_direct_channels_soft" set and my surround
> speakers set to 5.1 (tested on Windows and Linux with PulseAudio).
> 
> The sound is played only if I force my sound card to 7.1 and move the
> connector from the back speakers to the side speakers connection. I tried
> forcing my "channels" to "surround51" and "surround51rear" in the config
> file but it made no difference.
> 
> Is this expected or is this a bug? I understand OpenAL Soft will not
> spatialize the source when "AL_direct_channels_soft" is set but I expected
> sound to be heard on the back speakers of a 5.1 source as the speakers are
> present.
> 
> Thanks.

As I prefer GitHub to deal with issues I am also posting it here. Recently I tried to add AL_DIRECT_CHANNELS_SOFT support to an emulator and the same issue arose. OpenAL Soft seems to be sending the rear sound data to the side speakers, and maybe the side sound data to the rear speakers.

However I do not know if this is an issue with how my Realtek sound card enumerate the speakers, or something else.

Thanks.

**Comment by kcat** [comment]
> OpenAL Soft seems to be sending the rear sound data to the side speakers, and maybe the side sound data to the rear speakers.

From what I've learned, the proper definition for 5.1 setups is to use the side speakers for the "surround" channels. Some audio systems erroneously use or used the back/rear speakers, but it's more correct to use the sides (which makes sense since they should be placed at the sides around 90-110 degrees, rather than 150 degrees in the back).

>  I tried forcing my "channels" to "surround51" and "surround51rear" in the config file but it made no difference.

The `channels` config option works as a hint. Windows doesn't allow using different playback formats, so will be forced to whatever is reported by the system (and if the system reports using the back channels, it'll end up with `surround51rear` regardless). It should work on Linux with PulseAudio though, presuming PulseAudio itself is handling the channels properly.

Regarding `AL_DIRECT_CHANNELS_SOFT` more generally, it really shouldn't be used except with binaural sounds/streams, so it can avoid going through HRTF filters for headphone users. Unless there's specific needs, it should be avoided with surround sound formats because it'll only work correctly with particular output formats; trying to play 5.1 "direct" on stereo or headphone output will cause the front-center and surround channels to be dropped, for instance, and with headphones it will also lose the virtual surround effect. Even plain, non-binaural stereo sounds/streams should avoid direct channels so headphone users will hear it through virtual speakers (listening to non-binaural streams on headphones isn't pleasant, because sounds will pan unnaturally harsh and the brain will interpret non-panned sounds as coming from within the head; the virtual speakers make it sound the same as listening on stereo speakers as intended).

In hindsight, the direct_channels extension wasn't particularly well designed. It does the job it was intended to do (be a pass-through for binaural sounds on headphones, or for special-purpose setups with known configurations, preventing OpenAL Soft's panner from acting on the individual channels), but there are also shortcomings with regards to mismatched output formats. It doesn't help that the OpenAL API hides the output channel configuration (which there are definite benefits to doing so, but it's a double-edged sword in cases like this). If I were to redo it, I'd probably have first made some kind of `AL_FORMAT_BINAURAL*` buffer format extension, and made direct_channels use various channel remapping schemes for mismatched output, while leaving a fallback to the panner for output formats without discrete channels.

**Comment by LAGonauta** [comment]
This issue was fixed by a new OpenAL Soft extension:
https://openal-soft.org/openal-extensions/SOFT_direct_channels_remix.txt
