### ISSUE TITLE
Sound has strange filtering depending on direction head is facing (Minecraft)

### ISSUE THREAD

**Issue by Sonicwave** [kcat/openal-soft#211]
This was reported as https://bugs.mojang.com/browse/MC-121364 on Minecraft's JIRA bug tracker, but it was resolved as "Works as Intended" by a developer and I was told that the issue was caused by LWJGL/OpenAL (instead of the game itself).

Minecraft changed from LWJGL 2 (used in MC 1.12) to LWJGL 3 during the snapshot builds for 1.13 (officially released today), which I believe also updated OpenAL-soft (the developer who resolved the issue said that LWJGL 2 used 1.15.1, while the latest version seems to be 1.18.2 according to http://kcat.strangesoft.net/openal.html).

The issue is that sounds always have a strange "filtering"/muffling applied to them, and turning my head upward or downward also increases/decreases high frequencies (which wasn't the case in older versions). Some people also reported that the sounds are being panned too aggressively when you turn your head left or right. However, some people also don't seem to have this filtering/panning issue.

Here are several videos that show the effect:

- https://www.youtube.com/watch?v=cVx6DRatxOg (compares grass-breaking sound of 1.12 and 1.13)
- More grass breaking [in 1.12](https://www.youtube.com/watch?v=xrcZFuz1f_k) vs [in 1.13](https://www.youtube.com/watch?v=j5gYbs1Ghug) (shows how the sound changes as you turn your head)
- Sounds of attacking monsters/mobs [in 1.12](https://www.youtube.com/watch?v=SiiU0E4tIzg) vs [in 1.13](https://www.youtube.com/watch?v=plJH_p2ifE8)

Any assistance with this is appreciated.

**Comment by kcat** [comment]
By the sounds of it, the newer version is applying HRTF where the old one is plain stereo. Starting with OpenAL Soft 1.18, a generic HRTF data set is built into the library by default. HRTF will also be automatically enabled if OpenAL Soft detects the system device is configured as headphones, since listening to a plain stereo mix on headphones is generally not desirable. HRTF provides a better sense of 3D sound with headphones since it replicates the effect the head has on sound waves coming from various directions. Part of that effect is a subtle occlusion/muffling as a result of the outer ear and head, particularly for sounds coming from behind or below.

There are a few ways the feature can be disabled. The first is by having LWJGL ship with a build of OpenAL Soft that disables the built-in HRTF data set. It can't enable HRTF is there's no data set for it to use. This will prevent it from working for anyone, unless they find an external data set and configure OpenAL Soft to use it.

The second option is the game itself. The `ALC_SOFT_HRTF` extension allows the program to decide if HRTF should be enabled or disabled (or leave it to the library to decide automatically). Although given that the game uses LWJGL, I don't know if that properly exposes the extension.

A third option is the user. The Windows binary download at http://kcat.strangesoft.net/openal.html contains the `alsoft-config.exe` GUI tool, which allows forcing HRTF off. It can alternatively be configured manually, by creating/editing `alsoft.ini` in Windows' `%AppData%` directory, and put the lines:
```
[general]
hrtf = false
```
(the file could instead go in the application's executable directory, but given Minecraft is Java-based, it would probably detect the Java executable's directory instead of Minecraft's jar directory).

**Comment by Spasi** [comment]
LWJGL will continue shipping with the HRTF data. The `ALC_SOFT_HRTF` extension has been available since LWJGL `3.0.0` (Minecraft is on `3.1.6` afaict), so it can be used to disable HRTF spatialization.

**Comment by Sonicwave** [comment]
Many thanks for the responses, the third option worked for me and the sounds changed back to what they were like in 1.12. Is there a similar way for Mac and Linux users to force HRTF off?

**Comment by Sonicwave** [comment]
After further testing, I noticed that sounds are being panned too aggressively when HRTF is disabled via the config method; a slight turn of the head causes the sound to play as if the sound was 90 degrees to the left or right (made a demonstration in [this video](https://www.youtube.com/watch?v=ffwX2WDGqLE)).

**Comment by kcat** [comment]
`front-stabilizer` only affects 5.1, 6.1, and 7.1 output, and `stereo-mode` only dictates whether OpenAL Soft should try to use HRTF/crossfeed filters (if set to headphones) or not (if set to speakers).

For plain stereo, left and right is at -30 and +30 degrees instead of +/-90, since that's where stereo speakers are typically placed and is where a stereo source's channels are placed by default. Adding an option to change that will likely create potential issues elsewhere (see #216), so probably won't be very easy to do without affecting other things beyond mono sound panning. It'll be something for me to keep under consideration, though.

**Comment by kcat** [comment]
The aggressive panning should be address with commit 827c66f4f6f1b84082e2ce77ab0dc82221e6adc7, which is included in the 1.19 release. Stereo panning is widened to be -60 and +60 degrees for left and right.
