### ISSUE TITLE
OpenAL does not respect default pulse device

### ISSUE THREAD

**Issue by hawk78** [kcat/openal-soft#215]
1. **What do I do:**
I start an openal application on ubuntu with pulse and more than one possible device.
2. **What I do expect:**
The default audio device is used by the application
3. **What happens instead**:
The sound comes from a different device. 
4. **Workaround**
Use pavucontrol to switch the playback device.

**Proposed solution**
I have no time to do the coding myself, but the issue looks easily solvable:

Modify the following function in `pulseaudio.c`
```
/* PulseAudio Event Callbacks */
static void context_state_callback(pa_context *context, void *pdata)
{
    pa_threaded_mainloop *loop = pdata;
    pa_context_state_t state;

    state = pa_context_get_state(context);
    if(state == PA_CONTEXT_READY || !PA_CONTEXT_IS_GOOD(state))
    {
```
```
        pa_context_get_server_info(c, server_info_callback, userdata); //add this line
```
```
        pa_threaded_mainloop_signal(loop, 0);
    }
}
```
Add the following function in `pulseaudio.c`
```
    /*
     * Called when the requested information on the server is ready. This is
     * used to find the default PulseAudio sink.
     */
    static void server_info_callback(pa_context *c, const pa_server_info *i,
            void *userdata)
    {
        printf("default sink name = %s\n", i->default_sink_name);
        **//TODO store the default sink_name and use it to put the sink at the beginning of** 
    }
```

Then in `ALCpulsePlayback_deviceCallback` sort devices so that the default one is in the first position of `PlaybackDevices`.

Repeat for capture devices.

**Comment by kcat** [comment]
The default OpenAL device (`NULL`, `""`, or `"OpenAL Soft"`) corresponds to the default device PulseAudio gives for the app, and should also be listed first when enumerating. For the default device, OpenAL Soft creates a playback or capture stream using `NULL` for the PA device name, which has it open its default device given the stream/app name. For playback/capture it simply uses the device it got, and for enumeration it places that device in the list first.

The thing to be careful of is PulseAudio's stream-restore module. When you use something like pavucontrol to change the device or volume of a stream, that module tracks what was set for the stream/app, so the next time the stream is created it can put it back on that device with the appropriate volume (if an explicit device name isn't specified). This is the device OpenAL Soft will detect and use as the default since it's what PulseAudio would open by default without a device being explicitly requested. If you remove/unload that module, OpenAL Soft should use whatever is set as the "fallback" device in pavucontrol.

I this isn't the behavior you're seeing, or isn't the recommended behavior apps should have, please let me know and provide whatever relevant details you can.

**Comment by kcat** [comment]
OpenAL Soft is using the default device PulseAudio has configured for the given app as its default. Be wary of the `stream-restore` module and other potential modules that set a different default for apps than what may be configured as the "fallback device" in pavucontrol.
