### ISSUE TITLE
Resampler Quality

### ISSUE THREAD

**Issue by dezo2** [kcat/openal-soft#219]
This is not an issue, just a question: I always wondered why the OpenAL sounds muffled compared to DirectSound, even with all the processing disabled in plain stereo mode. Then I try move the resampler slider in 1.18.2 alsoft-config all the way left (Point) and now it finally sounds clean and crisp, just like normal DSound output. Is there any documentation for this settings? I wonder when I set the config sample rate to OS default 44.1kHz, is the resampler even necessary? Or is it disabled in "Point" mode? And how is it possible, that the "best" quality slider position sounds like old radio? Not trying to be annoying here, just curious... :-)

**Comment by kcat** [comment]
The resampler is necessary whenever the input (AL buffer) and output (device) sample times aren't aligned. This is usually the result of mismatched sample rates (e.g. a 44.1khz buffer and 48khz device), though it can also be a result of a timing offset (i.e. if the output sample time is in between two source sample times). However, if the input and output sample rates are the same and there's no sub-sample time offset on the input, the samples align and OpenAL Soft disables resampling for that source. Note that the source's pitch (or velocity-based doppler shift) influences this too, as speeding up or slowing down a source effectively alters the sample rate.

The point resampler is a zero-order hold, essentially nearest-neighbor sampling. This is the lowest quality resampler as it causes a lot of aliasing noise; a lot of new frequencies are heard that don't exist in the recorded sound (this can make the sound seem "brighter" or grainier, as a result of adding high frequencies or distortion peaks).

To provide a bit more information, the maximum frequency that a digital sound can have is half its sample rate (the so-called nyquist frequency). So if you have a sound with a sample rate of 22050, it can only contain audible frequencies up to 11025hz. Proper resampling should preserve this, so even if you have an output sample rate of 48khz, an input sample rate of 22050 shouldn't play any frequencies above 11025hz (or for a 11025 sample rate, nothing above 5512hz). This will obviously sound muffled since most sounds normally have frequencies above those limits, and healthy human ears can hear up to 20khz.

A lower quality resampler can make a low sample rate sound seem "clean and crisp" because it essentially fills in those lost high frequencies the brain is expecting to hear with noise. It is, however, just noise, it's not what the original sound or the recording actually had.

The other aspect to this is that real-time resampling is inherently imperfect (in any form, be it point/nearest or something better). Proper resampling involves the use of a low-pass filter to remove would-be high-frequency noise from the result, and a low-pass filter has a trade-off between performance and quality. Keeping the CPU cost down for use in real-time mixing of hundreds of sources means the quality of the low-pass/resampling filter also comes down. In the case of the bsinc12 and bsinc24 (and other anti-aliasing) resamplers, this takes the form of a bit of attenuation in the otherwise-fine upper frequency range, which can create a bit of extra muffling even where it theoretically shouldn't need to happen.

**Comment by dezo2** [comment]
Wow, thank you for the long explanation. Also thank you for making this setting available in config as I don't mind some aliasing in older games. I actually prefer the (unreal) sound of it. Only weird thing is that even samples recorded at 44.1kHz and played clean in wave editors sounds a little muffled in game with the higher resampler settings, but that may be the result of mixing and the filtering in current oal resampling implementation.

**Comment by kcat** [comment]
> Only weird thing is that even samples recorded at 44.1kHz and played clean in wave editors sounds a little muffled in game with the higher resampler settings, but that may be the result of mixing and the filtering in current oal resampling implementation.

It's likely the wave editors are using a lower quality resampler that doesn't attenuate higher frequencies at the cost of more aliasing and distortion noise, or are using a much higher quality resampler than OpenAL Soft since it only has to worry about playing that one sound and little else.

Like I mentioned in the last paragraph, practical resampling is inherently imperfect. Perfect resampling requires infinite resources, and since that's not possible to have, you just need to do the best with what you've got. While it's possible to do it good enough that a person can't perceive any inaccuracies, that will still require a lot of resources, and when the goal is to be fast with a lot of sounds being resampled at once, compromises are needed.

To help visualize, here's a spectrum analysis of OpenAL Soft's bsinc24 resampler. The sound being played is whitenoise (meaning all representable frequencies are present in equal volume, making it easy to see what the resampler does to each frequency) with a buffer sample rate of 44100 (only frequencies up to 22050hz can be represented in the input) and a device sample rate of 48000 (up to 24khz is possible on output):
![wn-bsinc24](https://user-images.githubusercontent.com/1545516/44808340-8269b580-abbb-11e8-88a6-cef6cb5c67cf.png)
The bsinc24 resampler has a -60dB noise reduction, and you can see all the frequencies above the input's 22khz limit are 60dB less than valid frequencies below that limit (everything between the input's 22khz limit and the output's 24khz limit is purely the remaining aliasing noise).

However, to be able to reach -60dB at the 22khz limit, frequencies start reducing at about 16khz. So even though the frequencies between 16khz and 22khz are completely valid, they're partially reduced as a compromise to ensure all aliasing noise above 22khz is properly reduced. That area between 16khz and 22khz is called the transition band. Improving/shrinking the transition band requires either less noise reduction (if it doesn't reduce as much, less room is needed to reach the target volume at the frequency limit), or a higher quality filter (more processing for each output sample to more correctly calculate what it should be).

**Comment by dezo2** [comment]
OK, I understand it now. I am actually learning something here, thanks again.
I think we can close this.
