### ISSUE TITLE
"Click" Sound on Stop of Looped alSource

### ISSUE THREAD

**Issue by PHarbunou** [kcat/openal-soft#220]
Hello, @kcat 
I've downloaded ("git clone") latest version of OpenAL Soft. 
Version: newest version - OpenAL Soft 1.18.2 + fixes (from github)
My target platform/OS: windows (Win32, x86)
Compiler: Intel C/C++ 11.1
Mixers: mixer_c only (no SSE, no SSE 2, no SSE 3, no SSE 4.1)
Resampler: default (linear)
Freq: 44100Hz
wave source files: 44100Hz/16bit PCM Wave / mono

In the moment I tried stop looped alSource (mono) - I can hear "click" sound from time to time:
alSourceStop( _al_source );
How it looks like (recorded output):
![audio3_wave_test1](https://user-images.githubusercontent.com/9641145/44949180-27db8e00-ae35-11e8-9bf3-e35d990d642f.png)
So I wanna know - what's wrong? Maybe I do something wrong. Can you help me to resolve this problem?

**Comment by kcat** [comment]
This generally occurs when a sound is stopped while playing non-0 samples, since it effectively causes the sound to jump to 0 amplitude. Larger changes from non-0 to 0 can cause an audible click, so depending on where exactly the playback offset is when it's stopped, it may or may not "click". As it is currently there's not much OpenAL Soft can do about it, because by the time `alSourceStop` returns the source needs to be finished playing, and it may be some time (relatively speaking) before some more audio is mixed, so it can't wait and fade out what's currently playing with the next mix.

You can work around the issue by first setting the source's `AL_GAIN` to 0, wait a few frames (~30 or 40ms), then stop the source for real. OpenAL Soft will fade the source gain to silence the source without risking audible clicks, then after a bit of time you can stop the source since it won't be playing anything audible.

**Comment by kcat** [comment]
> May I help you to improve/fix your code to be more compatible with Intel C/C++ Compilers? May I help you to improve your code to be more compatible with "exotic" Platforms?

Sure.

> May I help you to write ASDR filter to avoid "click" problems?

It's not really an issue with applying a release fade. The problem is simply that `alSourceStop` needs to stop processing the source right away. It can't wait for the next mixing update to fade out the sound, nor can it return from the call while a future mix may still use the source. It would need a lot more deeper changes to virtualize resources so the mixer can continue to access and mix buffers regardless of what OpenAL calls the app makes.

**Comment by kcat** [comment]
The latest Git version should improve this situation. If a sound is stopped or otherwise ends with non-0 amplitude, OpenAL Soft will fade out the residual offset which should avoid the most apparent noise.
