### ISSUE TITLE
OpenSL backend: Use environment variable to get optimal buffer size and frequency for fast path

### ISSUE THREAD

**Issue by MikuAuahDark** [kcat/openal-soft#233]
#91 is no longer possible (and it's not good approach anyway) with current release. I'm thinking of using environment variable to retrieve the optimal buffer size and optimal frequency for fast paths. This way, we can tell user to set specific environment variable to allow OpenAL-soft initialize OpenSL context with fast paths.

Example, considering `ALSOFT_OPENSL_BUFSIZE` is the optimal buffer size, and `ALSOFT_OPENSL_FREQ` is the optimal frequency.

1. User set those environment variable from location where it has access to Java stuff, but before OpenAL is initialized.
2. User initialize OpenAL
3. OpenSL backend of OpenAL checks for `ALSOFT_OPENSL_BUFSIZE` and `ALSOFT_OPENSL_FREQ` environment variable and use it to create the OpenSL audio context, possibly gaining fast paths.

If you need example how it's implemented, I have modified OpenAL-soft 1.17.0 in my fork of LOVE here https://github.com/MikuAuahDark/livesim3-love-android/blob/master/love/src/jni/openal-soft-1.17.0/Alc/backends/opensl.c#L335 (I used different environment variable, but the implementation should be something like that).

**Comment by jhasse** [comment]
Why not pass the Context to OpenAL Soft?

**Comment by kcat** [comment]
For the sample rate, you can pass  the `ALC_FREQUENCY` attribute to `alcCreateContext`. The app's Java code can grab the native sample rate and ensure that gets passed to OpenAL (either through a Java binding, or into other native code that itself calls OpenAL).

The buffer size is the tricky bit, since standard OpenAL hides that information. At best, there's `ALC_REFRESH`, but that's not the same thing (it's inaccurate for buffer sizes, and OpenAL Soft ignores attempts to set it anyway). Internally, OpenAL Soft of course essentially works with a device buffer that's divided up into equally-sized periods, and every time the device needs more samples it gives them in period-sized chunks. It's this period size that OpenSL wants to be a specific size to get low latency, but the total buffer size plays into performance and does still affect the latency. So if you want to control the period size, you generally want to control the period count too. And ideally you'd pass these parameters through as context attributes along with `ALC_FREQUENCY` (as an extension).

But different device APIs use different methods for specifying the buffer metrics, so it's not clear which an OpenAL extension should use. Some specify the total buffer size in time (e.g. nanoseconds), and the period size in samples. Some specify the period size in samples and the period count. Others specify the total buffer size and the period count. These all come down to the same thing, just expressed differently, and there's pros and cons to each method. Additionally, since the values given to OpenAL would be suggestions, if something like the sample rate gets changed from the suggested value because the device needs something different than requested, how should the buffer metrics change if they should at all? And there's considerations for things like SSE and NEON which work with groups of 4 floats or ints, so its best for the period size to be a multiple of that.

**Comment by MikuAuahDark** [comment]
So any idea about how to pass the buffer size? Or, what extension should I pass to `alcCreateContext` to ensure the OpenSL buffer size to be multiple of samples needed for fast path (for frequency, I pass `ALC_FREQUENCY`)?

> And there's considerations for things like SSE and NEON which work with groups of 4 floats or ints, so its best for the period size to be a multiple of that.

If you mean the optimal buffer size must be power of two, then Android can't guarantee this. Example, for my phone, the optimal sample rate is 48000Hz, and the buffer size is 384 samples (or multiple of this). 384 is not power of two (it's `2^7*3` to be exact), although 384 is divisible by 4, so I think the SSE/NEON instructions should work.

**Comment by kcat** [comment]
> So any idea about how to pass the buffer size?

Currently you can't. An extension will need to be made, after figuring out the most appropriate behaviors (how it should behave if the sample rate changes) and how the parameters would be best specified (given the number of ways buffer lengths can be declared).

> If you mean the optimal buffer size must be power of two, then Android can't guarantee this.

Not power-of-two, no. A power-of-two would guarantee optimal size even as the SIMD width grows (e.g. SSE and NEON work on 32-bit multiples of 4, AVX can work on 32-bit multiples of 8, maybe a future thing can do multiples of 16), but OpenAL Soft currently only uses SSE and NEON, so it works optimally with multiples of 4. I should note that it will still work even without the buffer size being a correct multiple. It'll just fall back to non-SIMD operations for the final 1, 2, or 3 samples; not the best since the loop for the final samples won't optimize very well, but not the worst thing.

**Comment by MikuAuahDark** [comment]
> how it should behave if the sample rate changes

Not sure what do you mean by this one. Isn't the sample rate only change between devices? or is there a special case where the optimal sample rate changes?

**Comment by kcat** [comment]
Different devices/systems may have different sample rate limitations. So for example, if you request something like:
```
ALCint attributes[] = {
    ALC_FREQUENCY, 44100,
    ALC_PERIOD_SAMPLES_SOFT, 1024,
    ALC_PERIOD_COUNT_SOFT, 3,
    0 /* EOL */
};
context = alcCreateContext(device, attributes);
```
And it turns out the particular device can't set 44.1khz and you get 48khz instead, what happens to the period samples and/or count? Or if you request 48khz but you get 44.1khz instead?

If it's left alone (so it still uses a period size of 1024 samples and 3 periods) the latency will be different as each period will play faster or slower (1.09x or 0.92x, in this example). But if the number of samples-per-period is changed, it produces a different number of samples per update. Alternatively, the period count could change, so while there would be some variation in latency, it stays roughly similar without changing the samples produced per update. Though that still means the system needs to wake up more or less often.

**Comment by MikuAuahDark** [comment]
For OpenSL, it will throw error (for weird sample rate), or just works (for
common sample rate, and rejected for fast path). It's just for fast path
requirement that device sample rate + buffer size must be used. Otherwise,
it will still work, but it's rejected for low latency.

Pada tanggal Sel, 16 Okt 2018 05.46, kcat <notifications@github.com>
menulis:

**Comment by MikuAuahDark** [comment]
I don't understand why if the frequency changes (due to device not supporting it) but leaving the period cause the audio to play faster or slower. I thought change in samples count means the mixer only called more or less often. Also since it's just a hint, then OpenAL doesn't have to obey with the attributes at all right?

Say, if the sample count is 1024 (assume 1 period count for simplicity), and if the frequency is 44.1KHz, then the mixer will be called at every 23.21ms, and if the frequency is 48KHz (same sample count), then the mixer will be called at every 21.33ms.

**Comment by kcat** [comment]
> I don't understand why if the frequency changes (due to device not supporting it) but leaving the period cause the audio to play faster or slower.

The audio wouldn't play faster or slower, but the latency would change. For example, the app does something silly like specify a sample rate of 96khz, and a period size of 1920 samples. The mixer would be called once every 20ms. But the device can't support that rate, and changes to 44.1khz instead. Now the mixer would be called every 44ms, more than doubling the latency.

Or say the app specifies an output sample rate of 22050hz and a period size of 441 samples. This would again mean the mixer is called every 20ms, but the device can only use 48khz. So instead, it'll be called every 9.2ms. The latency is more than halved, but there's a more subtle problem; some systems have a thread wake-up granularity of about 10ms, meaning the thread will always be waking up a bit late and potentially cause underruns.

**Comment by MikuAuahDark** [comment]
I'm losing track of this issue so I'll close this one.
