### ISSUE TITLE
Doppler effect broken for M>1 in FlightGear

### ISSUE THREAD

**Issue by mike402** [kcat/openal-soft#247]
In FlightGear aircraft can still be heard when approaching the camera at supersonic speeds.

Steps to reproduce:
1. Compile FlightGear with OpenAL
2. Spawn in a supersonic aircraft, exceed M=1
3. Put the camera in Fly-by mode, the sound of approaching aircraft is still there

Someone said OpenAL implementations arbitrarily limit pitch -- could it be the reason? Someone else said this does not happen on all OS or all versions of openal-soft. So my setup is:

* FreeBSD 11.2-RELEASE-p4
* FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
* openal-soft-1.19.0

**Comment by kcat** [comment]
I'm not sure there's anything to fix, unless there's more information about what exactly the issue is. If it's just the fact that you can hear sources moving toward the listener faster than the speed of sound, that would be because OpenAL isn't designed to apply distance-related delays (when it comes to virtual environments, the position and movement of sources and the listener don't always follow physical laws, so the app needs its own discretion on how to deal with distance and speed). Calculating the proper response from a sound source moving faster than its generated soundwaves can propagate would also be a complicated task. Those things are generally left to the app to implement, delaying source state changes depending on its distance and having prefab recordings of the desired super-sonic effects (the sonic boom and the like) to play at the appropriate time.

**Comment by mike402** [comment]
Sorry, I had confused the effects at the time. Indeed, modeling the sound cone is a matter of delay, not frequency shift.
