### ISSUE TITLE
Forcing frequency

### ISSUE THREAD

**Issue by DatCaptainHorse** [kcat/openal-soft#248]
Should I specify, in Windows OS? Don't know if this is OS specific.
Is it possible to force a specific frequency for context or device? Other than using config file.

Here's the issue:
- Bobby is a normal user, who has set their audio device's output frequency to 192kHz, because bigger means better right?
- The developer has implemented runtime HRTF on/off changing, but the HRTF's are limited to specific frequencies.
- Bobby wants to turn on HRTF, but an error pops up..
`AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 192000hz instead`
- Bobby sends bug report to developer
- Developer knows the issue and as temporary fix tells Bobby to change audio device's output frequency to 48kHz.
- Bobby does so and things start working well on his side
- Developer starts looking for permanent solution to the issue, since it's been bugging him for a while. Maybe you can reset the device with AL_FREQUENCY attribute to set it to 48kHz?
`Failed to set 48000hz..`
that failed.. 
- Developer is using his Google'Fu, looking through old posts, going through project GitHub wiki, looking at old issues and pull requests for last chance of hope.. he found nothing, and the last pint of hope was lost.

**Comment by kcat** [comment]
The main problem here is that Windows (WASAPI) doesn't allow apps to set a different sample rate for its playback stream; it won't resample for you. To support different sample rates, I'd have to add a separate resample pass on the final mix prior to output, which is doable but unlikely to have good quality for a number of reasons (OpenAL Soft's resamplers having speed vs quality tradeoffs, and the hardware probably not handling 192khz well with no audible benefits), not to mention the extra processing overhead. It also adds a bit complexity when trying to figure out what sample rate or HRTF to use (HRTF has no way to know what the device's "ideal" sample rate to use, and the device backend doesn't know if the default sample rate is good for HRTF). The best solution is to ensure the device is set to something reasonable, like 44.1 or 48khz.

But I can try to find the best way to handle optional resampling depending on HRTF's needs. Perhaps limit the internal mixing to 48khz and resample up as needed, since resampling every source up to 96 or 192, and processing all effects at 96/192, is pretty wasteful. Mix to 48khz then resample the final mix up may be ultimately cheaper.

**Comment by CaptainHorse** [comment]
If you could find a way, I'd be thankful. I'm not experienced enough with audio programming to contribute on the issue so I'll have to apologize on that.

**Comment by mirh** [comment]
You likely can't force shared-mode "engine" parameters from applications, but even putting aside exclusive mode (and that you can use [GetMixFormat](https://stackoverflow.com/questions/41876857/interpreting-waveformatextensible-from-iaudioclientgetmixformat) to query it), this is the first time I hear windows doesn't automagically resample whatever. 

Said this, I mean, talking about the performance vs "what's-on-the-tin" issue.. if masochistic people think the bigger the better, *logically* they should have it. If any there could be an env_var/switch/setting to force a specific rate in openAL.

**Comment by kcat** [comment]
FWIW, this is possible now in 1.23. The WASAPI backend can accept different sample rates and will use a resampler on the output if the device doesn't accept the requested rate. So even if the user has something like 96khz or 192khz set, the app can request 48khz with the ALC_FREQUENCY attribute to have OpenAL Soft use that lower rate, with a 48->96/192 resample done on the final mix (this will of course slightly increase latency, as resampling invariably does, but not by much).

**Comment by DatCaptainHorse** [comment]
\o/ you're amazing! I won't be able to check out the resampler yet but I believe you can close this issue, about time right?

**Comment by kcat** [comment]
If you find a problem with the resampling (stuttering, skipping, crackling), feel free to reopen this or create a new issue about it.
