### ISSUE TITLE
Feature request: Add fade-out to audio files that end prematurely

### ISSUE THREAD

**Issue by Polymega** [kcat/openal-soft#273]
Hi @kcat, 

I'm absolutely loving openal-soft! When used with Silent Hill 2 PC, it literally sends shivers down my spine to hear its audio sound stage rendering properly like it does on the PlayStation 2 version. Phenomenal stuff, really. 

**IDrinkLava** has already spoken to you on my behalf of this request, but I thought I'd make a proper ticket on the matter: 

--------------------------

[I'm part of a development team that is both fixing up and enhancing the PC version of this game.](https://github.com/elishacloud/Silent-Hill-2-Enhancements) Part of our project was enhancing the audio for the game. [To do this, last year we replaced all of the PC's heavily-compressed audio files with the PS2 version's superior files.](https://www.youtube.com/watch?v=2Ml6py5J7hA) And what an incredible night-and-day difference it made!

But the one thing lacking for people who play the game in this day-and-age is 3D audio: Playing older games that used hardware accelerated 3D audio on newer Windows just doesn't work out-of-the-box, as you know. 

And on top of that, there's one huge issue with the PC version and how it plays sound files: If the game cuts off any audio file short for whatever reason, it doesn't add any sort of fade out to the sound file. As a result, you hear harsh "clicks" and "pops" when this happens as demonstrated here: 
https://youtu.be/6v1USVhtfjQ?t=217
https://www.youtube.com/watch?v=46mAswB8L6E

For that reason, we instruct users for our project to use IndirectSound. The reason being is that IndirectSound has a feature within itself called `earlyStopFadeOutTime` and, by placing a value such as 0.002 (two milliseconds) in its .ini file, it will add a two millisecond fade out to any audio file that ends prematurely. 

[IDrinkLava released a video a few months back](https://www.youtube.com/watch?v=36l1nTb9dNY&t=8s) that shows how openal-soft works with Silent Hill 2 PC and... wow. openal-soft seems to correctly render spatial sound scatter (HRTF) just like the PS2 version did. And while IndirectSound is great, it doesn't present the sound stage that openal-soft does (in regards to HRTF).

Unfortunately though, the "clicks" and "pops" are way too prominent in this game to be ignored, but man-oh-man does openal-soft do magic for the game! Could a fade-out feature for audio that ends prematurely be implemented into openal-soft?

Thanks for your time and really amazing work on this mod!

**Comment by KuehnhammerTobias** [comment]
Yeah! This would be a tremendous improvement! Ioquake3 + OpenAL Soft also suffers from those "clicks" and "pops" caused by files that end prematurely. So other games would profit as well!

**Comment by kcat** [comment]
Hmm, you know, I just had the craziest thought just now. The problem here, as described in issue #220, is that the source needs to stop immediately upon `alSourceStop`, meaning it can't render any more samples from the buffers it was playing because they can be immediately removed from the source and go away. Trying to allow it access to the buffers afterward anyway would just be a recipe for a mess. As a result, the sound amplitude effectively jumps from whatever it was at in the last mix, to 0.

Now, the good thing here is that I've separated the `source` object that the app generates and manipulates, from the internal `voice` object that the mixer uses for rendering. The issue has been the `buffer` objects, as they hold the actual sample data. Buffers can be altered or deleted essentially at any time after `alSourceStop` returns, which is what makes it unsafe for the voice to continue accessing the samples after the source is stopped.

However, I just realized. The internal voice object actually holds a (short) history of samples it's been playing, for resampling purposes. In theory, I could use those samples to synthesize another mix and bring the amplitude back down to 0 more gracefully without the source or buffer. It of course wouldn't be perfect (without the actual samples it would've played, it is at best just guessing), but a long time ago OpenAL Soft used to use a similar trick to smooth out abrupt panning and volume changes, before the per-sample gain stepping was implemented in the mixer. I remember it being pretty good at getting rid of the worst clicks and pops.

That might be something to look into trying out.

**Comment by Polymega** [comment]
I'm happy to give it a solid play test within Silent Hill 2 PC if/when that time comes. Thanks for your response and consideration, kcat!

**Comment by kcat** [comment]
Commits 87479b4b3207a0600586c919c03b5cee7af5154e and 106671d45185576e9386eaf0c27211446c8ebce5 should help prevent clicks and pops when a sound ends with non-0 amplitude (either normally, or being stopped/paused mid-sound). If you're able to build current master, feel free to give it a shot.

**Comment by Polymega** [comment]
Thanks, kcat! There is definitely a noticeable improvement in eliminating the clicks/pops versus the vanilla PC game.

A few questions, if you don't mind me asking:
1. Is there any way to adjust the "aggressiveness" of the fade out? Such as a line that can be added to `alsoft.ini` to increase the start time/fade out length?
2. There's some oddities in audio behavior with Silent Hill 2 PC. Here's a video/audio example: 
https://youtu.be/sLn98E16qCQ
The radio static shouldn't fluctuate in volume like it is doing and rather should sound like this: 
https://youtu.be/pjW-0jBaaLE
(The second video example is using [DSOAL 1.31](https://www.nexusmods.com/newvegas/mods/65094/) with OpenAL-Soft integrated.)
Is there perhaps a setting within the .ini I need to adjust to get the radio static sounding correct again? [I've read through the example .ini file](https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample) and tried out a few settings but to no success.

Thank you for any advice, sir.

**Comment by kcat** [comment]
> Is there any way to adjust the "aggressiveness" of the fade out? Such as a line that can be added to alsoft.ini to increase the start time of the fade out?

Unfortunately no, it has no real choice but to start fading out as soon as the sound is told to stop or pause. It simply has no more audio to play and needs to bring the amplitude from what it last had to 0. At best I could tweak how long it takes the amplitude to fade, but ideally you wouldn't directly hear that (you'd just hear the sound stop, and the subsequent fade just removes the residual DC offset).

> There's some oddities in audio behavior with Silent Hill 2 PC. Here's a video/audio example:
> https://youtu.be/sLn98E16qCQ
> The radio static shouldn't fluctuate in volume like it is doing and rather should sound like this:
> https://youtu.be/pjW-0jBaaLE
> (The second video example is using DSOAL 1.31 with OpenAL-Soft integrated.)

It sounds like part of the sound effect is cutting out when it shouldn't. Is this related to DSOAL or OpenAL Soft? I.e., does it only happen when you update `dsoal-aldrv.dll` with the new OpenAL Soft DLL, and keep the same dsound.dll? What about if you use OpenAL Soft 1.19.1 (downloads [here](https://openal-soft.org/openal-binaries/))?

**Comment by Polymega** [comment]
Hi kcat,

My sincerest apologies for taking well over a year to respond back to this. We've been so caught up with our project for the game I lost track of time... big time.

As a refresher, when using newer builds of DSOAL (sometime past DSOAL v1.31a) the radio static for the PC game _Silent Hill 2_ doesn't sound correct. The radio static's volume will cut in and out, seemingly related to your character's position/orientation to the monsters (which produce the static).

Incorrect with DSOAL: https://youtu.be/sLn98E16qCQ
Correct with DSOAL (tested with 1.31 and 1.31a): https://youtu.be/pjW-0jBaaLE

> It sounds like part of the sound effect is cutting out when it shouldn't. Is this related to DSOAL or OpenAL Soft? I.e., does it only happen when you update dsoal-aldrv.dll with the new OpenAL Soft DLL, and keep the same dsound.dll?

Yes, this looks to be the case. If I keep the `dsound.dll` file from DSOAL 1.31a, but use a newer version of the `dsoal-aldrv.dll` file, the radio static is renders incorrect.

My apologies again as, at the time a year ago, I wasn't 100% sure what was doing what, in regards to your project. From what I understand, the `dsound.dll` file is for DSOAL, and the `dsoal-aldrv.dll` file is OpenAL Soft packaged in such a way for DSOAL to work/read from?

**Comment by Polymega** [comment]
Forgot to mention something important! The original intention of this ticket was about fading out audio that ends prematurely to prevent clipping (clicking and popping). Your added-feature to OpenAL Soft did nice work with this, but for _Silent Hill 2_ PC, we needed a more "aggressive" solution. 

I'm happy to say [our lead developer has made an integrated solution](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/21072fea74b22ced9cfc043e2115c95667d6c992) for this issue within the game. So because we've addressed the audio click/popping for the game, in the near future we will be including DSOAL as part of [our project's installation process](http://enhanced.townofsilenthill.com/SH2/install.htm)! This is exciting for us as we've been wanting to incorporate your brilliant DSOAL for a while now!

At the moment, we plan to include DSOAL 1.31a as part of the installation process. But I wanted to discuss the audio issue I found with the game using later versions, in case it's something that might be looked into (in case this issue might affect other games in a similar manner).

Thanks for all your hard work keeping old PC games sounding alive and well!

**Comment by kcat** [comment]
> From what I understand, the dsound.dll file is for DSOAL, and the dsoal-aldrv.dll file is OpenAL Soft packaged in such a way for DSOAL to work/read from?

Correct. DSOAL is really just dsound.dll which translates DirectSound calls to OpenAL, while dsoal-aldrv.dll is just OpenAL Soft with a unique name (necessary to avoid conflicts with apps that utilize both DSound and OpenAL).

> Your added-feature to OpenAL Soft did nice work with this, but for Silent Hill 2 PC, we needed a more "aggressive" solution.

To be clear, the ant-click/pop feature isn't the cause of sounds cutting out, missing, or being too quiet. The feature only affects sounds that are called to stop/pause, which would previously just immediately cut off. Now a sound that is paused (stopped from a DSound perspective) fades out in around 20 milliseconds, practically instantaneous... it would sound exactly as if you set the gain to 0 while playing (only difference is, it maintains a proper playback offset and automatically stops mixing after the fade). For a sound that actually stops (released in DSound), it ends even faster -- after 24 samples (about 0.5 milliseconds), with the remaining 19~20 milliseconds or so removing the inaudible DC offset.

For a sound that's supposed to be playing/audible, the feature should have no effect at all on it. If sounds are missing or end prematurely, it has to be something else. Though unfortunately, 1.20 had a lot of changes, as that release saw the codebase change from a mishmash of C89/99/11 and various compiler extensions and hacks, to C++11 and some compiler extensions. The only way to pinpoint the of improper sounds cause would require bisecting between 1.19 and 1.20, which itself could be problematic since various points in between may have their own issues with compilation and temporarily disabled code.

**Comment by Polymega** [comment]
> To be clear, the ant-click/pop feature isn't the cause of sounds cutting out, missing, or being too quiet.

Yes sir, understood. The incorrect radio static for the game is something unrelated to the click/pop fix you've included to the project.

> The only way to pinpoint the cause of improper sounds would be bisecting between 1.19 and 1.20, which itself could be problematic since various points in between may have their own issues with compilation and temporarily disabled code.

It'd be like trying to find a needle in a haystack. Completely understand. 

We'll include DSOAL 1.31a as part of our project, no problem there, as it's confirmed to be working well with the game from various play testers. But thank you for taking the time to speak with me and discuss out loud the hurdles and concerns that would come from trying to troubleshoot the radio static issue for later builds. I'm happy you were able to create a pop/click fix from this as well... a subtle but very nice feature!
