### ISSUE TITLE
5.1 (Rear/Side) problem

### ISSUE THREAD

**Issue by donizettilorenzo** [kcat/openal-soft#276]
1) No problem with 1.19.1: OpenAL Soft 5.1 (Rear/Side) respects 5.1 settings in Windows Mixer (I always set it to 5.1 and let only play FR and FL, so using headphones I got the mixdown and it's *necessary* for some games to work right 'cause they do NOT handle really well the classic "stereo")

2) With lastest master (compiled+linked in MSVC) OpenAL Soft 5.1 (Rear/Side) positional sound is a mess (stereo is OK but 5.1 puts all center/L+R sounds to FR and 7.1 kills the volume - no actual normalization? )

**Comment by kcat** [comment]
OpenAL Soft's output should be set to whatever is set for the device in the system settings. If the device reports 5.1, it should produce a 5.1 mix, if it reports stereo, it should produce a stereo mix. It's then the system that does any downmixing. I can't think of anything since the 1.19.1 release that would change the output behavior like you describe.

Can you get a trace log from both a good build (from 1.19.1) and a bad one (from master)? Set the `ALSOFT_LOGLEVEL` environment variable to 3, and capture stderr (or also set `ALSOFT_LOGFILE` to a file to write to).

You can also try doing a git bisect to see which commit the problem started with (this might be a little difficult around the switch to C++, as there might be a few commits where output doesn't work or it fails to properly build).

**Comment by donizettilorenzo** [comment]
1.19.1:
AL lib: (II) UpdateDeviceParams: Channel config, Dry: 6, FOA: 0, Real: 0
AL lib: (II) UpdateDeviceParams: Allocating 6 channels, 49152 bytes

compiled:
AL lib: (II) UpdateDeviceParams: Channel config, Main: 5, Real: 6
AL lib: (II) UpdateDeviceParams: Allocating 11 channels, 45056 bytes

11 channels?

**Comment by donizettilorenzo** [comment]
Another strange difference is the presence of

`anonymous-namespace'::InitPanning: Enabling second-order ambisonic decoder"

in the new version.

**Comment by kcat** [comment]
5 for the main (second-order ambisonic) mixing buffer, and 6 for the real 5.1 output. Previously it would render directly to the "real" output using somewhat exotic panning calculations that skipped the intermediate buffer. Now it always uses the intermediate buffer and does a separate "decode" (really just a simple remix).

I think I see the problem, though. I got the indexing wrong when setting up the decode/remix gains. I just pushed a fix for this.

The anonymous-namespace:: bit is intriguing. I guess it's just how MSVC supplies the name from `__FUNCTION__`.

**Comment by donizettilorenzo** [comment]
Thanks man, will try now ;)

**Comment by donizettilorenzo** [comment]
It's working as intended now, issue solved!

**Comment by kcat** [comment]
Fixed with commit d802a5785eb2dd1c7cd1fe60810734cf1dddf29c.
