### ISSUE TITLE
Major performance issues with HRTF on Intel Atom [GZDoom]

### ISSUE THREAD

**Issue by OrdinaryMagician** [kcat/openal-soft#279]
This is something that I've previously reported on the zdoom forums [here](https://forum.zdoom.org/viewtopic.php?f=7&t=64084), but it seems more appropriate to report it here instead. Though a device like the GPD Pocket seems more than capable of performing adequately, this specific issue just bugs the hell out of me. Having anywhere above 128 simultaneous sound sources active AND also HRTF enabled results in an exponential degradation of performance, eventually resulting in an almost complete halt of the program. I really don't know anything about the openal library so I wouldn't know where to start to track down why this is happening.

**Comment by kcat** [comment]
HRTF is a pretty CPU-costly effect. OpenAL Soft's audio processing also relies on good single-threaded performance; it itself works asynchronously in a background thread, but everything it does to prepare and send the audio mix is on one thread, and it's a time-sensitive task. Depending on the CPU, that number of sources with HRTF may just be a bit too much to handle in the time it has available.

The CPU you mentioned in that thread seems to vary its clock frequency, between 1.6 and 2.5Ghz. One possibility is, given the way audio is periodically processed in chunks, it's confusing the internal power management and not letting the CPU run as fast as it needs to for both the game and audio. Since you mentioned you're on a laptop, I assume the game is using the integrated graphics? If so, perhaps the graphics processing is also eating into the processing for other tasks.

What version of OpenAL Soft are you using? Newer versions should have performance improvements over older ones, though I can't recall exactly which versions included which improvements. There is also an option to use a "basic" rendering method for HRTF, which may be a bit more efficient with a higher number of sources, at the cost of some quality. It's not part of the GUI configuration app currently, but you can enable the mode by simply creating an `alsoft.ini` file (on WIndows, or `alsoft.conf` on other OSs) in the same folder as gzdoom's executable, with the contents:
```
[general]
hrtf-mode = basic
```

**Comment by OrdinaryMagician** [comment]
Let's see... It's 1.19.1.

Adding that to my .alsoftrc did the trick, at least.

**Comment by Slion** [comment]
Related to issue #302.

**Comment by kcat** [comment]
1.20 has further performance improvements for HRTF rendering. The `alsoft-config` GUI also allows selecting simpler HRTF rendering methods. I'm not sure what else to do here, beyond a general 'improve HRTF performance'. I don't think it would be a good idea to use the simpler HRTF methods by default, and I don't know of a way to detect systems where it would be desirable.
