### ISSUE TITLE
ALC_SOFTX_device_clock

### ISSUE THREAD

**Issue by openalext** [kcat/openal-soft#28]
Hi, why does the extension `ALC_SOFTX_device_clock` use a different spelling in the extension list obtained with `alcGetString` than in the codebase itself?

``` c
#ifndef ALC_SOFT_device_clock
#define ALC_SOFT_device_clock 1
typedef int64_t ALCint64SOFT;
typedef uint64_t ALCuint64SOFT;
#define ALC_DEVICE_CLOCK_SOFT                    0x1600
typedef void (ALC_APIENTRY*LPALCGETINTEGER64VSOFT)(ALCdevice *device, ALCenum pname, ALsizei size, ALCint64SOFT *values);
#ifdef AL_ALEXT_PROTOTYPES
ALC_API void ALC_APIENTRY alcGetInteger64vSOFT(ALCdevice *device, ALCenum pname, ALsizei size, ALCint64SOFT *values);
#endif
#endif
```

**Comment by kcat** [comment]
Because the extension is incomplete. Things may change, be added, and/or removed, and isn't (yet) intended for apps to use.  It will change to ```ALC_SOFT_device_clock``` when it's done.

**Comment by openalext** [comment]
Oh, I see. Is this the same clock that the future MIDI component will use? And BTW, what is the status of MIDI in OpenAL-soft? I've seen some forks with MIDI support, but nothing MIDI-related in this repository.

**Comment by kcat** [comment]
The MIDI component would use the same clock, yes, since it's all based on the same timing source. The device clock could be used for other things though, such as measuring time from the device's perspective or whatever future extensions may want a device time point, so it's designed as its own separate thing.

As for MIDI, I the removed the code a little while back since it wasn't progressing (some details were still hazy, and the intent was that OpenAL Soft would be able to render it itself), and otherwise relied on an external lib that was difficult to use outside of Linux.

**Comment by kcat** [comment]
The extension has been completed, BTW. The extension spec can be read [here](http://openal-soft.org/openal-extensions/SOFT_device_clock.txt).
