### ISSUE TITLE
Missing backends

### ISSUE THREAD

**Issue by numberZero** [kcat/openal-soft#280]
When OpenAL detects running JACK (by presence of a `JACK_PROMISCUOUS_SERVER` variable), it lists single “JACK Default” playback device (and several ALSA capture devices), instead of everything it lists normally (output of `openal-info`):
```
    ALSA Default
    HDA Intel, ALC883 Analog (CARD=Intel,DEV=0)
    HDA Intel, ALC883 Digital (CARD=Intel,DEV=1)
    HDA ATI HDMI, HDMI 0 (CARD=HDMI,DEV=3)
    HDA ATI HDMI, HDMI 1 (CARD=HDMI,DEV=7)
    HDA ATI HDMI, HDMI 2 (CARD=HDMI,DEV=8)
    HDA ATI HDMI, HDMI 3 (CARD=HDMI,DEV=9)
    HDA ATI HDMI, HDMI 4 (CARD=HDMI,DEV=10)
    CA0106, CA0106 (CARD=CA0106,DEV=0)
    CA0106, CA0106 (CARD=CA0106,DEV=1)
    CA0106, CA0106 (CARD=CA0106,DEV=2)
    CA0106, CA0106 (CARD=CA0106,DEV=3)
```
Capture devices are unaffected.

OpenAL vendor string: OpenAL Community
OpenAL renderer string: OpenAL Soft
OpenAL version string: 1.1 ALSOFT 1.19.1

**Comment by kcat** [comment]
If JACK is available, OpenAL Soft will use that for playback. Since, as far as I know, JACK doesn't have device enumeration capabilities, it just lists a single `JACK Default` device. If JACK isn't available, it attempts to use PulseAudio. If that's also not available, it attempts to use ALSA. Since ALSA does support enumeration, it's able to list all the discovered devices.

It's been a long time since OpenAL Soft allowed using multiple backends simultaneously, which is why you'll get only a JACK device or only ALSA devices, and never both. The main reason for this is because most audio devices don't support multiple streams (you need a separate mixer, like dmix, PulseAudio, or JACK, to act as a single stream for multiple apps). Various audio APIs tend to temporarily open devices on initialization or enumeration, and the device may be held open for a moment afterward, causing problems for multiple backends trying to access the same device (temporary freezes as it waits for the device to become available, or intermittent failures to access a device if another backend recently accessed it).

Playback and capture can use separate backends (which is why you can get JACK for playback and ALSA for capture), but they can't each use multiple backends.

**Comment by numberZero** [comment]
That is, backend selection is specifically for ALSA, if I understand you correctly. That’s sad. And while I do understand the mixing problem, I think it should be up to the user to choose the backend he needs. It’s really sad if some libraries can’t enumerate devices not blocking them...

**Comment by kcat** [comment]
> That is, backend selection is specifically for ALSA, if I understand you correctly.

ALSA, PulseAudio, WASAPI, DSound, certain versions of OSS, and some others allow selecting specific devices. It's mainly just APIs that don't have an option for enumeration (like JACK) or whose enumeration capabilities are poor (like OpenSL and PortAudio) that don't.

> I think it should be up to the user to choose the backend he needs.

You can, using the `alsoft-config` utility (you can either select a specific backend you want, or change the order in which they're tested, or disable specific ones). Alternatively, edit `alsoft.conf`/`alsoft.ini` (which `alsoft-config` is simply a GUI for). Or set the `ALSOFT_DRIVERS` environment variable. Whichever is most convenient.

For selecting specific devices, that's up to the audio API being used. OpenAL Soft can't enumerate devices when the backend can't (e.g. JACK has no way to list or select specific devices, so there's nothing OpenAL Soft can do to let you see them and select one).
