### ISSUE TITLE
Invalid buffer creation 

### ISSUE THREAD

**Issue by pyaggi** [kcat/openal-soft#282]
When creating a buffer without a context (ie: creating buffers before contexts) alGenBuffers returns without assigning a buffer number and devices status is unaffected.
As the openAL standards specify buffers belong to a the device not to the context, so they can be shared between sources of different contexts.
A workaround is to create a context before, even if a new context is created later which eventually will use the buffers through it sources. 
Right know selecting a device is done (at least I'm doing it that way) by selecting a context as current, and then the buffers created belong to the device owning the context. I think that is not clean, but the standard only specifies a way to select context (maybe I missed something), so that can be a problem. If two devices are created and buffers need to be created before a context I think a function for selecting the device will need to be provided, otherwise at least one context will need to be created (as in the workaround mentioned).
If this restriction persists I think alGenBuf should trigger an error, as right know the only way I could find to detect this condition is to assign the first integer (of the pointer list) to 0 and checks if it is still 0 after alGenBuf returns and in that case trigger an error myself.

**Comment by kcat** [comment]
> When creating a buffer without a context (ie: creating buffers before contexts) alGenBuffers returns without assigning a buffer number and devices status is unaffected.
> As the openAL standards specify buffers belong to a the device not to the context, so they can be shared between sources of different contexts.

While the buffers "belong" to the device, they are created through context-specific functions and rely on access to the context state. In this case, `alGenBuffers` depends on the current context to create buffers, even though the buffers are accessible to other contexts on the same device, and any generated error is recorded in the context. In a sense, it's better to consider buffers as a shared resource. It's created with a context and put in a shared pool that certain other contexts have access to. If there's an error, it's recorded in the context state (as with all `al*` functions) where the app can query it.

> If two devices are created and buffers need to be created before a context I think a function for selecting the device will need to be provided, otherwise at least one context will need to be created (as in the workaround mentioned).

Given the way OpenAL functions work, it uses the current context to know what driver to dispatch the call to (in the case of multi-driver systems). Otherwise, the function is given an explicit device or context handle, which would be associated with its dispatch table. Having the ability to select a "current" device along with a current context would unnecessarily complicate the setup, especially since you need a context to use the buffer for anything anyway.

Ideally what I would like more is to move away from the whole idea of selecting or setting a context as current, and have objects all work using their associated parent. This would require a more thorough redesign of the API, though.

> If this restriction persists I think alGenBuf should trigger an error

It does sort of trigger an error, though it's implicit behavior due to the fact that there's no current context. If you call
```
alGenBuffers(n, ids);
err = alGetError();
```
without an active context, `alGenBuffers` can do nothing (if this was OpenGL, you could actually crash here), and `alGetError` will return `AL_INVALID_OPERATION` as there's no context to get an error from... though this unfortunately isn't true when using the router (for some reason, Creative made their router have `alGetError` return `AL_NO_ERROR` if there's no context, and some apps came to rely on this as they call `alGetError` before setting a context and will fail if it's not `AL_NO_ERROR`).

> the only way I could find to detect this condition is to assign the first integer (of the pointer list) to 0 and checks if it is still 0 after alGenBuf returns and in that case trigger an error myself.

That's unfortunately not reliable behavior (it's actually wrong behavior). According to the spec:

"When an error flag is set, results of AL operations are undefined only if AL_OUT_OF_MEMORY has occurred. In other cases, the command generating the error is ignored so that it has no effect on AL state or output buffer contents."

So if `alGenBuffers` fails, the provided buffer is supposed to be unmodified. Only in the case of out-of-memory might it be modified (or it might not be, or it might be a schrodinger modification; it's undefined results). Newer versions of OpenAL Soft have gotten better at this too, avoiding writing anything to user-provided buffers until it knows the call is successful.
