### ISSUE TITLE
Information about openal is not displayed in AIDA

### ISSUE THREAD

**Issue by shikulja** [kcat/openal-soft#283]
Information about openal is not displayed in AIDA

![Скриншот 15-04-2019 234627](https://user-images.githubusercontent.com/3386359/56164138-bc67ba80-5fd8-11e9-9e55-cde13386c84b.png)

And it seems someone is lying a little.
![Скриншот 15-04-2019 235025](https://user-images.githubusercontent.com/3386359/56164487-75c69000-5fd9-11e9-9f41-6d7b2e1977b9.png)

**Comment by kcat** [comment]
> Information about openal is not displayed in AIDA

What information is it expecting to get? How does it try to get that information?

> And it seems someone is lying a little.

The way openal-info tries to detect supported filters and effects doesn't seem to work on Creative's drivers. It tries to determine support by calling `alGetEnumValue` for the filter or effect enum, but Creative always returns false for this even with supported filter and effect enums. It instead seems to want you to try setting the filter or effect type and see if it generates an error, but that's bad practice (a properly written app shouldn't purposely provoke or expect an error).

**Comment by shikulja** [comment]
@kcat 
AIDA does not show any information, no version, not supported functions, just a blank screen.
Creative shows completely

**Comment by kcat** [comment]
Hmm, well the functions are being exported since the DLL works as a drop-in replacement for Creative's, and the router is able to pick up the functions too. Maybe AIDA isn't even trying to look at the functions if some other information is missing.

As for that missing information, I'm not sure what's going on. The prebuilt binaries are made with MinGW-w64, and CMake is told the library version:
```
SET_TARGET_PROPERTIES(${IMPL_TARGET} PROPERTIES OUTPUT_NAME ${LIBNAME}
    VERSION ${LIB_VERSION}
    SOVERSION ${LIB_MAJOR_VERSION}
)
```
and that results in the linker being supplied with:
```
-Wl,--major-image-version,1,--minor-image-version,19
```
I'm not sure what else would need to be done for the version to show up.

**Comment by kcat** [comment]
Out of curiosity, does this work now since commit 7affe3d78d5473027104cb3b3008d5afb7ac47ea? An RC file was added, maybe AIDA will pick that info up.

**Comment by shikulja** [comment]
![Скриншот 07-01-2020 093517](https://user-images.githubusercontent.com/3386359/71873757-09745980-3131-11ea-8f02-14c97e8eb232.png)
openal-soft-1.20.0
began to display normally aida ver 5.99
In the new version aida, openal mapping was not found.
