### ISSUE TITLE
Popping during alSourcePlay alSourceStop ?

### ISSUE THREAD

**Issue by SkacikPL** [kcat/openal-soft#304]
It seems this issue is tied to native OAL implementation and is present in some apple products and certain implementations (especially in IDTech games).
Not entirely sure what is going on here, whether it's some obscure OAL bug or implementation issue (tested on this code: https://github.com/NVIDIA/Q2RTX/blob/master/src/client/sound/al.c)

I'm not sure whether it's buffer related and it picks up some junk from memory in that region or what. From what i could gather only things that were proven to work somehow is either having quick fade in/fade out or hotswapping with dummy "silence" buffer.
Given development of OpenAL is pretty much dead, maybe it'd be nice to have OpenAL Soft provide some way of circumventing it.

**Comment by kcat** [comment]
Clicks and pops when starting/stopping usually happen as a result of starting/stopping on a sample that has non-0 amplitude. It generally shouldn't happen at the start or normal end of a sound if the sound is loaded correctly (e.g. it's not including the .wav file header data), unless the sound itself is authored poorly.

The current release of OpenAL Soft does/should fade in from silence if a source starts at a non-0 offset. Current master also tries to fade the sound to silence when it stops. This is imperfect since you can't fade a sound you no longer have the samples for, but it does the best it can and is better than nothing.

**Comment by SkacikPL** [comment]
> It generally shouldn't happen at the start or normal end of a sound if the sound is loaded correctly (e.g. it's not including the .wav file header data), unless the sound itself is authored poorly.

Both are generally the case here as i'm primarily testing it on Quake 2 and some sound files actually do include the pops.

Though the mention about the header data is very important as by looking at how it loads sound files to buffers i see it just does it in its entirety so it might be responsible for other half of the cases.

Thanks for the information, i'll report back after i check whether stripping header from loaded buffer solves the issue.

**Comment by SkacikPL** [comment]
Yeah it seems OpenAL / Soft are perfectly fine, the Quake 2 implementation of various source ports is a bit wonky with the way it loads .wav file in its entirety as buffer. It's just a shame because it turns out Q2 has absolutely ATROCIOUS mastering where about half of the sound is maxed out on the gain and has no lead in/out silence or fade of any sorts.

Stripping headers helps a lot, though obviously there's about half of the sounds that would require remastering to be actually useful in this particular case.
I'll drop a comparison so maybe someone in future can reference it, if they ever encounter similar issue and stumble upon this thread:
https://youtu.be/5_wTghEXdJ0

Thanks for your help.

**Comment by kcat** [comment]
> There are other places in the code which actually can cause pop, like synchronizing looping sounds (as there can be multiple instances of eg. alarm sound)
> `qalGetSourcei(ch2->srcnum, AL_SAMPLE_OFFSET, &offset);`
> `qalSourcei(ch->srcnum, AL_SAMPLE_OFFSET, offset);`

If these calls are made after `ch->srcnum` is started, yeah, seeking a source while it's playing doesn't have any click prevention (yet). BTW, it may be better to use `qalGetSourcef`/`qalSourcef` for those calls, since that better preserves the sub-sample (fractional) offset, at least with OpenAL Soft.

> Other think i've noticed is that assigning (or removing) an effect/filter from source that is currently playing also causes crackling.

Changing the effect type can, yes, since the previous effect processor is lost after whatever it last rendered. The effect slot would need some kind of virtualization, similar to how sources use voices. Though if you mean changing the effect parameters but keeping the same type, that shouldn't happen, at least with reverb.

In any case, since this particular issue has been resolved, I'll close it. If  you can provide more information for the effect/filter crackling, feel free to create a new issue about it.
