### ISSUE TITLE
The allow-move option for the pulse backend should be set to true by default

### ISSUE THREAD

**Issue by tanuk** [kcat/openal-soft#316]
As a PulseAudio maintainer, I've seen several people complain about not being able to move a stream to a different device, and the problem is always that the application is using OpenAL-soft, which by default doesn't allow its streams to be moved.

Maybe you have some very good reason to not allow moves by default, but since I don't know that reason, it seems to me that the default value for allow-move is wrong.

**Comment by kcat** [comment]
This was recently changed actually, in commit c135629eae544b0e7785803b98987c1ab1eb95ca.

As mentioned in that commit message, the reason it was like that is ultimately KDE (or really, the `module-device-manager` module created and used at the behest of KDE for its PulseAudio integration). By default on KDE, *all* streams created are forced onto the devices set in KDE's preferences, even when the app connects to a specific sink or source. So if a user tries to select a specific device with an OpenAL app instead of the default, that selection is ignored and output is moved to the default regardless. Worse, the move happens after stream initialization, after OpenAL Soft auto-configures the stream's render format to match the sink, so even if it's moved onto the device the user wants, it could be with the wrong format and cause extra resampling/remixing that increases CPU load and reduces the audio quality (e.g. a 48khz surround sound mix, matching the initial sink, to be played on a 44.1khz stereo sink KDE moves it to).

The only way to prevent that problem, to ensure the user's selected device is used and ensure a proper matching auto-configuration, is to not allow the stream to be moved. Unfortunately it's been a problem for nearly, if not more than, 10 years, so I doubt KDE cares to fix it on their end.

**Comment by tanuk** [comment]
Great to hear this is already fixed! Thanks for the quick reply and the explanation. I'll close this issue.
