### ISSUE TITLE
AL lib: (WW) UpdateDeviceParams: SSE performs best with multiple of 4 update sizes (1114)

### ISSUE THREAD

**Issue by willm127** [kcat/openal-soft#32]
Hey guys,

I'm on OS X (10.11.3), and I'm getting the error above. Any idea what this means or how it can be fixed? Thanks! Do let me know if I can help in any way.

**Comment by kcat** [comment]
That simply means output was configured to do mixes of non-multiple-of-4 sample counts. It's nothing serious, just a warning that the SSE mixer won't be as optimal as it could be (still a lot better than the non-SSE mixer, though).

For OSX, that warning is kind of bogus anyway. OpenAL Soft doesn't actually know what the mixing size is when setting up the device, and will simply mix however many samples the system asks for in the callback. Unfortunately I don't know the CoreAudio API, or have a Mac to test with, to really fix it.

**Comment by mantognini** [comment]
I don't know if the following will help at all but just in case I'll share my quick findings.

I quickly looked at OpenAL Soft code when dealing with SFML/SFML#1057 and noticed that in Alc.c, [lines 1836-1838](https://github.com/kcat/openal-soft/blob/master/Alc/ALc.c#L1836-L1838), the update size is increased to match the next multiple of 4. This statement is executed on my machine -- which is a Mac BookPro Mid 2012 with a i7-3720QM and running OS X 10.10 -- because [helpers.c:151](https://github.com/kcat/openal-soft/blob/master/Alc/helpers.c#L151) was executed. So I don't get the warning mentioned by @willm127.

**Comment by kcat** [comment]
This warning should no longer occur with commit f775f25.
