### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by manhnt9** [kcat/openal-soft#326]
I'm having this compile error when building for iOS.
```sh
Alc/backends/coreaudio.c:459:5: error: use of
      undeclared identifier 'AudioObjectPropertyAddress'
    AudioObjectPropertyAddress propertyAddress;
```
This is because`AudioObjectPropertyAddress` is only available in MacOS 10.4+ SDK and not in iOS SDK ([Source](https://developer.apple.com/documentation/coreaudio/audioobjectpropertyaddress?language=objc)).
In order to support iOS, I suggest 2 ways of patching:
- Write a new audio backend for iOS, keep current MacOS's backend implementation
- Change MacOS's implementation to use common CoreAudio API that supports both MacOS and iOS

Please review and comment, our team may be able to provide this support.

**Comment by manhnt9** [comment]
Well turns out this issue had a PR here: https://github.com/kcat/openal-soft/pull/321.
I will test to see if iOS is correctly supported.

**Comment by manhnt9** [comment]
That PR fixes compile error. But the project still not considered to have proper support for iOS due to these linker errors:
- It still links some MacOS frameworks that aren't present for iOS
- It even links some Android-only libraries (log, atomic)

That's for building, I'm not sure if OpenAL will run on iOS yet.
We'll continue and send PR soon.

**Comment by kcat** [comment]
> That PR fixes compile error. But the project still not considered to have proper support for iOS due to these linker errors:
>
> * It still links some MacOS frameworks that aren't present for iOS
> * It even links some Android-only libraries (log, atomic)

Can you paste the full output from cmake and the build? It should only link to liblog if it finds the `__android_log_print` function in it. It links to libatomic if that's found since some systems need it for atomic support. iOS shouldn't have a liblog with Android functions in it, so I don't know why it would try to link it, and if it found libatomic it should be linked because it may be needed.

As for the frameworks, I'd have to know which it's trying to use that iOS doesn't have.

**Comment by fbirot** [comment]
I have the same problems here.

I've managed to make it work by adding those lines at the begining of CMakeLists.txt

``` cmake
string(COMPARE EQUAL "${CMAKE_SYSTEM_NAME}" "iOS" TARGETS_IOS)
string(COMPARE EQUAL "${CMAKE_SYSTEM_NAME}" "Android" TARGETS_ANDROID)
```

and then added a "AND TARGETS_ANDROID" condition in the HAVE_LIBLOG IF statement, like here:

``` cmake
# Include liblog for Android logging
CHECK_LIBRARY_EXISTS(log __android_log_print "" HAVE_LIBLOG)
IF(HAVE_LIBLOG AND TARGETS_ANDROID)
    SET(EXTRA_LIBS log ${EXTRA_LIBS})
    SET(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} log) 
ENDIF()
```

and then down in the file, replaced:
``` cmake
SET(EXTRA_LIBS ${COREAUDIO_FRAMEWORK} /System/Library/Frameworks/AudioUnit.framework
   /System/Library/Frameworks/ApplicationServices.framework ${EXTRA_LIBS})
```

by

``` cmake
IF(TARGETS_IOS)
        FIND_LIBRARY(COREFOUNDATION_FRAMEWORK NAMES CoreFoundation)
        SET(EXTRA_LIBS ${COREAUDIO_FRAMEWORK} ${COREFOUNDATION_FRAMEWORK} ${EXTRA_LIBS})
ELSE()
        SET(EXTRA_LIBS ${COREAUDIO_FRAMEWORK} /System/Library/Frameworks/AudioUnit.framework
           /System/Library/Frameworks/ApplicationServices.framework ${EXTRA_LIBS})
ENDIF()
```

I'm not familiar with cmake. There is probably a better way to do it, but with those changes it  compiles correctly (I've tested it for iOS, Android and OSX).

In order for it to work properly on iOS, I've also made this change: https://github.com/kcat/openal-soft/issues/425

**Comment by jay072** [comment]
Those changes above worked for me too :) 

Any idea how to get OpenAL-soft in .framework format for iOS? I've got it compiled into a .dylib but you can't submit apps with these embedded.

**Comment by fbirot** [comment]
You should be able to modify the cmake file so that the xcode project generated creates a framework (see here for more info: https://cmake.org/cmake/help/v3.5/prop_tgt/FRAMEWORK.html).

On my side, I've prefered creating an xcode project from scratch, adding all the required c files and headers and all the dependencies in order to generate a framework, but it should work also with a modified cmake file. The Xcode project created with cmake is not as clean as it is when created manually, which is the main reason why I've created it directly.

In order for the xcode project to compile both for the iphone simulator (x86) and iphones (arm), I've also added this macro "#ifdef HAVE_NEON ... #endif" in mixer_neon.cpp to disable all mixer_neon.cpp code when compiling for the simulator (the problem was that while with cmake we can add/remove c file depending on the architecture, I don't think it is possible with xcode unless maybe by creating different targets which wouldn't be very handy)

**Comment by halx99** [comment]
Relative PR: https://github.com/kcat/openal-soft/pull/466

**Comment by halx99** [comment]
@kcat since the pr #466 merged, we can easy to build ios/osx framework bundle, so I think this issue could be closed.
