### ISSUE TITLE
Some sounds are missing when using EAX in F.E.A.R.

### ISSUE THREAD

**Issue by funkerwolf** [kcat/openal-soft#333]
Some sounds are missing when using EAX in F.E.A.R., the problem also exists when using ALchemy.
It is not very clear for what reason this happens, but it becomes very pronounced when using other localizations as Russian voice acting for the game. The problem appears when using hardware mixing in the game, which activates eax support. Perhaps the problem is that eax is not able to process .wav tracks with a high bit rate, since the fixes for this problem are trivial that just the sounds in the fix are transcoded simply to mp3 with a low bit rate, however, iterating over the whole game, also not really a solution ...

**Comment by kcat** [comment]
Since it also happens with ALchemy and when just enabling hardware mixing, it seems like a more general issue with the engine not properly handling those files with its hardware mixer. OpenAL doesn't handle MP3 directly, the game is responsible for decoding them to plain PCM samples that can be loaded.

**Comment by funkerwolf** [comment]
You were right, the problem is really in the game engine, after converting sounds to mono format everything became normal
