### ISSUE TITLE
Call to alcOpenDevice(nullptr) Never Returns

### ISSUE THREAD

**Issue by Shokwav** [kcat/openal-soft#35]
Tested on Win10, latest version of OpenAL Soft. Using the WinMM backend only. According to gdb, the hangup seems to be in threads.c, in alcall_once, at line 495, where I assume it's infinitely calling the callback?

**Comment by kcat** [comment]
Sorry for the late response.

If you're using the latest git, line 495 means it's in the callback. which is only called once due to the atomic variable's state (the first instance it'll be 0 and call the callback, asynchronous calls will see 1 while another thread is handling it and wait until it's not 1, and subsequent calls will see 2 and skip the callback since it was already called). If it's hung on line 495, that means it's hung in the callback itself, somewhere else in the code. Can you get a full backtrace?

**Comment by kcat** [comment]
The relevant code has  changed significantly over the past couple of versions and even more in the latest master. And given the lack of further information, I'm going to close this. If there's still an issue here with the latest master, please provide more details, preferably at least a full backtrace.

**Comment by ltqsoft** [comment]
Hi, sorry if my comment bothered you.
I got a workaround for this issue: do not create any static instance of AL context wrapper class. It seems happen when I try to build a DLL which has that static instance, and then build another DLL which depends on it, using static linking is OK.
