### ISSUE TITLE
Sound loss with FlightGear on macOS (no issues in other platforms)

### ISSUE THREAD

**Issue by hayden2000** [kcat/openal-soft#358]
Hello!
I have an odd issue with sounds not playing in FlightGear, though the issue is platform specific, as it only works on Windows and not macOS.
Here is the specific issue, I have provided more details about what sounds do not play here: https://github.com/legoboyvdlp/A320-family/issues/20
This is the aircraft: https://github.com/legoboyvdlp/A320-family
And this error shows up in the log file whenever a sound is triggered that doesn't play:
`[ALRT]:sound /Users/Shared/Hudson/MacRelease/simgear/simgear/sound/soundmgr_openal.cxx:868:AL Error (sound manager): Unknown Internal Error at sample play`
I wasn't sure if this is a problem with OpenAL, FlightGear, or the A320-family. I was wondering if you had any ideas what could be going on, specifically why it might work differently on Mac vs windows?

**Comment by kcat** [comment]
If I were to guess, it seems the Mac version is using Apple's OpenAL implementation. Apple's OpenAL does seem to be somewhat buggy in that it doesn't fully follow the spec and takes unnecessary liberties, in particular it's known to generate errors when it's not supposed to because of how it tries to do things internally.

It is possible to use OpenAL Soft on Mac, although it would require the app to be linked against libopenal.1.dylib instead of OpenAL.framework. It's probably possible to put OpenAL Soft's library into a framework, but I have no experience with Macs to know how to do that.
