### ISSUE TITLE
Low effect limits

### ISSUE THREAD

**Issue by SephiRok** [kcat/openal-soft#36]
I'd like to advocate for higher maximum auxiliary effect slots
`ALc.c: device->AuxiliaryEffectSlotMax = 4;`
and higher maximum auxiliary sends
`alSource.h: #define MAX_SENDS                 4`

They seem like a needlessly low hard cap. Particularly the maximum auxiliary effect slots, applying more than 4 different effects simultaneously to different sources can be useful for varying the audio experience, perhaps especially in top-down games with a lot of simultaneous action in different environments, as well as experimental games.

**Comment by kcat** [comment]
Since commit d3cc867bd42759cb8e294d691354187984f96ff4, the default auxiliary effect slot count has been raised to 64 and the maximum number of source sends is raised to 16.

Note that for the effect slots, having an effect slot generated can incur some processing cost even if nothing is feeding it, so it's best to only allocate what you need to use. The cost can be minimized by setting a null effect type on unused slots, though not having it at all when it's not used is even cheaper.

For source sends, the default you get is 2. You can use ```ALC_MAX_AUXILIARY_SENDS``` with context creation or device reset attributes to request more, up to 16 (you can try to request even more, but it'll be clamped; query ```ALC_MAX_AUXILIARY_SENDS``` using ```alcGetIntegerv``` afterward to see what you got). Having more sends does slightly increase CPU cost since it's more properties that need to be processed for each active source, but it shouldn't be too bad.

Let me know if using the higher counts causes a problem. There's not too much that stresses a high number of effects and sends, so some feedback would be appreciated.

**Comment by kcat** [comment]
Closing since the number of effect slots has been significantly increased, and the number of source sends has increased as well. Even on modern systems, I don't expect this could be increased much further without performance problems, though there's always room for more general improvements.
