### ISSUE TITLE
  Two dynamic libraries use OpenAl mutexes

### ISSUE THREAD

**Issue by hy-chao** [kcat/openal-soft#361]
Linux system;
    use Openal in two dynamic libraries to play sound,   
    the first one  play sound ok,  when call the  second dynamic library，
    the first library playback sound stopped 。
    What should I do to have two libraries play sound at the same time?

    best wish；

**Comment by kcat** [comment]
Can you clarify exactly what you're doing? Two separate libraries using OpenAL at the same time can be a problem since OpenAL works with a global current context. If one library opens a device, creates a context, then sets the context current, and another library also opens a device, creates a context, then sets the context current, the first library's context is no longer current and any OpenAL calls it makes won't behave correctly.

The two libraries would have to be made to be aware of external OpenAL callers, and not try to act independently. For instance, you could have the main application open a device, create a context, and set the context current, then the two libraries use the existing context. Or alternatively, make the library's functions aware that its context may have been unset, and reset the current context before making OpenAL calls.

**Comment by hy-chao** [comment]
I try to get the context  before use it. If the library can get  the contex of device, do not create a new one.  It's works when two libraries playback sonud.
   Thank you for your time.
