### ISSUE TITLE
Execution failure on macos

### ISSUE THREAD

**Issue by ericLemanissier** [kcat/openal-soft#364]
When running a simple program on macos using openal 1.19.1, I get this failure:
```
dyld: lazy symbol binding failed: Symbol not found: _aligned_alloc
  Referenced from: /private/tmp/c3ipr/pr_224_17_0_1/test_package/build/af116007ef59c5b4ce4db068ade3b35142ac325a/bin/test_package
  Expected in: /usr/lib/libSystem.B.dylib
```
source file of program can be found on https://github.com/conan-io/conan-center-index/pull/224/files#diff-0f5e6c46b6f2228d5b3efdc7b4397ae7 and full log on https://c3i.jfrog.io/c3i/misc/logs/pr/224/17/openal/1.19.1/0aa7be2d0914b6f3128105e305c90b9cb0cae86d/create_stdout.txt
compilation of openal had this warning:
```
/tmp/c3ipr/pr_224_17_0_1/.conan/data/openal/1.19.1/_/_/build/0aa7be2d0914b6f3128105e305c90b9cb0cae86d/source_subfolder/common/almalloc.c:31:12: warning: 'aligned_alloc' is only available on macOS 10.15 or newer [-Wunguarded-availability-new]
    return aligned_alloc(alignment, size);
           ^~~~~~~~~~~~~
/Applications/Xcode-11.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/malloc/_malloc.h:50:10: note: 'aligned_alloc' has been marked as being introduced in macOS 10.15 here, but the deployment target is macOS 10.14.0
void    *aligned_alloc(size_t __alignment, size_t __size) __result_use_check __alloc_size(2) __OSX_AVAILABLE(10.15) __IOS_AVAILABLE(13.0) __TVOS_AVAILABLE(13.0) __WATCHOS_AVAILABLE(6.0);
         ^
/tmp/c3ipr/pr_224_17_0_1/.conan/data/openal/1.19.1/_/_/build/0aa7be2d0914b6f3128105e305c90b9cb0cae86d/source_subfolder/common/almalloc.c:31:12: note: enclose 'aligned_alloc' in a __builtin_available check to silence this warning
    return aligned_alloc(alignment, size);
           ^~~~~~~~~~~~~
1 warning generated.
```
it looks related to https://github.com/kcat/openal-soft/issues/311

How can this be worked around ?

**Comment by kcat** [comment]
One way would be to disable the `aligned_alloc` check in CMakeLists.txt:
https://github.com/kcat/openal-soft/blob/v1.19/CMakeLists.txt#L549
You'll have to clear the build cache so that it knows the macro isn't set anymore.

Alternatively, change `defined(HAVE_ALIGNED_ALLOC)` to `0` in almalloc.c:
https://github.com/kcat/openal-soft/blob/v1.19/common/almalloc.c#L29
https://github.com/kcat/openal-soft/blob/v1.19/common/almalloc.c#L60

The latest mast should have this fixed, however. So you can also try using that if possible.

**Comment by ericLemanissier** [comment]
disabling the aligned_alloc check in CMakeLists.txt fixed the problem thanks!
