### ISSUE TITLE
Issue with 1.20.0 and JACK (connection error).

### ISSUE THREAD

**Issue by ImagicTheCat** [kcat/openal-soft#380]
Program output:
```
cannot read result for request type 3 from server (Connection reset by peer)
AL lib: (EE) Failed to connect output port "alsoft:channel_1" to "system:playback_1"
cannot send request type 3 to server
cannot read result for request type 3 from server (Broken pipe)
AL lib: (EE) Failed to connect output port "alsoft:channel_2" to "system:playback_2"
```
JACK output:

`timeout waiting for client alsoft to handle a buffer size change event`

I'm using Archlinux package `openal 1.20.0-1`, I have no issues when reverting to `openal 1.19.1-2`.

**Comment by kcat** [comment]
Looks like JACK is trying to send a buffer size change event while OpenAL Soft is in the middle of configuring the device. I'm not sure how this should be handled because it will then try to reset the device while it's being reset. That it doesn't happen with 1.19 is actually an oversight... the event handler doesn't use the right lock so it would be allowed to do it's work in the middle of device configuration. But that seems incredibly dangerous since two threads could end up trying to modify the same thing at the same time without some kind of lock like this.

**Comment by kcat** [comment]
Commit 6f1c853397ae7a29e064cebe4d8988f192a28946 should handle this situation better. Are you able to check?

**Comment by ImagicTheCat** [comment]
The connection is made, I see `alsoft` in JACK. But either no sound is emitted from the application or sometimes a fast looping sound (the chainsaw kind).

**Comment by kcat** [comment]
It appears JACK doesn't like the process callback being set after a call to `jack_activate`, but the ring buffer can't be allocated until then since the server can send updated properties, placing the callback and ring buffer in a race condition. I just pushed commit af08f68448b37a9c1a22f6d9721b5c2c0708c960 to handle this. Not the cleanest thing, but it works.

**Comment by ImagicTheCat** [comment]
Everything seems OK, thanks.
