### ISSUE TITLE
Dummy context without device

### ISSUE THREAD

**Issue by W4RH4WK** [kcat/openal-soft#383]
Is there a way to create a context, that is not associated with any device, yet can be used so all calls to the library succeed?

I am currently building a simple 3D game engine and want to handle the special case where no audio device is available on the system. I'd prefer to only modify the initialization in such a way that regular OpenAL function calls succeed even if there is no observable effect.

**Comment by kcat** [comment]
No, because there's functionality that depends on a device (buffers, for example, are shared between contexts on a device).

If all you want is to call OpenAL functions and don't need any observable side-effect, then you can just call the OpenAL functions and ignore any set error (at least wit OpenAL Soft, this should be safe; if you run into an issue/crash, let me know). Without a context, the calls will just return without doing anything. Of course, as a consequence that means the `alGet` functions won't return anything meaningful either.

**Comment by W4RH4WK** [comment]
Alright, thank you very much.
