### ISSUE TITLE
alSourcePlay variable latency

### ISSUE THREAD

**Issue by gotleg** [kcat/openal-soft#395]
Hello,

I'm working on a sampler/sequencer app written in Qt/c++ using OpenAL as audio backend.
I'm facing a problem about latency/time precision and it looks like the problem should be on the OpenAL side.

My app runs a separated high priority thread to generate ticks event with high precision using std::chrono::high_resolution_clock / std::chrono::steady_clock (tried both)

Measuring time interval between ticks from this thread give me rock solid intervals with no variation.

Measuring time interval between ticks after event has been passed to the method calling alSourcePlay gives me very small interval variation.

ex : max 200 microseconds (0.2 ms) for a 20 000 microseconds (20ms) time interval

**The problem is that I can clearly hear that sound play is not regular but tick variation is way too low to explain that**

I saw ALC_REFRESH param from the doc, it is set to 43 by default on my system.
So i assume that my context is refreshed 43 times/second giving a latency variation between 0 and 23.25ms 

Is that correct ?

I tried to increased ALC_REFRESH like this :

ALCint contextParams[] = {
    ALC_FREQUENCY, ALCint(44100),
    ALC_MONO_SOURCES, ALCint(255),
    ALC_REFRESH, ALCint(100),
    ALC_STEREO_SOURCES, ALCint(1),
    ALC_SYNC, AL_FALSE
};

m_context = alcCreateContext(m_device, contextParams);
alcMakeContextCurrent(m_context);

But it doesn't seem to work as when I check params after setting context I still get ALC_REFRESH = 43.

Here are my questions :

- Do you think variation can be caused be this relatively low ALC_REFRESH ?
- Do I need a specific version of OpenAL to be able to set ALC_REFRESH ?
- About ALC_SYNC, I don't really get whether I should use a synced context or not in my use case.

Many thanks for your help.

**Comment by kcat** [comment]
> *The problem is that I can clearly hear that sound play is not regular but tick variation is way too low to explain that*
>
> I saw ALC_REFRESH param from the doc, it is set to 43 by default on my system.
So i assume that my context is refreshed 43 times/second giving a latency variation between 0 and 23.25ms
>
> Is that correct ?

As far as OpenAL Soft is concerned, the `ALC_REFRESH` property is essentially the device update period. By default, it will try to get a 20ms update period (ALC_REFRESH of 50), though it's not unusual that a device may require a slightly higher period (around 23ms is not unusual there). Note however that it's the minimum update; depending on circumstances, it could render multiple periods at once or with some backends even one plus some fraction of a period (e.g. a 960-frame period could render or 1200 or 1920 frames, depending on how many samples the device can actually take at the time the audio update triggers).

> I tried to increased ALC_REFRESH like this :
>
> ALCint contextParams[] = {
> ALC_FREQUENCY, ALCint(44100),
> ALC_MONO_SOURCES, ALCint(255),
> ALC_REFRESH, ALCint(100),
> ALC_STEREO_SOURCES, ALCint(1),
> ALC_SYNC, AL_FALSE
> };

The list needs to end with a `0` property, since `alcCreateContext` doesn't know how many property:value pairs are specified.

> Do you think variation can be caused be this relatively low ALC_REFRESH ?

If I'm understanding the issue, I don't think it's that, exactly. `alSourcePlay` is a bit of a complicated function since it needs to atomically enable mixing for the source (or source*s* with `alSourcePlayv`), with behavior dependent on the current mixing state. This essentially means it needs to use a mutex to protect access to resources shared with the mixer, which could be running asynchronously at the same time as the call. That could throw off timing between ticks on your thread. There is some good news there, in that the latest Git master manages to avoid that mutex, though it may still busy-wait/yield if it happens to get called while the mixer is running.

Or if you mean timing in the resulting mix itself, the update period/ALC_REFRESH determines how often samples are mixed for the device. A sound won't actually start mixing when you call `alSourcePlay`, but it gets marked as playing so it will start with the next mixer update. That will throw off the timing if you want to play a beat with high accuracy. Dealing with this won't be too easy; you can of course just brute-force it with a lower period/higher refresh, though that will create a higher burden on the CPU and OS's scheduler, and can still be subject to some mistiming. Alternatively, you can use a loopback device which lets you control exactly when a mix happens and how many samples get mixed, although then it's your responsibility to play the mixed samples in some way since they're given to you instead of a playback device (keeping in mind timer drift; the audio clock and system clock won't be perfectly synchronized).

> Do I need a specific version of OpenAL to be able to set ALC_REFRESH?

Currently, the refresh can't be controlled by the app. With OpenAL Soft the period size has to be set by the config file or `alsoft-config`, but even then it will be limited by what the hardware or OS can actually do (e.g. WASAPI has a strict 10ms period size, which OpenAL Soft can use multiples of, whereas ALSA and direct hardware may be limited to a specific set of period sizes depending on the sample rate and total buffer size).

> About ALC_SYNC, I don't really get whether I should use a synced context or not in my use case.

I'm not sure any current OpenAL implementation does anything with ALC_SYNC. It's not terribly clear how exactly it's supposed to work.

**Comment by gotleg** [comment]
Many thanks taking time giving your help.
Yes the problem is beeing able to play a beat at constant intervals :)

As you told me, ALC_REFRESH doesn't appears to be a solution, I tried changing update period from alsoft-config (just for fun) but my hardware doesn't handle.

I'll give a try to building the latest sources to check if I got natively better results without the mutex thing.

If not, then I think I'll have to check for the loopback device :+1:

**Comment by george-tsiros** [comment]
> > About ALC_SYNC, I don't really get whether I should use a synced context or not in my use case.
> 
> I'm not sure any current OpenAL implementation does anything with ALC_SYNC. It's not terribly clear how exactly it's supposed to work.

I've spent the past hour or so searching the web, skimming through all the issues that contain the string "sync". 

the openal 1.1 spec pdf mentions `ALC_SYNC` once on page 50 and that's it. From what i see, this attribute is completely undocumented. 

My question is (and i am sure i'll need my asbestos underwear for this) since there is no understanding of it, why are you including code that handles it in here? Honest question. 

Also, kindly add a comment in there somewhere that it is *known* that this attribute is unused/undocumented/of unknown purpose/useless.

**Comment by gotleg** [comment]
After more digging, it appears to me that openAL was not the best option for my purpose and I finally changed audio backend to native Qt (QAudioOutput, ...)
So I'll close this issue.
Many thanks again for your help and for all the great work on openAL that I use on other projects :)

**Comment by kcat** [comment]
> My question is (and i am sure i'll need my asbestos underwear for this) since there is no understanding of it, why are you including code that handles it in here? Honest question.

If you mean for OpenAL Soft, it's because `ALC_SYNC` is a spec-defined attribute so it has to be recognized. Though without a clear definition of what a "synchronous context" is, the implementation has no choice but to define it for itself. OpenAL Soft always returns false under the presumption that a "synchronous context" means audio mixes and/or state updates occur synchronously, which isn't ever true for a playback device.

For `alcCreateContext`'s attribute list, `ALC_SYNC` isn't explicitly handled and doesn't need to be. Any unknown attribute is ignored (same as if it was known but not honorable), so it's merely traced/logged and skipped over.
