### ISSUE TITLE
Problems with SDL redeclarations

### ISSUE THREAD

**Issue by Chreschtf** [kcat/openal-soft#397]
Hello. I was trying to build the sources and everything worked out fine until I had to install SDL+SDL sound in order to run one of the examples. since then I can't build them anymore because there are some redeclarations?
Here is the output of cmake
[cmakeoutput.txt](https://github.com/kcat/openal-soft/files/4333201/cmakeoutput.txt)
and here of checkinstall (simple make is the same output)
[openal-checkinstall.txt](https://github.com/kcat/openal-soft/files/4333203/openal-checkinstall.txt)
before I had SDL installed I was able to run the alrecord example, but not the alstream one as it uses SDL headers.
Any ideas why those problems arise?
fwiw I'm on ubuntu 18.04

**Comment by kcat** [comment]
I looks like SDL_sound's headers are installed in `/usr/include/SDL`, so when it includes `SDL.h`, it grabs SDL 1's headers, whereas when the examples include `SDL_audio.h`, it gets SDL 2's headers in `/usr/include/SDL2`, causing a conflict.

The examples need SDL 2 (except for alrecord which doesn't need anything extra). A few also need SDL_sound, however SDL_sound needs to be built against SDL 2 instead of SDL 1 for that to work correctly. I don't know if Ubuntu has a version of SDL_sound built against SDL 2, but if not, you can uninstall the SDL 1 and SDL_sound dev packages, and build SDL_sound manually against SDL 2.

Alternatively, if you don't actually need the examples, you can pass `-DALSOFT_EXAMPLES=FALSE` to the cmake command line to disable building them.

**Comment by kcat** [comment]
I just changed the examples to use libsndfile instead of SDL_sound, so they should no longer try to pull in SDL 1 and SDL 2 at the same time.
