### ISSUE TITLE
Question: change config programmatically

### ISSUE THREAD

**Issue by stgatilov** [kcat/openal-soft#403]
The alsoft.ini file allows to configure a lot of things in OpenAL-Soft. However, it seems to be user-provided configuration by design, so the application should not mess with it.

**Is there any way to programmatically change parameters from config file?**

---

**Background:** Recently we have switched TheDarkMod (based on Doom 3 engine) to OpenAL-Soft, with EFX and HRTF enabled. However, right now we distribute hardcoded alsoft.ini file along with game. It has two non-default parameters:

1. **HRTF = true**. This was necessary, because otherwise headphones were not detected as headphones, so HRTF was always disabled. Without doing so, most of players would never know about HRTF at all. However, this is a major nuisance for people with 5.1 sound, since they have to disable it in the file. Once again, most of them don't know about it, so they have to live with HRTF enabled on their 5.1 setup.
2. **cf_level = 2**. This was added before HRTF was integrated, due to complaints from players with ordinary stereo speakers. The original Doom 3 software mixing was much softer in this regard, while with default OpenAL-Soft config turning 45 degrees to the side results in no sound from opposite speaker.

Luckily, we can add an explicit option to the in-game menu, which would enable/disable HRTF, thanks to [ALC_SOFT_HRTF extension](https://kcat.strangesoft.net/openal-extensions/SOFT_HRTF.txt). It would be great to have "auto" setting too, but it would make sense only if either 1) headphones are detected more reliably, or 2) user could specify explicitly using the in-game menu that he has headphones. Point 2 can be done in config file with **stereo-mode = headphones**, but once again: can it be set programmatically?

The **cf_level** setting is much worse. I have searched through source code, and it seems that config file is the only way to influence this.

**Comment by kcat** [comment]
> **Is there any way to programmatically change parameters from config file?**

In some cases, there are either standard methods or extensions to handle what the config file can. For instance, the standard `ALC_FREQUENCY` context creation attribute can alter the playback sample rate like the `frequency` config option, while the `ALC_SOFT_HRTF` extension can set HRTF like the `hrtf` config option. There are others, and I'm always open to consider additional options/extensions for per-application control.

>     2. **cf_level = 2**. This was added before HRTF was integrated, due to complaints from players with ordinary stereo speakers. The original Doom 3 software mixing was much softer in this regard, while with default OpenAL-Soft config turning 45 degrees to the side results in no sound from opposite speaker.

The `cf_level` option is actually for headphones, not ordinary speakers. It's a really basic binaural filter (it takes a plain stereo mix and adds some crossfeed to the channels), unlike HRTF which is more accurate (it uses position-dependent filters applied to each sound). Having sounds panned hard left or right on headphones doesn't sound very good, and extended listening to non-binaural sounds on headphones can cause listening fatigue, so it was a good/cheap option early on. For ordinary speakers, you generally don't want to add a crossfeed since it happens naturally, which in turn makes hard panning less of an issue.

I've actually been considering removing that option/filter since it's essentially superseded by HRTF, it's only ever used in particular circumstances (headphones are detected and HRTF fails to enable, or the user specifically requested it instead of HRTF), and at least some sound systems have their own option for it. I just haven't because it's not that much code and it isn't really bothering anything, and there may be a couple people who prefer it. It's best to consider it a legacy thing that's just barely being kept around.

> Luckily, we can add an explicit option to the in-game menu, which would enable/disable HRTF, thanks to [ALC_SOFT_HRTF extension](https://kcat.strangesoft.net/openal-extensions/SOFT_HRTF.txt). It would be great to have "auto" setting too, but it would make sense only if either 1) headphones are detected more reliably, or 2) user could specify explicitly using the in-game menu that he has headphones. Point 2 can be done in config file with **stereo-mode = headphones**, but once again: can it be set programmatically?

ALC_SOFT_HRTF actually has an auto setting (`ALC_DONT_CARE_SOFT`), and is the default behavior if left unspecified and the config file doesn't set it. Unfortunately, not all sound systems are capable of reporting headphones, although WASAPI and PulseAudio should as long as the device is configured correctly with the system. ALSA and CoreAudio are the only other semi-significant backends that I wish could (and might be able to; I should look into it again).

An app option to set `stereo-mode` seems a little redundant, since if you know the device is headphones, you can just enable HRTF directly. If a user has headphones, and the system isn't reporting it correctly, they could just turn on HRTF in the options if they want it.

**Comment by stgatilov** [comment]
I found the original complaint about crossfeed ([link](https://forums.thedarkmod.com/index.php?/topic/19727-minimum-volume-cap-for-directional-sounds/)), and it was indeed about headphones. Although [someone said](https://forums.thedarkmod.com/index.php?/topic/19727-minimum-volume-cap-for-directional-sounds/&do=findComment&comment=430311) speakers would benefit from it too. I tested the game with cf_level = 0 on speakers, and I think it is OK.

I use front panel to plug headphones. I tried to see where I can mark it as headphones in Windows 10, and did not find anything. Somehow, the Realtek HD control panel understands that it is headphones when I plug them in, but nothing in Windows knows about it. Maybe Realtek considers everything plugged into front panel to be headphones by default. Anyway, it is obviously not the problem of the library.

I think I will end up with adding in-game option to enable/disable HRTF, and drop cf_level setting, which would allow to get rid of distributed config file.

Speaking of the original topic about configuration. I considered doing direct calls to internal functions of OpenAL-Soft. With GPL license, we have a luxury of linking everything statically. However, it turned out that all functions and variables that could be tweaked are marked "static" =)

Aside from the cf_level, I cannot name any setting in config file which application should be able to change. Maybe something like hrtf-paths or output-limiter. Just strange that there are so many things which cannot be accessed programmatically, even if they are not exposed into public interface (i.e. extension or specs).

Anyway, I think my current problem is solved.
