### ISSUE TITLE
Do soft_oal.dll and OpenAl32.dll do the same function?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [kcat/openal-soft#422]
Hi,

I'm looking for OpenAL files in the archive.
https://www.openal-soft.org/openal-binaries/

There is no file named **OpenAl32.dll** inside the files here.
But there is a file named **soft_oal.dll**.

Things get more involved. There are **openal32.dll.a, openal32.def openal32.lib** files in the libs folder in the zip archive. [1]
But there is no DLL compiled by this name.

In the project, I saw the file openal-info32.exe as an example.
When I click on this file I get the error **"OpenAl32.dll not found"**.

I copy the soft_oal.dll inside the bin folder to the location of openal-info32.exe. And **I change its name to openal32.dll**.
When I click on the file again, it shows information about my system successfully.
For example, realtek's sound card, etc.
I think it works successfully but I'm not sure.

In this case, why is the name of OpenAl32.dll in the bin folder soft_oal.dll? [2]
Another question is why does OpenAl32.dll requests .exe files.
If the dll file needed is soft_oal.dll, it should look for the correct file.

It is very clear that the project in this repo has problems for Windows.
For example, the issue of current Issues is about compiling windows Windows, visual studio,  or dll questions.
The odd official site also seems to have a problem with the files in the download links.
I don't want to compile OpenAL. I just want to configure and use it successfully.
But when I see that there is a problem with the official source, I remember that the source that other people refer to is the official site.

You're welcome. Please fix problems with Windows?
If these are not issues, then what do we have to do to use OpenAL on Windows? A short document describing this would be great.

[1]: In order to call a DLL function in Windows, we need the .lib file. Compilers read the functions of the DLL from the .lib file.
But here there is no lib file of soft_oal.dll.
There is openal32.lib. But it has no dll.

[2]: When all these problems are combined, OpenAL becomes very complicated for Windows users. It remains in an unusable state.
Issues such as dependency management, DLL queries in Windows are difficult enough. I think it has been made more difficult.

I would be very happy if you find solutions to these problems.

Thanks.

**Comment by kcat** [comment]
The readme.txt in the binary package explains it. OpenAL32.dll is the DLL that applications link to, which is why there's libOpenAL32.dll.a (for MinGW) and OpenAL32.lib/def (for MSVC). However, on a typical system, this DLL is installed by the oalinst.exe. It's a router that manages other OpenAL "drivers"; it doesn't implement the OpenAL specification itself, but it forwards API calls to drivers that do. OpenAL Soft is one such driver, and placing soft_oal.dll with the router will allow it to be recognized.

As an alternative, soft_oal.dll can be renamed to OpenAL32.dll, which will allow it to be used directly by applications without any router.

I would agree it's not a particularly user-friendly setup, since the user has to manually move around and potentially rename files. However, since I'm not primarily a Windows developer, I don't know the best practices for providing this stuff that makes it easy to use. I can look into providing CPack-generated packages, though from a cursory look, it doesn't appear like it can include 32-bit and 64-bit builds in a single package.

**Comment by SeanTolstoyevski** [comment]
Can OpenAl32.lib help call soft_oal.dll?

Because there is no openal32.dll in zip.
In this case, I have to use the other lib with soft_oal.dll.

What do you think about this subject, @kcat ?

**Comment by SeanTolstoyevski** [comment]
The subject of this dll is a nightmare.

I am trying to use DLLs that I found from other applications.
If I can handle everything with soft_oal.dll, I will leave other issues.
This answer is important to me.

**Comment by kcat** [comment]
As the readme and I said, either use oalinst.exe (from openal.org) to install the OpenAL32.dll router, which will allow OpenAL applications to see soft_oal.dll, or rename soft_oal.dll to OpenAL32.dll if you want to use it directly. Is there an issue you're running into with this?

**Comment by SeanTolstoyevski** [comment]
@kcat ,

What I want to ask is can I use the openal32.lib file for soft_oal.dll?

**Comment by kcat** [comment]
> What I want to ask is can I use the openal32.lib file for soft_oal.dll?

Yes, just rename soft_oal.dll to OpenAL32.dll.
