### ISSUE TITLE
/proc/cpuinfo reading to check NEON support is incompatible with iOS

### ISSUE THREAD

**Issue by fbirot** [kcat/openal-soft#425]
Hello,

In alc/cpu_caps.cpp if the macro HAVE_NEON is set, there is some code that reads the file /proc/cpuinfo to check at runtime that the cpu supports NEON. Yet it is not possible to check cpu features this way on iOS. This means that when compiled for iOS, even though all iphones starting from the iPhone 3GS support NEON, the CPU_CAP_NEON flag is not added to the caps variable.

https://github.com/kcat/openal-soft/blob/f5bf7dc76eb6d5924893d8cfacc01f14a20be141/alc/cpu_caps.cpp#L104-L136

In order to fix it (but it is maybe not the best way), I've added this at the begining of the file:

```c++
#ifdef __APPLE__
#include <TargetConditionals.h>
#endif
```
and then added:

```c++
#ifdef HAVE_NEON
    
#ifdef TARGET_OS_IPHONE
    caps |= CPU_CAP_NEON;
#else
    al::ifstream file{"/proc/cpuinfo"};
    // Rest of the code that checks NEON support reading the /proc/cpuinfo file
#endif
```

Do you think that a fix could be done in the repository ?

Thank you

**Comment by kcat** [comment]
With commit c75c96ce2d2f3801c8e28462d529fe999d12db8f, Neon support is assumed if it's enabled at compile time (if `__ARM_NEON` is set by default) and it will avoid checking `/proc/cpuinfo` in that case. Presuming iPhone 3GS and later targets enable Neon by default, it should have the same effect.

**Comment by fbirot** [comment]
Great thank you for the change. Yet is there any reason to keep the runtime check in the #else condition or could we assume that NEON is available if compiled for ARM (__ARM_NEON set) and not if compiled for a different architecture ?

**Comment by kcat** [comment]
The idea is that the library as a whole can be built without assuming NEON support, so it can run on non-NEON-capable processors, but if that same binary happens to be run on a processor with NEON support, certain methods can take advantage of it for better performance. If it assumed no support if it's not available when compiling, then NEON support would just be a compile-time option.

Not having a runtime check would only make sense if either it's problematic to have NEON and non-NEON code run side-by-side, or if it was very unlikely for code built to work without NEON support to be run on a device with NEON support. Otherwise, you can already completely disable NEON support by setting `ALSOFT_CPUEXT_NEON` to `FALSE` with cmake (in which case it won't ever try), or it can be globally enabled by setting a CPU target that guarantees NEON support (in which case it won't bother checking).
