### ISSUE TITLE
How reliable is this compared to default OpenAL?

### ISSUE THREAD

**Issue by Leadwerks** [kcat/openal-soft#430]
I am interested in eliminating the need for the OpenAL installer. Is this a reliable drop-in for default OpenAL, on Windows, Mac, and Linux? Are there any outstanding issues I should be aware of before proceeding?

**Comment by kcat** [comment]
More or less, yes, as long as you don't depend on erroneous or buggy behavior in the Windows or Mac implementations (Linux uses OpenAL Soft by default already). Things like `alGetError` returning `AL_NO_ERROR` without a current context set, for example, or assuming playback stops when the current context is changed. OpenAL Soft returns an error in the former case, and doesn't stop with the latter.

On Mac, the main difference is OpenAL Soft builds as a dylib rather than a framework, which may make it a bit difficult to replace for existing apps using Apple's OpenAL. But it's otherwise just as usable when building an app with it.

If you have any trouble, feel free to ask about it and I can try to help.

**Comment by Leadwerks** [comment]
It sounds like it's really only needed for Windows then, since OpenAL is guaranteed to be installed on Mac? Is there any reason to incorporate this on Linux, over the way I am already doing it?

**Comment by kcat** [comment]
For Mac, OpenAL Soft has features that aren't available on the default implementation, like EFX (for reverb and other effects), HRTF, resampler options, and more. It provides consistent behavior and capabilities across all OSs, so you don't generally have to worry about a function being buggy on one particular target if it works on the others, or missing a feature on one target that's available on the others.

As for Linux, it depends on what features you may want to use. If you want to use features added in the newest versions, it may not be a bad idea to bundle a shared lib for Linux to ensure it has the features you want. It can also be useful if you don't have a way to ensure the user has the OpenAL package installed already. Otherwise, if you don't need the newest versions (you either don't use newer features, or will just use them when available but don't require them), using the default system-installed version is fine.

**Comment by Leadwerks** [comment]
Sounds good, thanks.
