### ISSUE TITLE
Error when using delayed DLL load option in Visual Studio

### ISSUE THREAD

**Issue by Leadwerks** [kcat/openal-soft#444]
The delayed load option in Visual Studio allows you to create an executable that only loads a linked DLL when it is needed. This is nice because we can use our game engine to build small utility applications without requiring a bunch of DLLs be included with it.

The openal-soft library, however, causes an error when this feature is used.

To enable this add this option to the project linker command line options in the Visual Studio project that includes the library:
```/delayload:OpenAL32.dll```

You also need to add "delayimp.lib" to the additional dependencies in the **Linker > Input** settings.

This is what happens the first time an OpenAL function is used:

![Image1](https://user-images.githubusercontent.com/108503/85118814-813ec800-b229-11ea-8f1d-1b2aa0a2408e.jpg)

**Comment by Leadwerks** [comment]
Here is some additional information about delay loading DLLs:
https://docs.microsoft.com/en-us/cpp/build/reference/constraints-of-delay-loading-dlls?view=vs-2019

**Comment by kcat** [comment]
Which version of OpenAL Soft is this with? Is it prebuilt, or did you build it yourself? Are you using the router, or OpenAL Soft directly?

> Here is some additional information about delay loading DLLs:
> https://docs.microsoft.com/en-us/cpp/build/reference/constraints-of-delay-loading-dlls?view=vs-2019

Hmm, this sounds like it might be a problem: "Other cases include static TLS (thread local storage), declared using __declspec(thread), which is not handled when the DLL is loaded via LoadLibrary." I'm not sure exactly what it means by that, though I don't think that's the problem here anyway since TLS is only used with the thread-local context extension (unless using OpenAL Soft's router).

**Comment by Leadwerks** [comment]
I built it myself from the Visual Studio project located in the /build folder. I don't know what the router is or whether I am using that.

**Comment by kcat** [comment]
Try to make a debug build of OpenAL Soft, that should allow you to get a backtrace to where it crashes.

**Comment by Leadwerks** [comment]
Found it. Line 322 of "bsinc_tabls.cpp":
```c++
/* FIXME: These can't be constexpr due to the calls reaching the compiler's
 * step limit.
 */
alignas(16) const auto bsinc12_table = GenerateBSincCoeffs<bsinc12_hdr.total_size>(bsinc12_hdr);
alignas(16) const auto bsinc24_table = GenerateBSincCoeffs<bsinc24_hdr.total_size>(bsinc24_hdr);
```

**Comment by nkari82** [comment]
I had this problem too, and modifying the source with constexpr worked perfectly.

**Comment by kcat** [comment]
My first thought is maybe the callstack is too deep by the time you call an OpenAL function, so the initialization routines cause it to use more stack space than is available. If you can, try to avoid nesting too many calls before calling the first OpenAL function (subsequent OpenAL calls should be fine, since they don't need to be initialize the library again).

I don't know the root cause of this issue, though. I don't see what would be causing it to use so much stack at the points mentioned, since the function uses the heap to build the tables which is then written to global memory space on return.

**Comment by Leadwerks** [comment]
> I had this problem too, and modifying the source with constexpr worked perfectly.

Maybe you could explain that instead of giving an extremely vague description??

**Comment by Leadwerks** [comment]
Does anyone have a bit of code that just called LoadLibrary and retrieves all the function pointers with GetProcAddress? I have no idea why we fuck around with static libraries at all when there is a DLL that can be *dynamically* linked.

**Comment by Leadwerks** [comment]
I spent a couple hours making an OpenAL header that does not use the static lib. If I call LoadLibrary() to load the DLL the exact same thing happens.

**Comment by Leadwerks** [comment]
The reason the stack is so deep is because this is being called the first time a sound is loaded, from a command inside a Lua script, which causes initialization of the sound system.

My solution to this is to check if the DLL is present in another initialization function that is always called before sound is initialized, and if it is present then make a meaningless call like this:
```c++
alcIsExtensionPresent(NULL, "");
```
This triggers DLL loading early on and avoids the problem, although I still think the manner in which this memory is initialized in the library is questionable.

**Comment by kcat** [comment]
I'm not sure what you mean by "making an OpenAL header that does not use the static lib." OpenAL headers assume a dynamic lib by default, what did you change?

> This triggers DLL loading early on and avoids the problem, although I still think the manner in which this memory is initialized in the library is questionable.

How do you mean? Aside from returning a relatively large array, which shouldn't be a problem since it doesn't exist on the stack, it looks like a normal way to do that kind of thing.

**Comment by madebr** [comment]
Does increasing the stack size make the problem go away?
see https://docs.microsoft.com/en-us/cpp/build/reference/f-set-stack-size?view=vs-2019

If it does, you have a few options:
1. restructure the program in order to not meet this limit
2. use fibers: read these blog posts: https://devblogs.microsoft.com/oldnewthing/20200601-00/?p=103815 (June 1, 2020 - Juni 12, 2020)
3. (other options)

**Comment by Leadwerks** [comment]
@kcat I mean just calling LoadLibrary() and GetprocAddress() instead of having a .lib and a .dll.

@madebr I don't plan on spending more time on this but I think it's safe to assume that increasing the stack size would fix this. See my solution above.

Initializing a large chunk of memory on the stack strikes me as fundamentally wrong. But in any case, my problem is solved.
