### ISSUE TITLE
openal same version have different  result ?

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#456]
hello  .Not long ago，I had ask you a question about 
AL:LIB<EE>ALCdsoundCapture_open:DEVICE init failed :0x88780078? #374

when I test the 1.20 win32 ,it is ok (insert mic microphone jack  ，start record . then, pull out mic from jack, **it can still run** ,recording "0",no longer occur 0x88780078 error; and after a moment   insert mic again, it can still recording voice .    )
but the same version 1.20 ,the win 64 still have the error----AL:LIB<EE>ALCdsoundCapture__availablesamples update failed 0x88780078?  when I pull out the mic at recording. and when I insert it again, win64 can not re-recording.

can you tell me which version updata this error in win 64?

**Comment by kcat** [comment]
It seems like it's still using the old version with win64. With 1.20, it shouldn't produce error messages with `ALCdsoundCapture_` anymore, so if you're seeing them, it's using an older version.

Also, the difference in behavior would likely be because the DSound backend is more strict with unplugged devices, whereas newer versions should use the WASAPI backend instead (at least on Windows Vista and newer).

**Comment by xuandu** [comment]
I am sorry  ;the errror reason is that I have another openal (<1.20version) in this demo.exe,the demo runing use older openal.,not use the 1.20;and the openal1.20 win32, win64 are wright.so......sorry
