### ISSUE TITLE
Distorted audio when recording stack is initialized

### ISSUE THREAD

**Issue by magnus-gross** [kcat/openal-soft#457]
How to reproduce:

- Have an USB audio interface connected on Linux
- Have any Alsa or Pulseaudio program playing back music with a non-default playback rate (in my case 48000 is default, and Spotify plays back at 44100 Hz, which my USB audio interface supports as well so it plays back fine)
- Initialize the recording stack of OpenAL (see example down below)
- Now the playback of audio is distorted

Minimal reproducable OpenAL program:
```C
#include <AL/alc.h>

int main(int argc, char **argv)
{
	alcGetString(0, ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER);
	return 0;
}
```

Attached is the same program, compile with `gcc -l openal distorted_audio.c` and run it to cause the distorted audio.
[distorted_audio.zip](https://github.com/kcat/openal-soft/files/4978553/distorted_audio.zip)

I suspect that maybe OpenAL tries to open the recording device at 48000 Hz, while the same USB device is playing back at 44100 Hz, which would maybe cause issues?

This may however just be an Alsa bug and not a bug in this library, perhaps you can elaborate on what the initialization code may be doing and whether it could clash with any existing playback with different sample rates.

This originated from this issue: https://github.com/telegramdesktop/tdesktop/issues/1548
Telegram is basically executing the above code in its initialization routine.

But I can reproduce this bug with pure Alsa commands too, so I have already made a kernel bug report: https://bugzilla.kernel.org/show_bug.cgi?id=207617

Perhaps you know more about this matter? Should it even cause any problems from the Audio interface point of view, if you playback and record with different sample rates simultaneously?

**Comment by kcat** [comment]
OpenAL Soft doesn't initialize recording devices when enumerating them. It does open the reported cards and gets the available outputs and their names, which may be enough to cause ALSA to do whatever is causing it to bug out, though. I don't see anything wrong on OpenAL Soft's side, and since you can reproduce the problem with pure ALSA suggests the problem is there. Beyond that, I unfortunately can't offer any insight. I don't know whether it's common for hardware to support different rates for input and output, though I do know ALSA comes with resampling plugins to allow for different rates that the hardware may not otherwise be able to use.

**Comment by magnus-gross** [comment]
OK, thanks for your insight!
I will close this issue here then, as it's clearly a bug in ALSA then.

**Comment by ilya-fedin** [comment]
> OpenAL Soft doesn't initialize recording devices when enumerating them.

I see that this is not true for pulseaudio at least: https://github.com/kcat/openal-soft/blob/ec7e7c917403aba97aaa4ac990a863a0aca99b3e/alc/backends/pulseaudio.cpp#L604-L686

OpenAL opens devices with fixes sample rate at 44100 and some other properties on probing.

**Comment by kcat** [comment]
> I see that this is not true for pulseaudio at least:
> ...
> OpenAL opens devices with fixed sample rate at 44100 and some other properties on probing. Looks like this is enough to break entire playback functionality on systems with pro-audio cards with fixed clock.

For PulseAudio, yeah it has to connect a stream so OpenAL Soft can discover which device it gets when opening the default, so it knows which device is the default one that would open when no device name is given (since there isn't an API call to otherwise reliably get this info). However, it does use the flags `FIX_FORMAT | FIX_RATE | FIX_CHANNELS`, so the requested format should get overwritten with whatever the device is using and not affect the hardware mode. It also supplies `START_CORKED` so the stream won't actually start running, then is closed immediately after getting its display name without running.

**Comment by ilya-fedin** [comment]
Oh, thanks for clarification...

**Comment by ilya-fedin** [comment]
> For PulseAudio, yeah it has to connect a stream so OpenAL Soft can discover which device it gets when opening the default, so it knows which device is the default one that would open when no device name is given (since there isn't an API call to otherwise reliably get this info)

Why does it need pa_context_get_source_info_by_name though? I checked what gstreamer does and looks like it doesn't use it: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/blob/master/ext/pulse/pulsedeviceprovider.c#L414-482

Also, isn't it uses nullptr for the pa_stream_new name parameter for default device?

**Comment by ilya-fedin** [comment]
You can pass nullptr to pa_context_get_source_info_by_name as well: https://github.com/xbmc/xbmc/blob/19.0b1-Matrix/xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp#L795

**Comment by kcat** [comment]
> Why does it need pa_context_get_source_info_by_name though? I checked what gstreamer does and looks like it doesn't use it: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/blob/master/ext/pulse/pulsedeviceprovider.c#L414-482

That's just getting a list of available devices. OpenAL also needs to be able to report which of the available devices is the default device (that is, which one you'd expect to get by calling `alcOpenDevice(NULL)` or `alcCaptureOpenDevice(NULL, ...)`).

> Also, isn't it uses nullptr for the pa_stream_new name parameter for default device?

When an app passes NULL as a device name to OpenAL Soft, that's passed along to `pa_stream_connect_record`/`playback` as NULL for the device name. So the device you get by passing NULL to PulseAudio should be reflected as the default device with OpenAL.

> You can pass nullptr to pa_context_get_sink/source_info_by_name as well: https://github.com/xbmc/xbmc/blob/19.0b1-Matrix/xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp#L795

Hmm, I wonder if it gets the same device as you'd get by passing NULL to `pa_stream_connect_record`/`playback`, and if that's guaranteed behavior. The docs don't mention NULL is a legal value, so I don't know if it would be the same behavior or if there may be subtle but important differences.

The really annoying thing with PulseAudio is that there is no concept of a default device like you'd normally think. A device can be marked as a fallback device that's used when nothing specific is requested, but various modules and plugins can change how device selection works; e.g. the stream restore module tracks the last device an app stream was moved to, so when that same app requests the NULL device later on, it substitutes that last known device instead of using the fallback. Other modules may also have various effects on the stream, which the app can't really do anything about. There's also that module to integrate PulseAudio into KDE, which among other things forces streams to specific devices based on the stream's set role and as determined by KDE's device role configuration (this is even more egregious because it changes the device after the stream already connected to one, and even if the stream named a specific device to use at the user's behest, so the app sees one device upon connecting the stream, potentially making some decisions based on what it sees, only for it to get moved afterward to something the user didn't ask for and where those decisions may no longer be optimal).

It's all quite a mess, with everyone wanting to do their own thing and no one seeming to care about ensuring a good smooth user experience.

**Comment by ilya-fedin** [comment]
> Hmm, I wonder if it gets the same device as you'd get by passing NULL to `pa_stream_connect_record`/`playback`, and if that's guaranteed behavior.

At least looks like users don't complain that their app breaks entire playback capability of the system (yeah, it is [a pulseaudio bug](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/944), but looking by the issue it is clear that this won't be fixed). :(

**Comment by ilya-fedin** [comment]
@vimpostor can you try my patch?
https://github.com/ilya-fedin/openal-soft/commit/57592e6341d64763855a61d1bcbc151b71f5f0bd

**Comment by vimpostor** [comment]
> @vimpostor can you try my patch?
> [ilya-fedin@57592e6](https://github.com/ilya-fedin/openal-soft/commit/57592e6341d64763855a61d1bcbc151b71f5f0bd)

Sorry for the late reply, I was not with my computer over christmas time.
I tried your patch and it works! Neither my above minimal reproducable example nor starting Telegram Desktop produces distorted audio with your patched OpenAL.

I used pulseaudio with `default-sample-rate = 48000` and using current OpenAL still produces the distorted audio while your patched version does not with the same Pulseaudio config.


On a related note Linux 5.11 includes patches for improved implicit feedback support in the audio stack, which might fix this problem alltogether from the real source of the bug. I will test it as soon as 5.11 has a proper release. However it is nice to have this worked around in OpenAL now with your patch. :)

**Comment by ilya-fedin** [comment]
Can you change your sample rate to 44100 and check if recording a voice message in tdesktop will work ok or output will be distored?

**Comment by ilya-fedin** [comment]
> On a related note Linux 5.11 includes patches for improved implicit feedback support in the audio stack, which might fix this problem alltogether from the real source of the bug.

As far as I understand, kernel update is not enough, PA folks should use new APIs to subscribe on frequency changing and update PA's internal state accordingly

**Comment by vimpostor** [comment]
Hi, Telegram Desktop crashes with a segmentation fault the second I 
start recording with your patched OpenAL regardless of sample rate, 
while it does not crash with either default sample rate on normal 
OpenAL.

Am Tue, Jan 05, 2021 at 01:37:36AM -0800 schrieb ilya-fedin:

**Comment by ilya-fedin** [comment]
Oops, try with that patch
https://github.com/ilya-fedin/openal-soft/commit/6246f70bc8273b102f24d0dfc9a613bed1e8d57a

**Comment by vimpostor** [comment]
With that patch I get output distortion with my Spotify running at 44100 
Hz as soon as I start recording regardless of Pulseaudio default sample 
rate.

Am Wed, Jan 06, 2021 at 08:33:49AM -0800 schrieb ilya-fedin:

**Comment by ilya-fedin** [comment]
That's what I expected, unfortunately :(
While there's ability to use device sample rate on playback in OpenAL, there's no flag to use device sample rate on recording :(
Unfortunately, I'm not too familiar with OpenAL code to add resample logic to capture, just like with playback.
