### ISSUE TITLE
the error AL LIB(ee) Failed to get next packet size:0x88890004?

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#461]
Hello, I'm here again
this is the same question about pluging out the micphone.
**IN some computer** (win7， win10 ，  virtual machine win0),when I pluge out the mic ,it can still recording "0",and then I pluge in the micphone ,it can record voice continue;

but when we test **some new computer** especially win10 thinkpad pc.  when I pluge out microphone at recording，those computer AL LIB(ee) Failed to get next packet size:0x88890004

I checked the micphone driver; it's very new.and use the realtak driver also. 

use the 1.20 1.21 also have this problem.

**Comment by kcat** [comment]
Some hardware can detect when a microphone is plugged in, letting the system device change state depending if there's anything plugged in or not, while other (usually older) hardware can't, so the system device has to assume there's always something there even when nothing is. OpenAL Soft is simply behaving according to what the system is reporting. If Windows doesn't say anything's wrong and just gives 0s, that's what the app will get, and if Windows says there's an error and doesn't give anything, the error is passed along since there's nothing to give.

**Comment by kcat** [comment]
Closing since there's nothing for OpenAL to do here. If the system reports an unrecoverable error on the device, OpenAL Soft has no real choice but to stop capture and flag the device as disconnected since it's not working. That some hardware doesn't report an error and continues giving samples anyway is out of OpenAL's control.
