### ISSUE TITLE
audio capture not working 

### ISSUE THREAD

**Issue by PGG106** [kcat/openal-soft#478]
i've opened an issue on the telegram for desktop repo about audio messages not working, and i've been advised to post a bugreport here because it's probably a low level problem of openAL, here's the link to that discussion https://github.com/telegramdesktop/tdesktop/issues/8719

and here's the error report i was able to generate 
[openal_log.txt](https://github.com/kcat/openal-soft/files/5322217/openal_log.txt)

**Comment by ilya-fedin** [comment]
Telegram Desktop switched to dsound backend from wasapi backend in version 2.4.0 due to #473 and some issue that openal doesn't see some devices (they just doesn't appear in enumeration, don't have enought information about this yet)

Telegram Desktop uses openal 1.19.1 and after switching to dsound backend, dsound and winmm backends recording silence with @PGG106's device when device frequency is set to 48000 Hz. tdesktop calls alcCaptureOpenDevice with 48000 frequency as well, so, I guess, openal does some resampling when device is set to other frequency and that is what makes the recoeding working?

@PGG106's log is from a test binary with openal 1.20.1 and looks like dsound backend doesn't even start to record with `Error generated on device 17C04BD0, code 0xa004` error

**Comment by kcat** [comment]
> Telegram Desktop uses openal 1.19.1 and after switching to dsound backend, dsound and winmm backends recording silence with @PGG106's device when device frequency is set to 48000 Hz. tdesktop calls alcCaptureOpenDevice with 48000 frequency as well, so, I guess, openal does some resampling when device is set to other frequency and that is what makes the recoeding working?

With DSound and WinMM capture, the system is doing resampling on behalf of OpenAL Soft for the app. With the WASAPI backend, OpenAL Soft would do resampling itself since the system won't.

> @PGG106's log is from a test binary with openal 1.20.1 and looks like dsound backend doesn't even start to record with `Error generated on device 17C04BD0, code 0xa004` error

Hmm. Looking at [the source](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/media/audio/media_audio_capture.cpp), I can't see why that would happen. The device opens correctly, `alcCaptureStart` won't generate `0xa004` (`ALC_INVALID_VALUE`), and `alcGetIntegerv`/`alcCaptureSamples` are given proper values (well, technically `alcGetIntegerv` is being given a wrong count, it wants the number of array elements in the given pointer, not the number of bytes, but that's not causing a problem here since the value is large enough and it only writes the one element it needs to).

The only way I can see that error being generated without any other message being logged is if the backend reports fewer samples during `alcCaptureSamples` than it gave with `alcGetIntegerv`, but I don't see how that can happen either since it's internally holding a ring buffer that's only added to until the app reads samples. Unless `(_captured.data() + s)` is somehow null (which it shouldn't be since `_captured` was just resized), that error shouldn't happen.

I'd need more thorough debugging to see the state of the ring buffer and what the backend is trying to do when querying its size. If you have a debugger, you can set the `ALSOFT_TRAP_ERROR` environment variable to `1`/`true` and OpenAL Soft will call `DebugBreak()` when an error is generated, which allows getting a backtrace to see more precisely where it's being set and what check failed.

**Comment by ilya-fedin** [comment]
> Looking at [the source](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/media/audio/media_audio_capture.cpp), I can't see why that would happen.

:thinking: this should be something that was changed from 1.19.1 to 1.20.1 in dsound backend, since a build with 1.19.1 as well as the build with 1.20.1 and winmm backend doesn't produce such errors (but still records silence when device frequency is set to 48000 Hz in control panel, according to what @PGG106 told)

> If you have a debugger

hmm, even though I can't reproduce silence, I can reproduce the error with any settings in my VM :thinking:

**Comment by ilya-fedin** [comment]
I got a backtrace, but I guess it is completely useless
![image](https://user-images.githubusercontent.com/17829319/95003377-3c6b5100-05ce-11eb-8624-d32da3bdc612.png)

**Comment by PGG106** [comment]
` If you have a debugger, you can set the ALSOFT_TRAP_ERROR environment variable to 1/true and OpenAL Soft will call DebugBreak() when an error is generated, which allows getting a backtrace to see more precisely where it's being set and what check failed.`
if needed i could do it but i would be needing a guide

**Comment by kcat** [comment]
> hmm, even though I can't reproduce silence, I can reproduce the error with any control panel device settings in my VM, looks like recording with dsound backend completely broken on 1.20.1 thinking

Okay, found the problem. The DSound backend was casting the available sample count wrong when no new samples were captured since the last query, causing it to get truncated and wrap around a max of 255 samples (inevitably less than was previously queried and the app is requesting). That's now fixed with commit e7a44d3b7063553fa54e743a4fac116d130fbe1d.

That said, WinMM (and DSound in 1.19.1) should be fine. If that's recording silence, that's what Windows is giving. Perhaps Windows isn't doing the quad->mono conversion and just gives silence for unhandled conversions. Or perhaps there's some other issue with the format descriptor that's preventing it from properly converting.

**Comment by ilya-fedin** [comment]
> Perhaps Windows isn't doing the quad->mono conversion and just gives silence for unhandled conversions.

Do you mean 4 channels by `quad`? @PGG106's microphone is 2-channel, as I seen: https://github.com/telegramdesktop/tdesktop/issues/8719#issuecomment-703132267

This only happens when he has 48000 Hz set, what is equal to the frequency that tdesktop requests. But everything is fine with any other frequency, as he told.

**Comment by kcat** [comment]
> > Perhaps Windows isn't doing the quad->mono conversion and just gives silence for unhandled conversions.
> 
> Do you mean 4 channels by `quad`? @PGG106's microphone is 2-channel, as I seen: [telegramdesktop/tdesktop#8719 (comment)](https://github.com/telegramdesktop/tdesktop/issues/8719#issuecomment-703132267)

Right, sorry. Got mixed up with issue #473.

> This only happens when he has 48000 Hz set, what is equal to the frequency that tdesktop requests. But everything is fine with any other frequency, as he told.

That's odd. Since he says the older version works (which uses the WASAPI backend), that would mean the system is capturing audio on the device. But DSound and WinMM capture silence, only when it doesn't have to resample. I guess trying to do a stereo capture (just to see if it works when it doesn't have to downmix channels along with not resampling) isn't very practical to test.

**Comment by ilya-fedin** [comment]
> I guess trying to do a stereo capture (just to see if it works when it doesn't have to downmix channels along with not resampling) isn't very practical to test.

Yeah, I tried to change channels, but looks like this requires further changes for ffmpeg methods, but I'm not very familiar with that part of code :(

**Comment by ilya-fedin** [comment]
@PGG106 since this seems to be driver incompatibility with old API, i think it is better to close this issue and switch backend back to WASAPI in tdesktop.

But still would be nice to see a Media Foundation backend (even as a non-default backend) in openal, since problems with WASAPI appear very often (and most of them are unreproducible), at least with tdesktop and since most of applications don't care about latency.

**Comment by PGG106** [comment]
yeah that's fine for me , i'll close it with this comment
