### ISSUE TITLE
Rare crash after updating to 1.20.1.

### ISSUE THREAD

**Issue by john-preston** [kcat/openal-soft#486]
I've updated OpenAL Soft to 1.20.1 in Telegram Desktop and started receiving crash reports with such stack traces:
![image](https://user-images.githubusercontent.com/17900494/97703381-f7054b00-1ac9-11eb-886f-c19bd7d3b13e.png)

I think it happens at some moment after destroying an audio source. I even accidentally caught it once in my Debug session:
![image](https://user-images.githubusercontent.com/17900494/97704966-bb1fb500-1acc-11eb-8449-5af512794bdb.png)
When I've stopped a video playback.

It looks like `mSend[0]` in `ALvoice` contains some bad buffer, perhaps buffer of this `TargetData` was already destroyed, still being in `mUpdate` or somewhere:
![image](https://user-images.githubusercontent.com/17900494/97705228-2a95a480-1acd-11eb-9816-926d2c1475ac.png)

At the Context the `mNumSources` equals to 0 and `mSourcesList` has only one item with all free items (so all sources were indeed already destroyed). The `ALvoice` has `mPlayState=Stopping` and `mSourceID=0`.

So it looks like I've called `alDeleteSources`, it called `FreeSource`, it set voice state to `Stopping`, voice source id to 0, and destroyed the source. While that happened the mixer thread started mixing and reading `mSend[0].Buffer` from that voice and crashed.

It looks like `ALvoice::mSend[i].Buffer` comes:
- through `Calc[Non]AttnSourceParams` from `ALvoice::mProps.Send[i].Slot` which comes:
- through `CalcSourceParams` from `ALvoice::mUpdate->Send[i].Slot` which comes:
- through `UpdateSourceProps` from `ALsource::Send[i].Slot`.

In `~ALsource` the `Slot->ref` is decremented and if it becomes zero it can be freed / reused at some arbitrary point in time. But as I can see `ALvoice` when it gets this `Slot` value in `auto copy_send` lambda - it doesn't increment the refcount of that slot, so it may be destroyed while still being hold in `ALvoice::mUpdate->Send[i].Slot`?

BTW `CalcSourceParams` has check for `mSourceID`, but nothing there is synchronized, so I guess we first go through this check, then destroy the source, then try to mix the voice.

Maybe I should synchronize some calls that I don't? But in 1.19.1 this didn't happen.

**Comment by kcat** [comment]
There's a bit of a race here between a source stopping, and any effect slot it's attached to being detached and deleted. When a source stops or is deleted (which implicitly stops it), it's its mixing voice is set to stopping and the source ID cleared, at which point the voice is no longer "connected" to the source, and it will do one more mix using the handful of samples it has stored to fade to 0 gain (this being to ensure a source can stop at any time and cleanly go silent, without any pronounced click or pop sounds). 1.19 didn't have this capability, the voice just stopped when the source did, so there wasn't a risk of the voice using resources the source holds on to, but you could get a click or pop if a source stopped in the middle of the sound.

Since the source is stopped, any effect slots its connected to can be detached and deleted before the voice has a chance to do its last mix. Currently the effect slot holds the effect's mixing buffer, so when the effect slot is deleted, its mixing buffer goes with it.

The proper fix for this, one which appropriately avoids clicks and pops when an effect goes away or the voice changes effect targets, turns out to be fairly tricky since there's several levels of resources being worked with that would need to be virtualized and managed. A more basic workaround, which just stops the crash but can still click/pop, may be needed in the interim.

On the application side, it can be worked around can by waiting about 40ms before deleting an effect slot after the last source using it stopped.

**Comment by john-preston** [comment]
@kcat Is there an easy way to fix that on the library side? I'd cherry-pick it for now (even if it can click / pop). Or if it is not a simple switch, I'll look into adding some delay to clearing the effect slot (right now it is not very easy, they're tied together with the source in my system).

**Comment by kcat** [comment]
> Or if it is not a simple switch

It likely won't be very simple, but it's important enough to prioritize. I was actually preparing for the 1.21.0 release, so it probably won't be very long after the fix is implemented for it to be ready.

**Comment by kcat** [comment]
Commit 52d58a40234b8829801f0a587375eca91694c30f should fix this issue, if you're able to test.

**Comment by john-preston** [comment]
@kcat I didn't experience it myself, but I'll build a new beta version on OpenAL 1.21.0 and see the reports. Thank you!

**Comment by john-preston** [comment]
Thanks, I'll try it out. I think for now this can be closed.
