### ISSUE TITLE
Missing functions in Windows import libs

### ISSUE THREAD

**Issue by slipher** [kcat/openal-soft#497]
Starting from version 1.19, the import libs of the Windows binary releases (both .dll.a and .lib) no longer list the alEffect* functions. Is this intentional?

**Comment by kcat** [comment]
It's not intentional, no. It was a result of making the build while having the router enabled that doesn't include the EFX (and various other non-standard) functions in the import list for OpenAL32.dll. Generally you should load extension functions dynamically, but if you depend on (can't work without) the extension and provide an appropriate OpenAL Soft DLL, there's not much harm. I should have that fixed for the 1.21.1 release.

**Comment by kcat** [comment]
Should be fixed now with 1.21.1.
