### ISSUE TITLE
OpenAL-soft not able to initialise devices under Windows XP

### ISSUE THREAD

**Issue by t9999clint** [kcat/openal-soft#506]
I've tried with multiple games, sound cards and different versions of DSOAL but none of them seem to be able to start under windows XP.  
On Windows 10 it works fine. I ran the openal-info32.exe tool and it mentions that OpenAL version is 1.1 and it's showing EAX as the extensions, but under supported filters and effects it's showing `!!! none !!!`

**Comment by t9999clint** [comment]
Just realized that the effects  none thing is what Win10 shows too and it works on there.  
Might just be a DSOAL issue.  
Any experience with WinXP and OpenAL-soft?

**Comment by kcat** [comment]
> On Windows 10 it works fine. I ran the openal-info32.exe tool and it mentions that OpenAL version is 1.1 and it's showing EAX as the extensions, but under supported filters and effects it's showing !!! none !!!

This would indicate it's using Creative's OpenAL driver rather than OpenAL Soft. OpenAL Soft will show EFX extensions and not EAX, and won't have problems listing the filters and effects.

But I also wouldn't expect DSOAL to work on Windows XP, since it depends on MMDevAPI/WASAPI which was introduced with Windows Vista.

**Comment by t9999clint** [comment]
I see, so this would require a feature request on the DSOAL side.  
Thanks for the info
