### ISSUE TITLE
thread safety: failed to alBufferData if another thread is deleting unrelated buffers

### ISSUE THREAD

**Issue by wangii** [kcat/openal-soft#52]
I found out the read/write locks were implemented at the "device" level, and when buffering data, the read lock is used, while write lock is used in deleting buffers. so when a source finishes playing and associated buffers are being deleting, other ongoing playback would fail to buffer data.

maybe the read/write locks should be implemented at the "source" level? or simply use the write lock in alBufferData? or,  it's the library users' job to take care of it? please advise.

**Comment by kcat** [comment]
The locks will block execution when contended and wait until it's free, not cause a failure/error. It's used to keep the list of buffers safe from unsafe asynchronous changes (e.g. trying to lookup a buffer ID in one thread while another thread is trying to delete one). If ```alDeleteBuffers``` has the write lock when ```alBufferData``` tries to take the read lock, the latter will wait until the former is done (and vice-versa, if ```alBufferData``` has the read lock when ```alDeleteBuffers``` tries to take the write lock).

Are you sure it's ```alBufferData``` causing the error, rather than ```alDeleteBuffers```? In particular, make sure the buffers aren't still set on a source when trying to delete them (even if the source isn't playing, they need to be removed/unqueued first). Otherwise, you can try running the app under a debugger with the ```ALSOFT_TRAP_ERROR``` env var set to ```1``` -- that will cause a SIGTRAP and break execution when an error occurs, letting you get a backtrace to see what's causing it.

**Comment by wangii** [comment]
interesting, the problem is solved by calling `alSourceStop` first even if it's AL_STOPPED, then unqueue buffers.
