### ISSUE TITLE
alcOpenDevice "device configuration" string

### ISSUE THREAD

**Issue by laenion** [kcat/openal-soft#523]
According to the _OpenAL 1.1 Specification and Reference_ `alcOpenDevice` does not only accept NULL, but also
> a null terminated string that requests a certain device or device configuration.

And indeed I've found an application which is trying to use that mentioned "device configuration": See the beginning of `ds_init()` in http://svn.icculus.org/*checkout*/freespace2/trunk/src/sound/ds.cpp?revision=292&content-type=text%2Fplain&pathrev=292

Unfortunately that attempt to open a device with `\'( (sampling-rate 44100 ))` doesn't work for me, so I'm wondering now: Is this supposed to be a valid device configuration (I wasn't able to find any documentation about it), or is this a bug in the upstream project?

The _OpenAL Programmers Guide_ by the way only mentions "a valid OpenAL rendering device" as the parameter...

**Comment by kcat** [comment]
The only standard-defined things you can pass to `alcOpenDevice` is either `NULL`, or a device string returned from enumeration (`alcGetString(NULL, ALC_DEVICE_SPECIFIER)` or `alcGetString(NULL, ALC_ALL_DEVICES_SPECIFIER)`). Anything else is implementation-defined.

As far as I understand, "device configuration" really just means whatever strings the implementation accepts. I don't think there was ever any standard definition for what that means. The old OpenAL SI that was around at the time that code was written accepted configuration strings in some lisp-like format that defined what to open and how. OpenAL Soft can't honor that since it works differently, but what I can do is try to detect such device strings and ignore them.

**Comment by laenion** [comment]
Thanks a lot for all the details, that answers all my questions!

Regarding compatibility with old software it may indeed be a good idea to have a default fallback in case an incompatible / invalid configuration string (though I currently can't remember any other game where this might have been a problem - but it's not unlikely this was taken from some example code, so there may be more and potentially proprietary applications trying this).

**Comment by kcat** [comment]
Should be handled now with commit 8c2592b4d9604d2c47120fdc7f773c22ed92af16. If there's still any issues, feel free to reopen.
