### ISSUE TITLE
Modify Pitch before source

### ISSUE THREAD

**Issue by marauder2k7** [kcat/openal-soft#527]
Was wondering how i would go about modifying the pitch of a buffer stream before it gets to the source? I know i can do it with a source with AL_PITCH but is there a way to do it before that? We are working on a class for our engine for mixing buffer data into 1 source 

Sorry for making this an issue i didn't know where else to ask lol

**Comment by kcat** [comment]
The only way you can change the pitch "before" it gets to the source with OpenAL is to supply a different sample rate/frequency to `alBufferData`. That will cause the source to play it back faster or slower, at a higher or lower pitch, depending on the value given compared to its normal sample rate (e.g. if you have a 22050hz sound, and you pass 44100 to `alBufferData`, it'll play twice as fast with double the pitch). This can't be changed on-the-fly during playback though, since a buffer can't be modified while playing and a source's buffer queue needs to have all buffers using the same format and sample rate. Only the source's `AL_PITCH` property (or `AL_VELOCITY`) can change the rate/pitch dynamically while it plays.

The alternative is to resample it manually before giving it to `alBufferData`. Though that's not straight-forward to do if you want it done with high quality (linear resampling isn't enough), and OpenAL can't do that for you.

**Comment by marauder2k7** [comment]
that is perfect! this is more for being able to say output all the sounds of a vehicle through 1 source instead of having a separate source for every file and then each time that particular file plays it can modify the pitch a bit to get more dynamic

**Comment by marauder2k7** [comment]
just out of curiosity, buffer layering was never added was it? i remember a few years ago something about it being added with AL_BUFFER# for each source, or was there something else for doing that? 

To explain better we are trying to implement a purely openal system like fmod for our engine

**Comment by kcat** [comment]
It was something I was playing around with, but ended up dropping it because it was pretty limited (buffers needed the same format and sample rate) and complicated certain parts of the mixer, without really adding any new functionality. Having multiple buffers play at the same time could be done more flexibly with multiple sources, playing them at the same time with `alSourcePlayv` and keeping their property changes synchronized using batched updates.

**Comment by marauder2k7** [comment]
yeah we've had that for the past few years but run out of sources too quickly on certain platforms so that's why we were trying to make it so one source per object to play multiple sounds at the same time mixing them as required. Just for a single vehicle or player you could have 4 or 5 sounds playing at any given time

**Comment by marauder2k7** [comment]
the buffer layering stuff isnt available anywhere is it because we are making our own file format for this class which is basically just comprised of the al buffer data for each sound file which we should be able to make sure all files are the same sample rate when being ingested too

**Comment by kcat** [comment]
Buffer layering also had the restriction that they all had the same volume, position, filtering, etc. 

Normally you don't really need more than a couple hundred sounds playing at once, as either they'd all be too close to make out any individual sound, or they'd be at such a distance that the quietest one wouldn't be missed under all the other sounds.

One of the better ways I've seen a real-time audio system implemented with OpenAL is to maintain a list of active SoundEmitters with their position, reference distance, gain, whatever other relevant parameters you use, and a priority value (and an optional OpenAL source ID). If you need to play a sound and there's not enough sources, find the active SoundEmitter with the lowest priority value, and which is the quietest given its relevant distance/gain properties. If the sound you want to play is higher priority, or equal priority but louder/closer, forcibly stop or preempt that other emitter and take its source to play the new sound with, otherwise don't play the new sound and leave the SoundEmitter you're trying to play as preempted (i.e. has no OpenAL source).

Looping sounds that don't have a playing SoundEmitter should regularly try to restart, so it'll start playing again when a source becomes free or if it or the listener moves to make it louder than another playing sound. Non-looping sounds don't really need this, since they typically would have finished before having a chance to actually play again (though it can be done if you really need).

**Comment by marauder2k7** [comment]
having the same position and filtering wouldn't have been an issue but the same volume would be yea =/ damn thanks for clearing things :)
