### ISSUE TITLE
Suspicious #endif and triggering ERR(...)

### ISSUE THREAD

**Issue by AKonia** [kcat/openal-soft#534]
Is `#endif` on line **423** ok, especially with this lonely `if`on line 422? On my system macro on line 426 always executes.
https://github.com/kcat/openal-soft/blob/6e676b81d588f9bfd2b0b69af48cdf9a701ca24a/alc/helpers.cpp#L419-L427

system: manjaro linux 4.19.*

**Comment by AKonia** [comment]
An indentation on line 424 looks suspicious. 

ERR triggers with `Operation not permitted` message error.

**Comment by kcat** [comment]
> Is `#endif` on line *423* ok, especially with this lonely `if` on line 422?

Yes. If the `SCHED_RESET_ON_FORK` flag is defined, it tries to set that with `SCHED_RR`. If that fails with `EINVAL`, or if the flag isn't defined, it just tries to set `SCHED_RR` alone.

> ERR triggers with `Operation not permitted` message error, I think it's better add checking for EPERM with more silent behavior, or just don't touch threads scheduling at all.

It's generally a good idea to have real-time processing for audio mixing/output threads, since there's a limited amount of time to get audio to the device. More buffering can help avoid the problem, but you don't want too much with real-time playback since it adds latency. I suppose I could downgrade the message to a WARN, though, and/or try to lower the niceness instead if real-time priority fails.

**Comment by AKonia** [comment]
@kcat problem is the fact that from 3 cases: `user, sudo, root` on my machine works only from user-case with `Operation not permitted` OAL-S error message, with ALSA error in case of `sudo` and some **xdg-*** error in case of `root` - so the question: is it ok ?

As I know scheduling manipulation makes sense only on very slow machines and on machines with limited resources such as HPC, so are there any tests, that precisely shows neediness of this approach in common situation ? Wouldn't it be better to make this scheduling manipulation as build option(Offed by default) ? Or at least wouldn't try to control scheduling if app doesn't have enough permissions, because it is common situation when system don't allow sched-manip without permissions.

**Comment by kcat** [comment]
> is it ok ?

It's not ideal for users to not be able to set heightened priority for important threads. Normal apps shouldn't be run as `sudo`/`root`.

The error message itself is harmless; the library will do what it's supposed to with what it can. It's just telling you there's a problem with getting real-time priority that can cause unstable audio playback (higher chance of dropouts or latency).

> As I know scheduling manipulation makes sense only on very slow machines and on machines with limited resources such as HPC, so are there any tests, that precisely shows neediness of this approach in common situation ?

Scheduling is also important for timing, not just performance. When the audio card or audio server signals the app that more audio is needed, it can be detrimental for the scheduler to think the thread is just going to do some normal unimportant processing and not immediately wake it.

It's not something that can be easily tested since it's highly dependent on the OS (Linux's scheduler is more adaptive than Windows', for example), audio load (how much CPU time is needed to process, mix, and write out audio), and general system load (how much contention there is for the audio thread to get the CPU and keep it for the time it needs).

> Wouldn't it be better to make this scheduling manipulation as build option(Offed by default) ? Or at least wouldn't try to control scheduling if app doesn't have enough permissions, because it is common situation when system don't allow sched-manip without permissions.

It shouldn't be off by default since real-time priority is important for real-time audio. JACK, PipeWire, PulseAudio, and CoreAudio (OSX), all attempt to get real-time priority on the client's audio processing thread for a reason. There isn't much need to check permissions before attempting to modify it, since the same thing will happen in both cases: either OpenAL Soft sees permission isn't available and will warn it couldn't set real-time priority, or it tries to set real-time priority and will warns that it couldn't set it.

What I probably need to do is read up on how apps try to get real-time priority, if setting the scheduler through pthreads isn't how it's done these days. I vaguely recall something about a D-Bus service that an app can request real-time priority from, and which also acts as a watchdog against misbehaving real-time threads. If that's the normal way to do it on Linux, that's what I may have to do.

**Comment by kcat** [comment]
Commits 5165b29b1945e1cff5e8c042bd371a5b2da9b492 and 37730927efe488e63114b5c665bd53e9ee5b478c do this, and it no longer prints an ERR if it fails to get real-time priority (it prints WARNs instead).
