### ISSUE TITLE
Get amplitude of time point in source

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#553]
Hi, I was wondering how I'd get the amplitude of the 

a. current time point
b. any time point

in the source.

**Comment by kcat** [comment]
You'd have to keep a local copy of the buffer samples, then to get the amplitude at the current time point, get the source sample offset and read the sample at the returned offset. To get it at any time point, just read the sample at the time point you're interested in.

**Comment by hsdk123** [comment]
@kcat Thanks for the quick replies!

> read the sample at the time point

How would I do this?

**Comment by kcat** [comment]
If you have a 16-bit mono buffer, declared like this
```c++
short *Samples;
```
then after you've allocated and loaded it with the sound, read from it:
```c++
amplitude = Samples[offset] / 32768.0f;
```
where `offset` is the sample offset you want to check.

**Comment by hsdk123** [comment]
@kcat How should I calculate which sample to use if I have multiple channels?

**Comment by kcat** [comment]
> @kcat How should I calculate which sample to use if I have multiple channels?

That depends on what you're ultimately trying to do. You could use whichever is farthest from 0 (e.g.
```c++
float amplitude = sample[offset * channels] / 32768.0f;
for(int i = 1;i < channels;++i)
{
    float atmp = sample[offset*channels + i] / 32768.0f;
    if(fabsf(atmp) > fabsf(amplitude))
        amplitude = atmp;
}
```
), or you could add them together (e.g.
```c++
float amplitude = sample[offset * channels] / 32768.0f;
for(int i = 1;i < channels;++i)
    amplitude += sample[offset*channels + i] / 32768.0f;
```
), or you could average them (e.g.
```c++
float amplitude = sample[offset * channels] / 32768.0f;
for(int i = 1;i < channels;++i)
    amplitude += sample[offset*channels + i] / 32768.0f;
amplitude /= channels;
```
). It really depends on what it's for and what it needs to represent.

**Comment by hsdk123** [comment]
@kcat Thanks, makes sense!
What's the reason there's no division for 32bit buffers?
```
amplitude = sample;
```

**Comment by hsdk123** [comment]
And when the samples are played, what is the amplitude of the sound that I hear as a user? (is it the sum, or the average, etc.)

**Comment by kcat** [comment]
> What's the reason there's no division for 32bit buffers?

Because 32-bit float samples are already normalized between -1...+1, where 8- and 16-bit samples are scaled up to be integers, so need to be scaled back down, basically.

> And when the samples are played, what is the amplitude of the sound that I hear as a user? (is it the sum, or the average, etc.)

That's a bit more complicated. The amplitude is basically the pressure level of the sound wave in that direction at that instant. So the left channel sample is the amplitude the listener gets on the left, and the right channel sample is the amplitude the listener gets on the right. The channel sum is the overall pressure in the exact center where the two meet. The channel average is the general amplitude level a listener would get. And the farthest from 0 is the "maximum" amplitude that gets to the listener from some direction.

But still, the perceived loudness a user would hear is even more complicated, as sound is the result of change in air pressure over time (which is perceived by different sections of the ear responding to different overlapping frequency bands).

Generally, to get a general perceived volume for a sound at a point in time, you calculate the Root Mean Square of the samples around that point in time. For a mono sound, that would be something like
```c++
// Take the square root of the average of the squares
float loudness = sqrtf((samples[i-n]*samples[i-n] + samples[i-n+1]*samples[i-n+1] + ...
    + samples[i+n-2]*samples[i+n-2] + samples[i+n-1]*samples[i+n-1]) / (n*2));
```
(where offsets outside of the sound buffer range should be treated as reading 0 amplitude). The value for `n` is somewhat arbitrary, but the smaller it is, it's less likely to represent what the listener perceives, while the larger it is, the more it represents the sound as a whole rather than at that point in time.

**Comment by hsdk123** [comment]
Thanks for the detailed response, I was able to get something up!
