### ISSUE TITLE
Broken spatial sound in Fallout 3 and Fallout New Vegas

### ISSUE THREAD

**Issue by TheMaxus** [kcat/openal-soft#561]
In the latest version 1.21.1 the spatial audio is completely missing in Fallout New Vegas and Fallout 3 and it also causes frequent crashes that seem to disappear when using `set DSOAL_LOGLEVEL=2`. Older versions seem to work perfectly.

I've attached the debug log.

[dsoal_error.txt](https://github.com/kcat/openal-soft/files/6436655/dsoal_error.txt)

**Comment by kcat** [comment]
The log unfortunately doesn't tell me much. Can you get a backtrace to the crash? Does it work with 1.21.0, and if not, what's the last version that does?

**Comment by TheMaxus** [comment]
How do I get a backtrace? And yes it does work perfectly with 1.21.0.

**Comment by kcat** [comment]
You'd need a debugger, and probably debug builds of OpenAL Soft and DSOAL. depending on where the crash is. Short of that, you could try setting `DSOAL_LOGLEVEL=3` and see where it ends before crashing, although you say setting `DSOAL_LOGLEVEL=2` prevents the crash, so that may not work. However, getting the output with `DSOAL_LOGLEVEL=3` and `ALSOFT_LOGLEVEL=3` may help show why spatial sound isn't working.

**Comment by TheMaxus** [comment]
I had no luck reproducing crashes, but the spatial sound problem is still there. I've attached logs for both versions. I've also tried the latest git version and the problem is still there. I hope this helps find the problem with spatial sound.

[logs.zip](https://github.com/kcat/openal-soft/files/6437767/logs.zip)

**Comment by kcat** [comment]
Alright, well it appears the spatial sound breaks because the game sets a ludicrously high minimum sound distance of 1000000000, presumably to disable automatic distance attenuation while keeping 3D positioning, and with OpenAL Soft 1.21.1, it uses 1/1024th of the minimum distance to determine if a sound should be treated as being at the same location as the listener (since the math to transform the source's world position into the listener's local space for panning is subject to floating point precision errors, the amount of which varies depending on the specific position and orientation values in use). I'll need to figure out some other way to deal with that.

**Comment by kcat** [comment]
Commit 58a9549a5886fe91aba698abb4e6e4c0c94f129e should fix spatial sound. Though I still need to see if it re-breaks another game (#522).

**Comment by TheMaxus** [comment]
Thanks! The commit indeed fixes the spatial audio and I haven't had a single crash while testing so I think the problem was in the pre-built binaries I was using at the time or something else.
