### ISSUE TITLE
MSYS2 Patches

### ISSUE THREAD

**Issue by Amavect** [kcat/openal-soft#569]
The MSYS2 project has a few patches that I'm thinking should be pushed upstream.
The most important of which are renaming the mingw-w64 library from OpenAL32 to openal (for non-MSVC compilers).
Would you be interested in these? I can put together a PR.

https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-openal

**Comment by kcat** [comment]
The library needs to be OpenAL32.dll on Windows for compatibility. That's what existing apps and projects will expect. With the router enabled, it also has to be specifically named ending in `*oal.dll`, or else it won't be recognized.

The PortAudio change may be something to include, although I'd do it more robustly by checking all potentially valid names, instead of assuming a DLL name based on the compiler (whether a given system has `libportaudio-2.dll` or `portaudio.dll` installed already is entirely separate from whether OpenAL Soft was built with MinGW or not; the same DLL can go on a system with `libportaudio-2.dll` as one with `portaudio.dll`).

For the OSS patch, I don't see why that's necessary. If it's being erroneously detected when it's not actually available, the detection should be fixed to avoid false detection, or if it's being detected properly but fails to build, the OSS backend should be fixed to build properly. If it's being detected and built correctly, but you don't want it enabled in the build, you can explicitly disable it by setting `ALSOFT_BACKEND_OSS` to `FALSE`/`OFF`/`NO` with cmake (`cmake .. -DALSOFT_BACKEND_OSS=FALSE`).

I don't see what's wrong with the libm check, since it might be needed if it's available. Why does that need to be explicitly avoided?

For the WindowsSDK/WinMM import patch, the latest version doesn't explicitly search for the SDK anymore, so it shouldn't be necessary now.

**Comment by Biswa96** [comment]
> Why does that need to be explicitly avoided?

Probably for this issue https://github.com/msys2/MINGW-packages/issues/8637. libm is part of msys2's *nix realm. But mingw does not link with any cygwin/msys2 related library.

**Comment by Amavect** [comment]
As much as I would like consistency between OSes and platforms, I believe that the library maintainer gets to call the shots.
The MSYS2 maintainers don't seem to want to change their naming scheme, and workarounds like pkg-config have not helped, so I'm going to resort to symlinking the names for my projects.

Thanks for the tip that the WindowsSDK patch is unneeded for 1.21.1. I'll be working on a patch for downstream.
