### ISSUE TITLE
Driver isn't the default with ALC_ENUMERATION_EXT

### ISSUE THREAD

**Issue by mirh** [kcat/openal-soft#574]
The EnumerateWin32 sample returns this, and of course games using the former requires forcing. 
```
All Available OpenAL Devices

Devices available with standard ALC_ENUMERATION_EXT
===================================================
                                                OpenAL Spec/Ext Support
#    Device Name                               Default  1.0   1.1   EFX

0  - Generic Software                           X              X     X
1  - OpenAL Soft                                               X     X


Devices available with ALC_ENUMERATE_ALL_EXT
============================================
                                                OpenAL Spec/Ext Support
#    Device Name                               Default  1.0   1.1   EFX

0  - OpenAL Soft on 27GL850 (NVIDIA High Definition Audio)
                                                X              X     X
1  - OpenAL Soft on Speakers (Realtek(R) Audio)
                                                               X     X
2  - Generic Software on 27GL850 (NVIDIA High Definition Audio)
                                                               X     X
3  - Generic Software on Speakers (Realtek(R) Audio)
                                                               X     X
```

**Comment by kcat** [comment]
If this is with Creative's router, there's nothing OpenAL Soft can do to change the way the router orders `enumerate` vs `enumerate_all` queries (and which driver is used to query the default). Technically given OpenAL Soft's name as `soft_oal.dll`, it should be found before `wrap_oal.dll`, and thus be earlier in the driver list, but there's complicated logic in Creative's router for determining which drivers to prioritize when.

If this is with OpenAL Soft's router, I'm not sure why that would happen. The `ALC_DEVICE_SPECIFIER` and `ALC_ALL_DEVICES_SPECIFIER` use the same driver order to build their respective lists, and use the same order to query the defaults, so along with `soft_oal.dll` being sorted before `wrap_oal.dll`, OpenAL Soft should be preferred over Generic Software in both cases.

**Comment by mirh** [comment]
Yes, this is with the creative's router (btw is there any source code newer than version 6.14.357.23 available somewhere?)
And now that you mentioned it, I found out that *Generic Software* was preceding *OpenAL Soft*, because wrap_oal.dll was still present in the game root folder (thus "local" wins over "system" querying I guess). 

But even once I take care of that, regardless of the querying "order", the game still prefers generic software since that's somehow flagged as default (so this would be one very compelling reason for why system OpenAL32.dll could as well be replaced altogether with openal-soft). 
Why is that?

Could it have something to do with the `OPENA32DLL - Still didn't find exact match, picking first` warning that is printed when you use the 6.14.357.22 router with just oal-soft enumerable?

**Comment by kcat** [comment]
> But even once I take care of that, regardless of the querying "order", the game still prefers generic software since that's somehow flagged as default (so this would be one very compelling reason for why system OpenAL32.dll could as well be replaced altogether with openal-soft).
> Why is that?

It seems for standard enumeration, Creative's router specifically looks for an OpenAL device name that contains `"X-Fi"`, `"Audigy"`, `"Generic Hardware"`, or `"Generic Software"`, in that order, to set as the default (it actually first looks for an exact match for the default name reported by DSound or WinMM, e.g. `"27GL850 (NVIDIA High Definition Audio)"`, which of course won't match device names starting with `"OpenAL Soft on"` or `"Generic Software on"`; it would only match a hardware driver that lacks the prefix). If it still doesn't find anything, then it just picks the first name in the list.

Capture enumeration and extended enumeration (`ALC_ENUMERATE_ALL_EXT`) don't use a predefined list or names to match, so will tend to get OpenAL Soft device names first instead of the wrapper driver names, if `soft_oal.dll` gets found/loaded before `wrap_oal.dll`.

> Could it have something to do with the `OPENA32DLL - Still didn't find exact match, picking first` warning that is printed when you use the 6.14.357.22 router with just oal-soft enumerable?

Probably. I don't see that message anywhere in the code I have, but it looks like the kind of thing that would be printed if it couldn't find any of the aforementioned names (from `ct_oal.dll` or `wrap_oal.dll`), since OpenAL Soft won't have them and it'll be forced to pick the first it has in the list.

**Comment by mirh** [comment]
Mhh, [I see](https://github.com/rpavlik/openal-svn-mirror/blob/928c7ffbf00bfe1a93ede49e18d261ab00e62ac0/OpenAL-Windows/Router/alc.cpp#L590L596)... It's really the router to be biased. 
On the other hand, to be fair, I just checked out sens_oal.dll and creative's strategy seems to have been exactly to report individual device names here (hell, even with ALC_ENUMERATE_ALL_EXT, they have no "*X on* Y" entry). 
I'm not really sure on how this arms race could be played.

**Comment by kcat** [comment]
> On the other hand, to be fair, I just checked out sens_oal.dll and creative's strategy seems to have been exactly to report individual device names here (hell, even with ALC_ENUMERATE_ALL_EXT, they have no "_X on_ Y" entry).

It's possible that's just how Sensaura themselves made the driver, not really thinking about compatibility with other drivers through the router, and Creative didn't care to change it. Either that, or Creative changed it (or purposely left if alone) to simulate hardware devices. Though I don't imagine that would play nice with actual hardware drivers also being available.

Unfortunately I don't think there's any way to improve the situation with Creative's router. You could simply search manually for device names that contain OpenAL Soft to use as a default, ignoring the defaults reported by OpenAL if you find something, and rather than calling `alcOpenDevice(NULL)` to open a default, explicitly pass `"OpenAL Soft"` as the device name.

OpenAL Soft's router should work better, if you're able to use that. It's more consistent with normal, extended, and capture enumeration order and doesn't give preferential treatment to specific names, so `soft_oal` should get found first and take priority over `wrap_oal`. You can also use the WGL trick to temporarily open an `"OpenAL Soft"` device (or some other preferred driver), use that handle with `alcGetProcAddress` to get functions directly from the driver, and use the returned function pointers instead of the router functions (Creative's router doesn't allow this trick, its `alcGetProcAddress` will return the router functions regardless of the provided handle when possible, whereas OpenAL Soft's router passes the request along to the driver if given a non-null handle).

**Comment by mirh** [comment]
Unfortunately I'm tinkering with old games, so it's not really like I am much in control of anything here. 
And even though the rejuvenated router sounds the right thing to do, compiling it myself and then shipping it "unofficially" doesn't really seem much tenable. 
So if you aren't up to raising the stakes, I guess I should now recommend people to just replace the router altogether for a somewhat proper OOTB experience (and to the very least this is why creative is doing what they are doing, otherwise there's no way their new cards could work without hacks at least in older applications)

**Comment by mirh** [comment]
What if you retooled alcDefaultName to have some whatever "punny" word that contained "X-Fi" or "Audigy" within?
Strstr can match whatever subsequence of characters so 1. you wouldn't be using any trademark at the end of the day 2. you can think to some tongue-in-cheek like "maX-Fire" or "Audigyberty" (too bad I don't know [esperanto](http://ixbtlabs.com/articles/audigyplatinumex/index.html))

I get that it's a bit uncouth.. but having to tell people to tinker with dozens of old games every time seems quite a PITA.
