### ISSUE TITLE
Bad audio quality when using PulseAudio with defaults

### ISSUE THREAD

**Issue by MarcelHB** [kcat/openal-soft#588]
Hello,

When using https://github.com/gemrb/gemrb with OpenAL on Windows, the music of the games sounds as good as expected.

On Linux, my Ubuntu 21.04 currently provides OpenAL soft v1.19.1, and the music sounds comparably bad, like being downsampled. I can reproduce this by using `alureplay` to exclude any bad API use.

That made me try setting ALSA in the config file:
```ini
[general]
driver = alsa,
```
Now, I have the expected audio quality, and my PluseAudio widget displays `ALSA plugin` for the respective application. My  playback device is a Creative Sound Blaster Z. 

- Is this a known issue that has been fixed by a newer version?
- Otherwise, is there additional information I can provide?
- Is there a setting in `[general]` or `[pulse]` I should try instead?

Thanks!

**Comment by kcat** [comment]
A shot in the dark, but are you using headphones, or have the device configured to be headphones in PulseAudio? OpenAL Soft's PulseAudio backend can detect when the device is set as headphones and automatically enable HRTF for binaural mixing, since plain stereo mixing on headphones doesn't tend to sound good (the ALSA backend can't detect that, so defaults to plain stereo for stereo output). HRTF creates a more "external" quality to the sound, simulating the sound coming from points in space around you, instead of pushing the left channel directly to the left ear and the right channel directly to the right ear with no cross-talk. Particularly, with a stereo track it simulates how it would sound when listened to with speakers. Some people may not like the effect, or the default data set may not work well for your head/ear profile.

If this is what's happening, you can disable HRTF if you don't want it. With the setting:
```
[general]
stereo-mode = speakers
```

If the issue isn't HRTF, can you provide trace logs from using ALSA and PulseAudio? Setting the `ALSOFT_LOGLEVEL` environment variable to `3` will make OpenAL Soft print more information to `stderr` about what it's doing when an app is run.

**Comment by MarcelHB** [comment]
You are right, I'm using balanced stereo headphones. What you suggest also fixes the experience.

This is the spectrum sample for some music as I'd like to hear it:
![Screenshot_2021-08-09_18-44-19](https://user-images.githubusercontent.com/238558/128743098-ebf64849-6080-4acd-b904-8ab25b062bc3.png)

This is the `auto` setting, damping around 8kHz, and boosting around it:
![Screenshot_2021-08-09_18-43-15](https://user-images.githubusercontent.com/238558/128743203-c86488f8-1b1e-443e-8d05-c1da4d422555.png)

I'm fine if this serves well to maority of the users, and since I now know that it's not a technical difficulty.

**Comment by kcat** [comment]
Yeah, HRTF works by altering the frequency response of the sound, creating various peaks and troughs as a result of the head and ear's influence on soundwaves from external sources. For instance, this is the frequency response of pure whitenoise (which normally has a completely flat linear frequency response) through the default HRTF data set, simulating the sound coming from directly in front:
![Screenshot_20210809_141015](https://user-images.githubusercontent.com/1545516/128775223-1bc1bdd7-8e83-4165-a2d2-f81e8e9f5292.png)

And different HRTFs have different effects on the sound, for example this is the same whitenoise with a different HRTF data set:
![Screenshot_20210809_140354](https://user-images.githubusercontent.com/1545516/128775351-c85fd455-1092-4197-8d42-4168666d23b6.png)

Whether or not it creates a good effect will depend on having a frequency response that's a close-enough match to your own ears. The default one OpenAL Soft comes with is generally considered a decent generic one, but it's still ultimately dependent on the individual how well it works. Alternate data sets can be used if a better one can be found, though the library doesn't currently provide any others itself.

Of course, any HRTF effect may not sound "good" if it's not what you expect or want, regardless of how well it matches. Especially if you have a track that's already a binaural mix meant for headphones, playing it through simulated speakers won't be ideal (OpenAL Soft allows apps to specify if a given track should be played with virtual positioning/HRTF panning, but the app has to indicate that when playing a given track). So there's always the option to turn it off.

**Comment by MarcelHB** [comment]
Thanks for the insights. Some of the tracks are actually recorded binaurally, and especially the ones I used for comparison. But now we can provide Linux users hints on how to adjust this if they dislike the default.
