### ISSUE TITLE
PipeWire backend possible in the future?

### ISSUE THREAD

**Issue by KynikossDragonn** [kcat/openal-soft#596]
While PipeWire has both a ALSA plugin (that's about as much as you expect from PulseAudio's ALSA plguin) the PulseAudio side of things has to be provided by a additional daemon process, that in of itself adds a slight bit of overhead over just PipeWire's server process by itself.

Using `drivers = alsa` will obviously cut out having to use `pipewire-pulse` but I'm wondering if it may be a good idea to try to add a native backend for people using PipeWire as opposed to PulseAudio.

It may be a bit too early to go for it though, PipeWire is still under heavy development but it shows a lot of promise. It has way less CPU usage and buffering problems than PulseAudio already. (Even just using PipeWire with OpenALSoft set to ALSA, I get way less CPU usage and other issues under it versus PulseAudio)

**Comment by kcat** [comment]
Current master has an in-progress PipeWire backend. It needs to be enabled with `drivers = pipewire` and there may be a few quirks (it won't autodetect a device being headphones, like the PulseAudio backend does, for example), but it should be fully functional. The only real reason it's not auto-selected is because currently it doesn't know during initialization if PipeWire is driving audio devices instead of Pulse or something else, since you can have PipeWire installed but not used for audio.

**Comment by KynikossDragonn** [comment]
Failing to autodetect headphones is also something I noticed in PipeWire (I have to keep manually selecting the port in pavucontrol) and has been reported as a issue on the gitlab page for it.

Headphones on my system is strange, the back and front 3.5mm connectors appear to be two separated things in ALSA mixer, one is normally muted for the other under PulseAudio.

I usually only use headphone connectors on speakers not on an actual PC or laptop.

I'll check out the current master though, thanks!

**Comment by kcat** [comment]
1.22 has a PipeWire backend, used by default when built with support for it.
