### ISSUE TITLE
Use a custom HRTF

### ISSUE THREAD

**Issue by BEENNath58** [kcat/openal-soft#611]
I compiled OpenAL Soft and now I want t use a custom HRTF for the program. Where do I configure the OpenAL.DLL, is there any .ini file that I must configure?

**Comment by kcat** [comment]
If you built the `alsoft-config` utility (which requires Qt5), you can run that to configure the library. You can also use the program from the latest 1.21.1 release (the available options are mostly the same). Under the HRTF tab, you can set the paths for HRTF data files as necessary, and set the preferred HRTF to use. If you don't have and can't get the `alsoft-config` utility, then on Windows you want to create/edit the `alsoft.ini` config file either in the same folder as the executable, or in the folder indicated by the `AppData` environment variable. Then set the `hrtf-paths` and `default-hrtf` options as appropriate:
```
[general]
hrtf-paths = C:\path\to\hrtf\files # optional, only if they're not already in the %AppData%\openal\hrtf folder
default-hrtf = MyHRTF # the filename without the extension, case-sensitive
```

Be aware that the HRTF data file has to be in the right format. OpenAL Soft uses its own `.mhr` format, which can be created from the `makemhr` utility, typically from SOFA files. The SOFA files and resulting mhr files should have full sphere responses in a regular layout pattern (it's okay if part of the bottom is missing, makemhr can synthesize those as needed). Notably, HeSuVi style HRTFs will not work, since they simulate discrete speaker setups like 7.1 rather than a regular shaped spherical pattern.

**Comment by BEENNath58** [comment]
>  If you don't have and can't get the `alsoft-config` utility, then on Windows you want to create/edit the `alsoft.ini` config file either in the same folder as the executable, or in the folder indicated by the `AppData` environment variable. Then set the `hrtf-paths` and `default-hrtf` options as appropriate:
> 
> ```
> [general]
> hrtf-paths = C:\path\to\hrtf\files # optional, only if they're not already in the %AppData%\openal\hrtf folder
> default-hrtf = MyHRTF # the filename without the extension, case-sensitive
> ```
> 

I couldn't find the 'alsoft-config' utility so I will create the 'alsoft.ini'. I assume putting it 'AppData' makes it a uversal configuration for every application run on openal-soft?

I also assume that this .ini file can use the other options provided in the 'alsoftrc.sample' file or does it need a differ file too?

**Comment by kcat** [comment]
Putting it in AppData makes it affect all apps that use OpenAL Soft, yes (all of them that can access that folder, at least). The ini can have other options too, yes.
