### ISSUE TITLE
alSourcePlayv with multiple sources takes up to 9 milliseconds to execute

### ISSUE THREAD

**Issue by Vercidium** [kcat/openal-soft#617]
I've recently been facing some performance issues with OpenAL when using `alSourcePlayv`, which I usually call with 2-6 sources. Sometimes it executes instantly whereas sometimes it takes up to 9 milliseconds, causing a stutter in my game.

Could this be due to an internal lock? In my scenario it's not urgent for sounds to play instantly; instead is it possible to place these source IDs in a queue, for OpenAL to play when it's ready?

**Comment by kcat** [comment]
Is this with the latest version of OpenAL Soft? With 1.21, it does put the sources in a queue or sorts to play later, though there are a couple locks it has to use to protect against other threads accessing the same things (which shouldn't be a problem if you aren't calling OpenAL functions on other threads). It does have to do a sync with the mixer (i.e. wait until the mixer isn't actively mixing samples for the device) after putting them into the queue, but that's a busy-wait, and would only happen if the mixer happens to be executing at the exact time the source changes are queued, and shouldn't take nearly 9 milliseconds to finish.

Since 9ms is pretty close to a typical timeslice, it does suggest the call is being temporarily blocked/preempted by something, but if you're not making OpenAL calls on other threads, I'm not sure what it could be.

**Comment by Vercidium** [comment]
Yeah this is with OpenAL Soft version 1.21.1 (DLL created 5/05/2021).

I'm only calling OpenAL functions on the main thread, and I call `alSourcePlayv` just before `alProcessContext` each frame.

The sync to the mixer might be the cause of the problem as there are 24 people in game (all playing footsteps/shooting sounds), meaning there could be hundreds of active sources at once. Is it possible to put the sources in a new queue that will then be processed when the mixer finishes processing?

**Comment by kcat** [comment]
> The sync to the mixer might be the cause of the problem as there are 24 people in game (all playing footsteps/shooting sounds), meaning there could be hundreds of active sources at once. Is it possible to put the sources in a new queue that will then be processed when the mixer finishes processing?

The sources are already being put into a queue to be processed/played later. The issue is, once `alSourcePlayv` returns, any and all subsequent calls have to recognize the source is "playing" and act accordingly, so the source is actually put into a pseudo-playing state where it looks like it's playing, but won't actually start until the mixer next runs and processes the queue for source changes. Some functions act differently depending if the source is playing or not, and since the state of the source also depends on the mixer state, which some calls can read atomically, there are edge cases. For instance, the mixer can be running and have just finished handling the queued source changes, then the change for a source to play is queued and another call is quickly made which sees the mixer running, thinking it means any pseudo-playing sources should now be in a true playing state... which it wouldn't be. So queueing source changes has to sync with the mixer, wait for it to finish its current invocation, so future calls won't see the mixer running while the change isn't applied. The setup is unfortunately a bit more fragile than I'd like, it's possible that I could loosen some sync requirements without issue, but it'll need to do a careful evaluation to make sure it won't trip up with various possible sequences of events.

In any case, I doubt that's the problem here anyway, particularly if it's happening regularly. It shouldn't take 9 milliseconds for the mixer to run an update, unless it's being heavily overloaded. The mixer should be running for less time than it's not, so most syncs with the mixer are instantaneous with unlucky callers getting a delay of maybe a few milliseconds. But a consistent 9ms wait is nearly half of the ~20ms update period, so you'd have a core at a constant 50% utilization just processing audio, with high risks of underruns if the audio thread wakes up late or gets preempted. And the 9ms would only be the time it takes for `alSourcePlayv` to sync, meaning the mixer would already have been running for the call to get caught on it like that. Anything else that needs to sync with the mixer would also see this same delay (which includes stopping/rewinding sources, getting the source playback offset, or device clock).

A more precise profile of what in the `alSourcePlayv` call is being slow would be helpful. I don't know what tools there are on Windows for profiling libraries, but a release+debug build should help show what's causing it to take the most time.

**Comment by Vercidium** [comment]
Sorry for the delay, closing this as the spike was caused by too many active reverb effect slots (one per active sound). I've reverted to only using 1 and this function is now running very quickly.

**Comment by Vercidium** [comment]
Sorry for the delay, closing this as the spike was caused by too many active reverb effect slots (one per active sound). I've reverted to only using 1 and this function is now running very quickly.
