### ISSUE TITLE
[makemhr] Any reason for MIN_RATE = 32000?

### ISSUE THREAD

**Issue by emoose** [kcat/openal-soft#619]
Hi, just wondering if there's any reason for MIN_RATE being capped to 32000 [inside makemhr](https://github.com/kcat/openal-soft/blob/master/utils/makemhr/makemhr.h#L34)? A lot of titles use audio with sample rates lower than that, [seen some people](https://forums.nexusmods.com/index.php?/topic/5002815-true-3d-sound-for-headphones/page-20#entry44131760) modding the code to lower the MIN_RATE to help support those games, but could lowering it that way be incorrect somehow?

If lowering it would be fine, it might be nice if it could be changed in the main codebase here, instead of people needing to modify & build it themselves - maybe changing to 8000 like that linked NexusMods post mentioned would be a better limit.

**Comment by kcat** [comment]
The makemhr `MIN_RATE` dictates the acceptable range of the HRTF data set's sample rate. And the HRTF data set sample rate relates to the device output sample rate, not the individual sounds. So a game having sounds at 8000 doesn't really matter if the device output is 44100 or 48000.

When mixing, OpenAL Soft first resamples the sound to match the device output (which it has to, otherwise it will play at the wrong speed and pitch), then applies HRTF. So if your device sample rate is 48000 (very typical, along side 44100), an 8000 or 16000 or 22050 sound will first be resampled to 48000, then the HRTF is applied to that 48000 resampled sound regardless of what the original rate was. Consequently, there's no practical reason to resample the HRTF to even 32000, let alone less, since the device most likely isn't running that low. But even if you do have a device playing at 32000 or less, OpenAL Soft will automatically resample the HRTF to match the device rate when loading it (older versions didn't do this, so you had to make the HRTF match your device rate ahead of time, but newer versions do so you don't anymore). So even then, if you have an HRTF data set at 48000 and are using 22050/24000 output, that's properly handled.

As for why the limit is there at all, a FIR filter like HRTF can only work on the frequencies its samples can represent. If the HRTF sample rate is 32000, it can only apply to frequencies up to 16khz (the nyquist frequency). If resampled back up to 48000 to match the device, when applied to a 48000 sound all frequencies above 16khz are silenced. Since HRTF's purpose is to create a auditory sense of space for the sound, and the brain relies on higher frequencies to localize a sound, data sets that are less than 32khz start becoming unsuitable at doing that.

**Comment by emoose** [comment]
Ah thanks for the reply, had a feeling there might have been a reason for it.

The reason I asked about it was due to another DLL that makes use of the MHR files from here to add HRTF (https://github.com/kosumosu/x3daudio1_7_hrtf), which gave some error messages when audio played at a sample rate that it didn't have MHR data for, but now I'd guess that means it probably doesn't resample the audio first before applying HRTF as OpenAL Soft does.

Will have to try asking that project about adding support for it, or maybe see if the games audio files themselves can be resampled.
