### ISSUE TITLE
Cannot disable PipeWire backend when building

### ISSUE THREAD

**Issue by shinchiro** [kcat/openal-soft#624]
On system which has pipewire installed, passing `-DALSOFT_REQUIRE_PIPEWIRE=OFF ` still make the pipewire codes compile

**Comment by kcat** [comment]
`ALSOFT_REQUIRE_PIPEWIRE` is the option to require PipeWire. With it off, it will still try to enable it, it just won't fail if it can't. You want to set `-DALSOFT_BACKEND_PIPEWIRE=OFF` to ensure it's disabled at compile-time. Though you normally shouldn't do that since the PipeWire backend will only be used if the client library exists at runtime (all backends, except SDL and WinMM, are soft dependencies; OpenAL Soft will try to load the corresponding library dynamically, so even if it's built with PipeWire support, it won't require `libpipewire-0.3.so.0` at runtime and will just skip the backend if it's unavailable).

**Comment by shinchiro** [comment]
Thank you for info
