### ISSUE TITLE
pipewire backend doesn't seem to set realtime priority

### ISSUE THREAD

**Issue by v-fox** [kcat/openal-soft#630]
If I use `mpv --ao=openal` or [`strawberry`](https://github.com/strawberrymusicplayer/strawberry/) with openal backend checking with `chrt -a -v -p $(pidof <app>)` or in `journalctl --no-hostname -b 0 -e -u rtkit-daemon` doesn't show any rt threads.

At the same time, using pulse backend in openal results in SCHED_RR priority=1 regardless of an actual settings.
Using jack backend results in SCHED_FIFO=35 which is setting from ~/.config/pipewire/jack.conf

~/.alsoftrc has `rt-prio = 12` setting but in neither case it is respected.

**Comment by kcat** [comment]
OpenAL Soft tells PipeWire to run the audio process callback on the RT thread, which as far as I can tell, is managed internally by the PipeWire client library. I don't know why `chrt` doesn't show any real-time threads; maybe there's a bug in PipeWire that's failing to set RT priority on the RT thread, or something's interfering that's preventing RT processing (PipeWire isn't doing resampling to it, and it shouldn't be getting remixed), or it's handled another way that `chrt` doesn't show. But I don't see anything in the docs about the caller needing to do anything to get RT priority on the RT thread, and I don't know how to check if/why `PW_STREAM_FLAG_RT_PROCESS` isn't honored.

**Comment by v-fox** [comment]
The only other "native" PW client I know is pulseeffects/[easyeffects](https://github.com/wwmm/easyeffects) but I can't test now if it has any rt threads. The fact, that openal doesn't get right rt priority on both jack and pulse backends under both native jackd & pulseuadio as well as PW's emulations, does imply there is something wrong. Although, getting priority from jack.conf rather than ~/.alsoftrc is likely correct. Certainly not RR=1, though.

But I wouldn't know for a fact, you better test it out yourself with proper debugging. easyeffects code might be a useful example. Try something that creates audible xruns without realtime on any backend and compare how it behaves with pulse/jack/pipewire backends when realtime is properly configured in the system. You can see "error" count in `pw-top` per node (such as mpv using openal) but I'm not sure that all errors are xruns.

I have some errors counted but it seems stable and without xruns. The weird part is that it seems like `period_size` sets the size of entire buffer and `periods` does nothing with PW backend. Would be nice to be able to change default 20ms buffer arbitrarily to avoid hardcoding period size that is tied to rate.

**Comment by kcat** [comment]
When it comes to using RT mixing, OpenAL Soft doesn't get to say how big the period size is. It can (and does) suggest a preferred update size given the setting (through the `PW_KEY_NODE_LATENCY` property, which is the desired quantum/update size), but for RT processing, the PipeWire (or JACK for that matter) server runs the device with a set update size depending on the running apps' needs. When the hardware needs audio, the server gets a hardware interrupt and invokes the RT callbacks to get the audio mixed onto the card with no additional latency, beyond what the hardware has remaining while the callbacks are running. At most, the audio server could give an application a buffer of some multiple N of the update size, and call the app's callback every Nth update, but that's something for the server to do (and there are risks, since using the RT callback to generate N times as many samples than the update needs can cause underruns).

There isn't an easy or reliable way to purposely generate underruns for a non-RT thread which an RT thread could handle fine. That's highly dependent on the amount of work the CPU can do and the amount of load the CPU is under when the update is run. There's no way to know for sure 'a non-RT thread couldn't have handled this' or 'an RT thread could've handled this'. Especially since PipeWire adjusts the stream latency to avoid underruns with non-RT processing (on the assumption it's more likely to run late).

**Comment by etircopyh** [comment]
> The only other "native" PW client I know is pulseeffects/easyeffects

There's also [Mumble](https://github.com/mumble-voip/mumble) (not in release yet), SDL, [JamesDSP](https://github.com/Audio4Linux/JDSP4Linux). Guess there is something else...

**Comment by ishitatsuyuki** [comment]
I stumbled upon this issue while debugging easyeffects xruns. Turns out we have been all doing it wrong.

In the current versions of pipewire, you need to ensure `client-rt.conf` is loaded or your client would not get any realtime scheduling treatment at all. I filed an issue [upstream](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2024) here.

An workaround (or intended way to call the API, per PipeWire devs) is to initialize the context like [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/7c6649b5e57ffeea179cb896102bc051f89b7d4f/pipewire-alsa/alsa-plugins/pcm_pipewire.c#L1069).

**Comment by kcat** [comment]
This should be fixed with commit 561f50b3a35d8d502b731546f0cf0c09d4e705b2.

**Comment by v-fox** [comment]
> This should be fixed with commit https://github.com/kcat/openal-soft/commit/561f50b3a35d8d502b731546f0cf0c09d4e705b2.

Yep.
