### ISSUE TITLE
OpenAL Soft 1.21.1 breaks the reverb effect in Serious Sam Classic

### ISSUE THREAD

**Issue by Kappa971** [kcat/openal-soft#631]
The following problem is described here: https://github.com/kcat/dsoal/issues/33

The reverb effect works up to OpenAL Soft 1.21.0

**Comment by mirh** [comment]
This sounds like something it'd be great to bisect...
https://github.com/kcat/openal-soft/compare/1.21.0...1.21.1

**Comment by Kappa971** [comment]
Find out which of these commits caused the issue. Unfortunately I can't compile OpenAL Soft with Visual Studio + vcpkg (it's very easy to switch between commits), I haven't found a guide about it.

**Comment by Kappa971** [comment]
It doesn't work with MINGW either. I was able to branch from a commit but I'm getting errors while compiling. 
According to the guide on the OpenAL Soft site, it would be enough to move to build/ and run `cmake ..` then run `make` to build it.

**Comment by kcat** [comment]
What errors? OpenAL Soft is building for me with MinGW-w64 (32-bit target).

**Comment by Kappa971** [comment]
Could you tell me exactly the steps to build an OpenAL Soft build? Do I need to install any dependencies? Thanks.

**Comment by Kappa971** [comment]
I built OpenAL Soft with the latest commit and it seems that the problem is solved.
However, the OpenAL32.dll file is about 24mb in size and requires three dlls.

**Comment by kcat** [comment]
Make Sure to build in Release mode (instead of the default RelWithDebInfo, which increases the size quite a bit because of debug info), and have the `ALSOFT_STATIC_LIBGCC`, `ALSOFT_STATIC_STDCXX`, and `ALSOFT_STATIC_WINPTHREAD` CMake config options enabled. You can then also run `strip` on the resulting DLL if you want to reduce the size a bit more.

**Comment by Kappa971** [comment]
Thanks so much. It would be useful to add this information to the official site. I think it can close the issue.

**Comment by mirh** [comment]
This issue was actually about the serious sam regression, not building?

**Comment by Kappa971** [comment]
The released build of OpenAL Soft 1.21.1 broke the reverb in Serious Sam. Compiling from source with the latest commits, it appears that the problem has been indirectly resolved.

**Comment by Matthaiks** [comment]
The reverb effect in Serious Sam seems to be broken again as of this commit: 01521b684998c43a7bd4d062af9858961379fecb

**Comment by kcat** [comment]
> The reverb effect in Serious Sam seems to be broken again as of this commit: [01521b6](https://github.com/kcat/openal-soft/commit/01521b684998c43a7bd4d062af9858961379fecb)

Does it work with commit c7da1696a4c15910f6b7240ae7cbfc44114bef06?

**Comment by Matthaiks** [comment]
> Does it work with commit [c7da169](https://github.com/kcat/openal-soft/commit/c7da1696a4c15910f6b7240ae7cbfc44114bef06)?

I'm unable to test it. No workflow files for this commit.

> EDIT: Also, try now with commit [4c89d76](https://github.com/kcat/openal-soft/commit/4c89d76ec30d89deeb83aa1eac1d99c7397ac8a1).

Still broken.

**Comment by Matthaiks** [comment]
Yes, it does work with https://github.com/kcat/openal-soft/commit/64ead7d36de7dc748414530121b69876a0c84e05.

**Comment by kcat** [comment]
So it broke somewhere in 1e226fd54dc6670222ce1210cf55fe1b4d61e89c...01521b684998c43a7bd4d062af9858961379fecb. Of those, the only commits that could have an influence here that I see would be

1e226fd54dc6670222ce1210cf55fe1b4d61e89c - "Don't commit EAX updates in applyAllUpdates" (this makes it so `alcProcessContext` doesn't force deferred EAX properties to be committed).

20ab7645fb637e427d31f044fa1a05f683595f58 - "Don't set a default EAX version for fx slots" (this makes it so an effect doesn't automatically start processing until the app sets and commits a property on the effect).

If I were to take a wild guess, it would more likely be 1e226fd54dc6670222ce1210cf55fe1b4d61e89c. If the app suspends OpenAL property updates with `alcSuspectContext`, and supplies EAX changes with the deferred flag, it might expect calling `alcProcessContext` to commit the deferred EAX properties and apply them along with other pending OpenAL updates.

That would be kind of annoying since it would increase the CPU cost of `alcProcessContext` without some additional EAX state tracking, and be a potential problem for DSOAL committing deferred updates correctly (if a non-deferred `EAXSet` call fails, I don't think it should commit previously deferred properties, but DSOAL needs to call `alcSuspendContext` before calling that with a non-deferred property so all deferred properties update at once; but if `EAXSet` fails, `alcProcessContext` still needs to be called, causing previously deferred properties to be committed despite a failed call). I can't say I expect a dsound app to depend on the behavior of a failed non-deferred EAX property after setting deferred properties, but stranger things have happened.

**Comment by kcat** [comment]
Try now with commit ef5373611fb0411be0e29c463f0e525481011eb0. The [workflow builds](https://github.com/kcat/openal-soft/actions/runs/4435661352) should be available soon.

**Comment by Matthaiks** [comment]
The reverb is back. 👍
