### ISSUE TITLE
ALC_ENUMERATION_EXT OpenAL Soft default device (maybe fixed)

### ISSUE THREAD

**Issue by Kappa971** [kcat/openal-soft#650]
Hi, I know this problem has been discussed above, but this hasn't led to a solution.
The main problem is that Creative's OpenAL32.dll router will never choose "OpenAL Soft" as the default device in ALC_ENUMERATION_EXT but always "Generic Software". This is a problem for almost all old games that use OpenAL, as they don't allow you to choose the OpenAL device to use, but use the one indicated by the Creative's router.

I noticed that Host OpenAL (Creative's deprecated official OpenAL driver for cards without hardware acceleration) sets the device name to the Windows default audio device name, in my case "Altoparlanti (Sound Blaster Z)" as the system is set in Italian (would be "Speakers (Sound Blaster Z)"): 
![hostOpenal](https://user-images.githubusercontent.com/62349018/151831716-19556ffa-b886-423b-9987-b651eeee8d3f.png)

I started doing some tests by changing `constexpr ALCchar alcDefaultName [] = "OpenAL Soft\0";`. I manually changed OpenAL Soft's `alcDefaultName` variable from "OpenAL Soft" to "Altoparlanti (Sound Blaster Z)", and in this case the device is set as default by the Creative's router:
![scr1](https://user-images.githubusercontent.com/62349018/151808265-970ec597-cc3c-45df-96cf-b2f9ea10da38.png)

I did the same test in another PC with Realtek sound card, manually changing `alcDefaultName` to "Altoparlanti (Realtek High Definition Audio)" and it works:
![scr4](https://user-images.githubusercontent.com/62349018/151808688-39983b61-eafa-48ba-afd5-71cae9a5d907.jpg)

According to other tests, it appears that Creative's router will only recognize OpenAL Soft as the default device in ALC_ENUMERATION_EXT, if the device name **exactly** matches the Windows default audio device name. For example, "OpenAL Soft on Altoparlanti (Sound Blaster Z)" or "Speakers (Sound Blaster Z)" (with Windows localized in Italian) will not work, but "Altoparlanti (Sound Blaster Z)", in my case, will work because it is the same as the Windows default audio device name.

I have no idea how to do this, but I guess the `alcDefaultName` variable can be set automatically with the Windows device name instead of "OpenAL Soft".

EDIT
Creative's OpenAL32.dll router also seems to recognize "Generic Hardware" as a device name, setting it as the default:
![scr](https://user-images.githubusercontent.com/62349018/151969127-b30f9278-b200-4c7a-9cc6-98ab876d60a6.png)
In this case it would be enough to modify the line `constexpr ALCchar alcDefaultName [] = "OpenAL Soft\0";` to `constexpr ALCchar alcDefaultName [] = "Generic Hardware\0";`

**Comment by Kappa971** [comment]
Anyway, if this doesn't interest anyone or just changing the device name breaks something else, I can close the issue. 
It will mean that I will modify the string at my own risk.

**Comment by mirh** [comment]
This was already discussed in #574. 
The thing is.. I just tried to hex edit the latest openal-soft dll to have it report "Audigy X-Fi" as a name (would you believe OpenAL Soft is just as many characters long?) and it didn't work. 

After some extra headbanging I finally cracked the enigma. 
https://github.com/rpavlik/openal-svn-mirror/commit/217ff4f3cd52973acaf6bffcc91d6b49cafa415c
https://github.com/rpavlik/openal-svn-mirror/commit/479a86c1bbb20208ba693fe907d834d40a74352a
https://github.com/rpavlik/openal-svn-mirror/blob/trunk%401478/OpenAL-Windows/Router/alc.cpp#L1856
https://github.com/rpavlik/openal-svn-mirror/blob/ba975e38049a82ed8cc28c4ba95f1eb2bc9101f4/OpenAL-Windows/Alc/ALc.c#L151

You need both your openal driver AND your [audio device](https://winaero.com/rename-audio-device-windows-10/) to have "Audigy" or "X-Fi" in their name. 
Once you oblige, partial match search is unlocked, and every game ever finally starts to pickup on openal-soft out of the box. 
I'd like to propose a new ALSOFT_NAME variable, so that this becomes a cakewalk to address.
