### ISSUE TITLE
On MS Windows, Application cant find soft_oal.dll if placed inside directory that contained non ANSI character.

### ISSUE THREAD

**Issue by xannagan** [kcat/openal-soft#655]
Using precompile windows binary version 1.21.1,Not sure if this is an intended behavior.

But If I placed soft_oal.dll inside my application folder that contain non ANSI character (such as thai or japanese),
Calling alcOpenDevice("OpenAL Soft") will failed to find the dll and will hang up the application when exit.

With this behavior,It impossible to provide the dll in a portable manner with out the user have to install OpenAL Soft him self.

Using precompile windows binary version 1.21.1 on Windows 11 64bit
My application is compiled with WideChar UTF-16.

**Comment by kcat** [comment]
Are you using Creative's router DLL? That may have problems with non-ANSI paths, though it's a bit surprising since the code looked Unicode-aware.

As a workaround, you can rename `soft_oal.dll` to `OpenAL32.dll` and put it next to the executable to have your application use OpenAL Soft directly and avoid the buggy router. Unless you need or want the router, in which case you can try to use OpenAL Soft's router instead of Creative's, though you will need to compile it yourself since it's not part of the current binary releases.

**Comment by xannagan** [comment]
Thank for your fast response.

Rename the dll as suggested fixed non-ANSI path problem.

But it introduced some side-effect if the system already has Creative's OpenAL32.dll.

When launch program from Visual Studio , If the system already has Creative's OpenAL32.dll installed in system folder.
It will always tried to load that dll first instead of the renamed one in application folder,
Result in error when try to directly open device with specific 'openal soft' parameter.

May be VS preload the system wide dll for debugging/crash report purpose.
This only affect compiling/developing process and not when running exe in retail environment.

Using alcOpenDevice(NULL) is enought to initialize the correct OpenAL32.dll in this case (Installed Creative's when running in VS / renamed oal_soft.dll one when running in retail).
