### ISSUE TITLE
Make error - Linux CentOS

### ISSUE THREAD

**Issue by nv-piyush** [kcat/openal-soft#656]
Hi,

I am setting up openAL on linux CentOS machine, getting this error when building it:

![152294030-e2050446-5b93-409c-83ce-49efbb3edd22](https://user-images.githubusercontent.com/40065258/152294424-1896385a-f96b-4fee-87fe-7cff4c2aad40.png)

I have followed these steps,

```
git clone https://github.com/kcat/openal-soft.git
cd openal-soft 
cd build
cmake ..
make
```

Please let me know if I am missing anything

**Comment by kcat** [comment]
What compiler and compiler version you have? It seems to not like `'` in numeric literals, and doesn't have `std::remove_cv_t`, both of which are standard C++14. GCC 5 and later should support it.

**Comment by nv-piyush** [comment]
Thank you for your quick response.
```
>gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
```
Yes, it has older GCC version. Is there any alternative possible?

**Comment by kcat** [comment]
Updating to GCC 5 or newer would be my suggestion, if possible. 9 year old development software[1] isn't likely to work well with modern code. Otherwise, you'll need to go with 1.20.1, which only needs C++11 and should build with GCC 4.8.

[1] GCC 4.8.5 may have been released in June 2015, but that's only a bugfix release and doesn't improve standards compliance or add features over the original 4.8.0 release, which was March 2013.

**Comment by nv-piyush** [comment]
okay, will update it. Thanks!
