### ISSUE TITLE
`error: 'PW_KEY_CONFIG_NAME' was not declared in this scope; did you mean 'PW_KEY_CORE_NAME'?` and other build errors

### ISSUE THREAD

**Issue by ndarilek** [kcat/openal-soft#691]
Hello,

I'm attempting to build 1.22.0 in a Docker container in CI--specifically the `rust:bullseye` image. In doing so, I get a bunch of errors like:"

error: 'PW_KEY_CONFIG_NAME' was not declared in this scope; did you mean 'PW_KEY_CORE_NAME'?
error: 'PW_KEY_NODE_RATE' was not declared in this scope; did you mean 'PW_KEY_NODE_NAME'?

cmake claims it is looking for Pipewire 0.3, which is what I'm installing. Is it possible that this either isn't compatible with 0.3, or that a breaking change was introduced after whatever Bullseye ships?

If you use Docker, here's a Dockerfile that triggers this build failure:

```
FROM rust:bullseye
RUN apt-get update && \
  apt-get install -y llvm-dev libclang-dev clang pkg-config  libasound2-dev libpulse-dev libpipewire-0.3-dev libdbus-1-dev cmake wget && \
  wget https://openal-soft.org/openal-releases/openal-soft-1.22.0.tar.bz2 && \
  tar xfj openal-soft* && \
  cd openal-soft-1.22.0/build && \
  cmake ../ && \
  make
```

Thanks.

**Comment by kcat** [comment]
It may need a newer versions of PipeWire, though I'm not exactly sure which version since the headers don't mention when they were added. I'm not sure if it would be worth to build the PipeWire backend for Bullseye since it has such an old version (0.3.19; I started using it around 0.3.23, and it's now at 0.3.50). Unless you expect a build for that to run on newer systems, then I could probably add a workaround.

**Comment by ndarilek** [comment]
Hmm, I wonder if it might be wise to add a minimum version check? I mistakenly assumed semver compliance when I shouldn't have.

In any case, I may just build a Linux library and commit the binary directly. I had no idea this was yet another long string of backwards-compatibility-breaking minor versions on Pipewire's part. :)

Thanks.

**Comment by kcat** [comment]
> Hmm, I wonder if it might be wise to add a minimum version check? I mistakenly assumed semver compliance when I shouldn't have.

I'll need to try and find out when those macros were added. Or add some arbitrary minimum version that I know should have it.

> In any case, I may just build a Linux library and commit the binary directly. I had no idea this was yet another long string of backwards-compatibility-breaking minor versions on Pipewire's part. :)

More of a forwards-compatibility break. Older code written for versions before the change still compiles and works with newer versions, but newer code written for versions after the change may not compile and work with older versions. Most code falls prey to this kind of thing. I simply didn't know there was a minimum 0.3 version for these macros, I mistakenly assumed they've been there since the initial 0.3 release, and the header doesn't say when they were added.

**Comment by kcat** [comment]
There is now a required minimum version of 0.3.23, with commit 22e6c0df6017aa86e2cd83d8073e4d490c55dd11. If this isn't high enough, or if you know a better/lower minimum version that still builds, let me know and I can adjust it.
