### ISSUE TITLE
First 10ms of audio distorted.

### ISSUE THREAD

**Issue by oomek** [kcat/openal-soft#702]
I've recently discovered that OpenAL does some weird distortion and wanna-be fade-in on starting the playback.
Here's an example showing the original waveform and recorded waveform from the test app.

![image](https://user-images.githubusercontent.com/2974860/167740190-2147bb6f-4795-4f42-b95f-ef7648bad09c.png)

![image](https://user-images.githubusercontent.com/2974860/167740210-34f0638d-9748-4198-aa42-605a864a884b.png)

Could you tell me whether this is this a bug or a feature? If it's the later how can I disable it?
This distortion and fade-in doesn't sound good because it destroys transients of short UI samples.

**Comment by kcat** [comment]
Individual sounds fade in when made to start at a non-0 offset, to avoid a click or pop from starting with a large amplitude in the middle of a sound. It shouldn't fade in when starting at the beginning. It also shouldn't look nearly so jagged and spiky, it should be a smooth linear fade in.

Does this happen for any sound your start at any point with the device open, or only at the very beginning of device playback? That it happens over 10ms instead of OpenAL Soft's default 20ms update period, and it has this jagged pattern when OpenAL Soft's fades should be smooth, would suggest a compressor/limiter at the system level, although that would only be the case at the start of playback and not when starting individual sounds.

**Comment by oomek** [comment]
> Does this happen for any sound you start at any point with the device open, or only at the very beginning of device playback?

It happens on the initial playback of every sound I tested and on every playback of the streamed sounds.

> That it happens over 10ms instead of OpenAL Soft's default 20ms update period, and it has this jagged pattern when OpenAL 
Soft's fades should be smooth, would suggest a compressor/limiter at the system level, although that would only be the case at the start of playback and not when starting individual sounds.

I was suspecting some system post-processing, but even when another long sound is playing in the background this jagged fade-in also occurs.

> What OS are you on, and can you provide a trace log (set the `ALSOFT_LOGLEVEL` environment variable to `3` and it'll print a log to stderr).

I'm unable to produce a log on windows for some reason. only on Raspbian and Arch Linux where surprisingly this problem does not occur.

**Comment by kcat** [comment]
I'm unable to replicate the issue here on Linux. Although, since you mention it doesn't happen for you on Linux either or Raspian, only on Windows where you're also not able to create a log, that makes me think it's not using OpenAL Soft.

Can you check the device name from the OpenAL device to see what it opened? If it's just a device name and doesn't have "OpenAL Soft", that would be Creative's hardware driver. If it has "Generic Software" or "Generic Hardware", that would be Creative's wrapper driver, and Generic Hardware is more specifically using DirectSound3D to do the mixing. Any of those could be doing the fade-in like that when starting sounds, which would also explain why it's jagged over 10ms.

**Comment by oomek** [comment]
Do you mean ALC_DEVICE_SPECIFIER?
on Windows I see: `Generic Software on Speakers (Focusrite Usb Audio)`
On RPI: `Built-In Audio Analog Stereo`

The libs I link against in SFML are from here:
https://github.com/SFML/SFML/tree/master/extlibs/libs-mingw/x64

**Comment by oomek** [comment]
Ok, I solved this and it's a bit embarrasing.
I assumed alsoft is statically linked.
After adding openal32.dll to the app folder the issue on Windows disappeared.

```
Version: 1.1
Vendor: Creative Labs Inc.
Renderer: Software
```

with dll:
```
Version: 1.1 ALSOFT 1.18.1
Vendor: OpenAL Community
Renderer: OpenAL Soft
```
