### ISSUE TITLE
Minecraft surround sound

### ISSUE THREAD

**Issue by Uncraftbar** [kcat/openal-soft#723]
I dont know if this is the right place for this but i cant find anything.
How do i enable 5.1 surround in Minecraft.
Im using toslink with dolby digital live and the newest version of minecraft (1.19)

**Comment by kcat** [comment]
What OS are you using, and how is the device configured? Normally OpenAL Soft should detect what the device is configured for in the system and set an output to match, although depending on the system there may be room to tweak the output.

**Comment by Uncraftbar** [comment]
> What OS are you using, and how is the device configured? Normally OpenAL Soft should detect what the device is configured for in the system and set an output to match, although depending on the system there may be room to tweak the output.

Im using Windows 10. Its configured through the normal windows soundsetting with dolby digital live.
My av is quite old so it doesnt have hdmi so i use toslink from my mainboard

**Comment by kcat** [comment]
I mean, is it configured for 5.1 Surround, Stereo, or something else in Windows' sound settings for the device?

**Comment by Uncraftbar** [comment]
Its using dolby Digital live and thats 5.1 So it just takes 5.1 and transfers it into dolby Digital

**Comment by kcat** [comment]
Usually OpenAL Soft should detect the device configuration from the system and use it without any extra set up necessary. If it's not, or if there's something weird about the configuration, I'd normally ask for a trace log. But since Minecraft is a Java app, I think it restricts file I/O which prevents OpenAL Soft from producing a log file. You can try setting the `ALSOFT_LOGLEVEL` environment variable to `3` and `ALSOFT_LOGFILE` to some fullpath+filename where it has write permissions to make a log file, then if it does produce the given file after running Minecraft, that would be useful to tell what it's detecting and subsequently doing.

**Comment by Uncraftbar** [comment]
Okay gonna try if that doesnt work what are other games that use OpenAL soft so i can try if it works there

**Comment by Uncraftbar** [comment]
Where can i set the variables? im a little bit confused

**Comment by Uncraftbar** [comment]
OK wow i tried it now and i have no idea why but it works now sorry for wasting your time but thanks for the help
