### ISSUE TITLE
[Feature Request] EVGA Nu Audio control for Linux

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#728]
so i have an EVGA NU Audio Card (yes a sound card in 2022, deal with it!)   and currently everytime i want to switch from my headphone output to the aux output or visa versa, i have to boot into windows to switch this one setting and then reboot back to Linux and it's such a pain, hopefully this is possible to do, i dont leave both on because then volume goes lower

**Comment by kcat** [comment]
OpenAL Soft handles the devices as reported by the system. Typically ALSA, PulseAudio, or PipeWire. If the system isn't reporting an output, OpenAL can't select it. I don't know how the device works, whether the switching is handled at the kernel/driver level or if it can be controlled from userland, but it seems like something ALSA would handle. Your best bet is likely to ask the PipeWire or PulseAudio devs if they have an option to switch the device's outputs, and if not, if ALSA provides the capabilities for them to add the option. Otherwise, you'd have to ask the ALSA devs directly if there's a way to switch that device's outputs.

**Comment by TheBestKmanEver** [comment]
the settings can be changed in the EVGA drivers and these settings are saved to the card itself which then has my output swapped from the headphone port to the AUX out (separate RCA), boot back into linux and these settings are applied to the card

**Comment by kcat** [comment]
This isn't really something for OpenAL Soft to deal with. You're better off asking the ALSA, PulseAudio, and/or PipeWire devs for this kind of control of the device's features. I don't know what they'll need to know.
