### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by xanather** [kcat/openal-soft#73]
On windows I am getting a memory leak from the allocation on this line

https://github.com/kcat/openal-soft/blob/master/Alc/backends/mmdevapi.c#L1143

**Comment by kcat** [comment]
What tool are you using to detect the leak? I'm not sure if there really is one, since [```althrd_create```](https://github.com/kcat/openal-soft/blob/master/common/threads.c#L129) only makes two allocations at most, which are accounted for. First, a container to hold the function to call and its parameter, so it can be passed to ```CreateThread``` with a proper starter function (the callback Windows wants isn't necessarily the same as ```althrd_start_t```), however that's freed if the thread creation fails or in the starter function if it succeeds. For that to leak, ```CreateThread``` would have to return success but never actually run the callback (which would also mean you don't get any sound without the mixer callback).

The second (potential) allocation is for the uint:ptr map, so it can map the returned thread ID (which is given back as the ```althrd_t``` object)  with the returned thread handle. However, a global function pointer is placed in the ```".CRT$XLC"``` section, which should be called by the C runtime when the lib unloads (which will always be at process exit, as the lib is pinned), to clear/free the map. Depending on what you're using, it may report the leak before this callback is given a chance to run.

Can you provide a bit more information about what/where the leak actually is?

**Comment by xanather** [comment]
I am using visual studio debugger and setting

`_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);`

In the program's wWinMain entry point.

These are the leaks that are shown when the program ends normally.

> Detected memory leaks!
> Dumping objects ->
> {21497} normal block at 0x02EB31D8, 32 bytes long.
>  Data: <                > C8 08 00 00 A0 03 00 00 CD CD CD CD CD CD CD CD 
> {60} normal block at 0x006BA188, 32 bytes long.
>  Data: <      #Q        > 1C 00 00 00 00 18 23 51 CD CD CD CD CD CD CD CD 
> Object dump complete.
> The program '[6880] warden.exe' has exited with code 0 (0x0).

I have not figured out what the 60th allocation leak is (it occurs before the entry point starts). These leaks only started appearing when I started compiling with OpenAL Soft (OpenAL32.dll) as a dependency.

By calling _CrtSetBreakAlloc(21497) in the entry point the debugger encounted a break point on the line I linked above.

I am trying to also figure out the source of _CrtSetBreakAlloc(60) though as I said at the moment I have not figured out a way to do this since _CrtSetBreakAlloc is called after the 60th allocation has already occured (while the libraries are being loaded I assume).

Note that the 21497th allocation only occurs if I use the OpenAL API, if I don't for the duration of the program it does not show. The 60th allocation always shows.

I will make another issue if I figure out the source of the 60th allocation.

**Comment by kcat** [comment]
The 60th allocation is likely
https://github.com/kcat/openal-soft/blob/master/Alc/ALc.c#L871
where it allocates space for a uint:ptr map entry during DllMain, to hold the TLS ID and associated thread-exit callback. The 21497th allocation is also for a uint:ptr map (a different one) where it stores the IDs and HANDLEs for threads. The "leaks" are reported due to the same cause, though: they're cleaned up in ```.CRT$XL?``` section callbacks, apparently after ```_CRTDBG_LEAK_CHECK_DF``` does its report. It seems a similar issue affects C++ static global classes:
https://stackoverflow.com/questions/10299995/vs2010-reports-false-memory-leaks-for-static-classes-in-a-dll

The odd thing is, there are other allocations that happen too, which are cleaned up by ```DllMain```. They aren't reported as leaks from what you've shown though, even though the CRT callbacks should be called in the same context as ```DllMain```. Makes me wonder if those callbacks aren't being called (I know they are for MinGW builds, but I've never personally made/tested an MSVC build).

**Comment by xanather** [comment]
So you think I shouldn't worry about these leaks? Anyway to check if the callbacks are being called, I can set breakpoints wherever.

**Comment by kcat** [comment]
I'm not sure if this is relevant anymore with the switch to C++. Threads and TLS all use the standard interfaces, so there's nothing really for OpenAL Soft to clean up for them anymore. If you're able to check if there's still any leaks I can take a look at them, but if not I think this can be closed.
