### ISSUE TITLE
AL lib:(EE) ALCplaybackAlse_open:Could not open playback device'XXXX':Device or resource busy

### ISSUE THREAD

**Issue by Zonginus** [kcat/openal-soft#744]
HI,there!
I can use OPENAL to collect audio data, but I encountered this error when playing：
[AL lib:(EE) ALCplaybackAlse_open:Could not open playback device'plughw:CARD=INTEL,DEV=0':Device or resource busy]

Is this problem caused by the same device I use to collect and play？

**Comment by kcat** [comment]
Depending on your hardware, the device may not be able to be opened multiple times at the same time. Most audio hardware these days depend on a software mixer to allow sharing the device. Are you not using PulseAudio, PipeWire, or something along those lines?

**Comment by foyego** [comment]
————————————————————————————————————————————————————————
0-CapDevName:ALSA Default
1-CapDevName:HDA Intel, ALC887-VD Analog (CARD=Intel,DEV=0)
2-CapDevName:HDA Intel, ALC887-VD Alt Analog (CARD=Intel,DEV=2)

play  number: 4
ALL AVAILABLE PLAY DEVICEs:
0-PlayDevName:ALSA Default
1-PlayDevName:HDA Intel, ALC887-VD Analog (CARD=Intel,DEV=0)
2-PlayDevName:HDA Intel, ALC887-VD Digital (CARD=Intel,DEV=1)
3-PlayDevName:HDA NVidia, ID 99 Digital (CARD=NVidia,DEV=3)

0-PlayDevName:ALSA Default

Load libopenal.so.1 success!
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'plughw:CARD=Intel,DEV=0': Device or resource busy
————————————————————————————————————————————————————————
There are only a few devices we can get. It may be a very old computer.For this error, should we disable this device or what should we do？
It would be great if you could answer us~！

**Comment by kcat** [comment]
That error is because you're trying to open an audio device that's in use by something else already. It's not normal to use ALSA directly since it's limited with sharing devices. Are you not using PulseAudio or PipeWire on your system?

**Comment by Zonginus** [comment]
I don't think PulseAudio  or PipeWire is installed in my system :(
If I can solve the problem by installing PulseAudio . I'm willing to try it~

**Comment by clort81** [comment]
Actually plenty of software manages to use concurrent alsa.   Only openal is unable to.

**Comment by kcat** [comment]
OpenAL can use concurrent ALSA. The default device with ALSA is `"default"`, like anything else. If you don't have PulseAudio or PipeWire or something, that is likely to be a dmix device that can mix audio from multiple apps.

For the discovered devices that you can select, OpenAL uses the `plughw:` prefix by default on those devices, which is likely to prevent concurrent use if the device doesn't support hardware mixing. That prefix can be changed in the config file (using the `device-prefix` and/or `capture-prefix` options in the `[alsa]` section) if you need something different on your system, for instance to `dmix:`, which allows it to be shared with other apps that are also using the dmix pcm device (though not if they use a different pcm device, even if it's a dmix type). If you're using a custom dmix pcm device, make sure it can take `CARD` and `DEV` parameters, and you can use that instead.

Alternatively, you can define custom OpenAL device names that map to specific ALSA device names, if you prefer using explicit per-device mappings instead of autodetected devices with generated pcm device names.

Yeah, this is annoyingly complicated, but that's ALSA for you.

**Comment by clort81** [comment]
That's a very good explanation kcat.
I also found your advice for custom devices in alsoft.conf
So i have setup custom devices and can better experiment
```
custom-devices = Custom1=hw:CARD=Loopback,DEV=0;Custom2=hw:CARD=Loopback,DEV=0;Custom3=dmix:CARD=Loopback,DEV=1;Custom4=dmix:CARD=Loopback,DEV=1;CustomDmix=dmixer 
```
Then my openal application gets all the custom devices listed: cool!

Among many other things, my .asoundrc has:
```
# software mixer for sound card
pcm.dmixer {
    type dmix
    ipc_key 1024
    ipc_perm 0666 # allow other users
    slave {
        pcm "snd_card"
        period_time 0
        period_size 1024
        buffer_size 4096
        # TODO what is right rate 96000
        rate 44099
        channels 2 # must match bindings
    }
    bindings {
        0 0
        1 1
    }
}
```
and i can write multiple instances to 'dmixer' device with
```
aplay -Ddmixer delme.wav
```
and hear sound from all of them.  

What's the canonical test client for openal?  Perhaps my application is the cause of my issue, by using openAL badly.

I'd like something like "alplay -Ddevice delme.wav"

Thanks sincerely, for making openal and being so kind as to chat.

**Comment by clort81** [comment]
The sample main.c helped me diagnose my problem.
I had a ~/.alsoftrc modified that i had forgotten about and it was overriding my device selection.
running strace ./openaltest 2>&1 |grep alsoft
showed me my problem.
...
the TL;DR for people, as kcat wrote: your alsa playback device either needs to support multiple stream mixing in hardware (better sound cards) or alsa will need to do the mixing in software (e.g. with 'dmix).
Or you use a frontend like jack or pulseaudio that will also do mixing of multiple sources.
For linux users, be aware that openal will look for and pull-in configuration options from 5 places, in this order

"/etc/openal/alsoft.conf"
"/etc/xdg/alsoft.conf"
"/home/$USER/.alsoftrc", O_RDONLY) = 3
"/home/$USER/.config/alsoft.conf"
"/$CWD/alsoft.conf"

cheers!
