### ISSUE TITLE
7.1 sound order question

### ISSUE THREAD

**Issue by nkrapivin** [kcat/openal-soft#746]
Hello.

I'm trying to port OpenAL-Soft to a platform (not linux based) that has it's own native low-level sound playback library.

It says that the 7.1 channel order is:
`L - R - C - LFE - L surround - R surround - L extend - R extend`
And there's also an option to use:
`L - R - C - LFE - L extend - R extend - L surround - R surround`.

What corresponds to `DevFmtX71` and what is `DevFmtX3D71` here? I can't quite understand.
OpenAL-Soft does `Aux0` / `Aux1` in X3D71, and `BackLeft` / `BackRight` but I don't understand what does this mean since I've never dealt with audio before.
I just want to be sure there's as less remixing overhead as possible.

Thanks to all maintainers who work on this awesome thing,
- Nik

**Comment by kcat** [comment]
For buffers and loopback device output, OpenAL Soft uses WaveFormatExtensible ordering. For 7.1 that's FrontLeft, FrontRight, FrontCenter, LFE, BackLeft, BackRight, SideLeft, SideRight. I'm guessing that corresponds to the second option you specified.

The `DevFmt*` enums don't dictate any particular channel ordering, that's up to the backend to detect from the system. If you're making a new backend, calling the `BackendBase::setDefaultWFXChannelOrder` method will set the channel order to match WaveFormatEx, while `BackendBase::setDefaultChannelOrder` sets the order to match what certain other systems use (both given what `mDevice->FmtChans` is set to at the time of the call). You can set whatever order you want by making new methods that follow the behavior of those functions.

The primary difference between `DevFmtX71` and `DevFmtX3D71` is that the latter uses `Aux0` and `Aux1` channel labels instead of `BackLeft` and `BackRight`. The backend still treats the device as plain 7.1, but internally the library uses `Aux*` labels to avoid matching `BackLeft` and `BackRight` input channels to `BackLeft` and `BackRight` outputs, since the physical speakers would not be in the normal places.

**Comment by nkrapivin** [comment]
Is there a docs entry on how `UpdateSize` and `BufferSize` work in ALSoft?
The platform's native library wants you to specify the "buffer granularity/grain" of the stream, minimum of `256`.
This means the buffer must be at least `GRAIN * CHANNELS * SIZEOF_int_OR_float` in size.
So if you have a float stereo device, your buffer must be at least `256 * 2 * 4` in size, and you must store floats inside that buffer.
If you have a short stereo device, it's `256 * 2 * 2`.
I'm trying to implement this myself:
```cpp
porttype = DevicePorts[indexInTable];

mFrequency = static_cast<uint>(freq);
mFmtChans = static_cast<DevFmtChannels>(alChanFmt);
mFmtType = static_cast<DevFmtType>(alDataFmt);
mUpdateSize = clampu(
	mDevice->UpdateSize,
	64 * 4, /* minimum allowed port 'granularity' */
	64 * 32 /* maximum allowed port 'granularity' */
);
mFrameSize = BytesFromDevFmt(mFmtType) * ChannelsFromDevFmt(mFmtChans, 0 /* we never use ambisonic in this case */);
mBuffer.resize(mUpdateSize * ChannelsFromDevFmt(mFmtChans, 0));
/* ^ mBuffer will store the actual samples data that will be sent over to the lib */
```

Is this correct?

**Comment by kcat** [comment]
> Is there a docs entry on how `UpdateSize` and `BufferSize` work in ALSoft?

`UpdateSize` is the number of sample frames per update. Also called the period size, it's the number of sample frames that will be played before the app is alerted to needing to write more samples. `BufferSize` is the total number of sample frames that the device can have queued while playing. For float stereo, 1 sample frame is `2 * 4` bytes.

When the `reset` method is called, `UpdateSize` and `BufferSize` can act as hints to what the actual output device update size and buffer should be. It's not required to match the output device to what those settings are, but when the output device is configured, `mDevice->UpdateSize` and `mDevice->BufferSize` should be updated to reflect what the output device is actually using. Same for the `mDevice->FmtChans`, `mDevice->FmtType`, and `mDevice->Frequency` fields. There is the `mDevice->Flags` bitfield with flags to indicate if it should try to configure the output device format to what those fields specify, or if it should ignore those fields and use some default, but in either case it's not required to match the format (it's far more important that the device ends up usable with any format the output can use) and the fields should be updated to what the output device is actually using once configured.

**Comment by nkrapivin** [comment]
> `UpdateSize` is the number of sample frames per update. Also called the period size, it's the number of sample frames that ....
> BufferSize is the total number of sample frames that the device can have queued while playing. For float stereo, 1 sample frame is 2 * 4 bytes.

But are they in bytes or samples?

**Comment by nkrapivin** [comment]
Nevermind, just realized it's all in samples.
Got this thing to run on a PlayStation 4: https://youtu.be/KgqQGrNnis4
Thanks again for this awesome lib, is it okay if I submit my backend as a PR?

**Comment by kcat** [comment]
> Thanks again for this awesome lib, is it okay if I submit my backend as a PR?

As long as there's no code that would be under NDA, that it's all derived from legal sources.
