### ISSUE TITLE
Reading of HRTF sofa files

### ISSUE THREAD

**Issue by hoene** [kcat/openal-soft#75]
The standard "AES69-2015: AES standard for file exchange - Spatial acoustic data file format" defines a file format for reading HRTF data set.

Program makehrtf does not understand SOFA but should.

I am working on it: https://github.com/choene/openal-soft/blob/master/utils/sofa/SOFAtoOpenAL.cpp

**Comment by hoene** [comment]
The reader libmsysfoa (https://github.com/hoene/libmysofa) is now part of Debian and Ubuntu releases...
Now, it should be much easier to add the SOFA format to the makehrtf converter...

**Comment by kcat** [comment]
Yes, I'm actually in discussions now with someone who helps me on makehrtf about using it. I have a question though, regarding ABI/API stability. Do you at all expect libmysofa to break API or ABI, as new features are added or altered? Can you guarantee that apps written now will still compile and behave properly with newer versions of the lib released years from now, or that an app built and linked against it now will still work without recompiling with new versions in the future? Or would it be better to maintain a local copy of the lib so that my code won't start failing when libmysofa updates, and static link so my apps won't break if the shared lib updates?

**Comment by hoene** [comment]
libmysofa is here to stay. It is part of my legacy.

Over the last year, the API has been very stable. It is not very likely to change anymore (beside some minor extensions). 

Currently, it is part of other projects such as VLC and ffmpeg. They will kill me, too, if I change anything.

**Comment by kcat** [comment]
makehrtf (now makemhr) supports reading SOFA files, so this is implemented.
