### ISSUE TITLE
Question: use alcDestroyContext while context is current in a different thread

### ISSUE THREAD

**Issue by maxbachmann** [kcat/openal-soft#764]
The documentation for `alcDestroyContext` mentions that the context should not be current and `alcMakeContextCurrent` should be used to enusre this. `alcMakeContextCurrent(NULL)` unsets both the global context and the thread local context. However the context might still be the active one in a different thread.

Is it enough to unset the context for the current thread and simply ensure the other threads are not calling openal while the destroyed context is set as thread local context?
As pseudo code I would like to do the following:

```
func thread1:
    context = get_context()
   alcSetThreadContext(context)
    //use openal
    while disabled:
        // another thread calls alcDestroyContext(context) in the meantime
        pass
    new_context = get_context()
    if context != new_context:
        alcSetThreadContext(new_context)
        context = new_context
   //use openal
```

looking at the implementation it appears to care only about the current thread right now: https://github.com/kcat/openal-soft/blob/ee3142d4d605eac7e7c5f6d4df87ec5e3b345d29/alc/context.cpp#L196-L201

**Comment by kcat** [comment]
> Is it enough to unset the context for the current thread and simply ensure the other threads are not calling openal while the destroyed context is set as thread local context?

Sort of. The main problem will be if the thread is destructed while a "destroyed" context is current on that thread. A reference is kept on the context while it's current on each thread, and "destroying" a context removes it from the list of valid contexts (so it won't be seen as valid if passed to another function call) and removes its primary reference, so that once its remaining references are released (any asynchronous call accessing it is finished, or is unset from being current on other threads), it'll auto-delete itself.

If a thread quits while a context is current on it, it'll remove that reference, however it's not safe to delete the context in a thread destructor callback since it can potentially call things that aren't allowed to be called there. So if the final reference is removed that way, the context won't be deleted and there'll be no more references, causing a leak. If a context is current on a thread when the thread is destroyed, it'll log an error to `stderr` (or the log file if one is set), and it'll report if it also caused a leak.

> looking at the implementation it appears to care only about the current thread right now:

A thread can only really look at its own thread-local current context. While it's technically possible to look at what's current on other threads, it's not really practical or safe to do anything about anyway.

**Comment by maxbachmann** [comment]
Do I understand  you correct that:
1) the context is not really destroyed until it has a reference count of 0 -> will not be really destroyed while threads still reference it
2) it is fine to have a "destroyed" context as current context in a thread as long as I call `alcSetThreadContext(NULL)` at some point before the thread is destructed (can't be done in the destructor of a thread local variable)

**Comment by kcat** [comment]
> the context is not really destroyed until it has a reference count of 0 (only removed from list of valid contexts) -> will not be really destroyed while threads still reference it

Essentially yes.

> it is fine to have a "destroyed" context as current context in a thread as long as I call `alcSetThreadContext(NULL)` at some point before the thread is destructed (can't be done in the destructor of a thread local variable)

Correct.

Ultimately, calling `alcDestroyContext` makes the given context invalid/unusable, there's no guarantee the context will remain current on other threads (a future version may be able to properly unset the other threads' context with that call). OpenAL Soft won't crash whether or not the "destroyed" context stays current on other threads, but the actual behavior is undefined; only thing you're allowed to do afterward on those threads is set a different context or NULL. Calling `alcSetThreadContext(NULL)` before the thread exits helps ensure OpenAL Soft can properly clean up, but you can't assume the context will still be set after `alcDestroyContext`.

**Comment by maxbachmann** [comment]
thanks for helping
