### ISSUE TITLE
alcReopenDeviceSOFT not properly exported from soft_oal.dll

### ISSUE THREAD

**Issue by zerppa** [kcat/openal-soft#769]
I'm using **soft_oal 1.22.2** from a C# app. For standard sound playback everything is working fine, but I then I tried to use `alcReopenDeviceSOFT` to handle device disconnects (such as unplugging headphones).

A simple (and dirty) way to define the DLL import would be something like this:

```csharp
// Define
[DllImport(Lib, EntryPoint = "alcResetDeviceSOFT")]
public static extern byte alcResetDeviceSOFT(IntPtr context, int* attrList);

// Use
if (ALC.alcResetDeviceSOFT(this.device, null) == ALC.TRUE)
{
}
```

The above code is for `alcResetDeviceSOFT` and it works. But when I attempt the same for `alcReopenDeviceSOFT`:

```csharp
[DllImport(Lib, EntryPoint = "alcReopenDeviceSOFT")]
public static extern byte alcReopenDeviceSOFT(IntPtr device, string deviceName, int* attrList);
```

I get:
> System.EntryPointNotFoundException: 'Unable to find an entry point named 'alcReopenDeviceSOFT' in DLL 'soft_oal'.'

Baffled, I opened the DLL in _Dependency Walker_ to list all of the exported functions. As expected, `alcResetDeviceSOFT` is listed but `alcReopenDeviceSOFT` is not.

Checking soft_oal sources, let's pick three sample definitions:
```cpp
// Correctly exported
ALC_API ALCboolean ALC_APIENTRY alcResetDeviceSOFT(ALCdevice *device, const ALCint *attribs);

// Correctly exported
FORCE_ALIGN ALC_API void ALC_APIENTRY alcRenderSamplesSOFT(ALCdevice *device, ALCvoid *buffer, ALCsizei samples);

// Not exported
FORCE_ALIGN ALCboolean ALC_APIENTRY alcReopenDeviceSOFT(ALCdevice *device, const ALCchar *deviceName, const ALCint *attribs);
```

Is `ALC_API` missing from the signature?

**Comment by kcat** [comment]
Not really. Extension functions are supposed to be accessed through `alcGetProcAddress` or `alGetProcAddress`, after making sure the extension is supported. They aren't supposed to be exported like normal functions, though I've been pretty careless about that in the past (and has created problems in the rare cases of extensions being removed, since the functions can't be removed without breaking apps). Only the more ubiquitous and fairly widely used extensions (like EFX) would make sense to have exported, as they're more likely to be standardized at some point in the future.

**Comment by zerppa** [comment]
Alright, thank you for the clarification.
I got it working via first getting the pointer and then invoking that.

`alcReopenDeviceSOFT` just seemed inconsistent with the other functions I found.
