### ISSUE TITLE
SOFA in MakeMHR: "Unsupported delay dimensions: M,R"

### ISSUE THREAD

**Issue by ThreeDeeJay** [kcat/openal-soft#774]
[EAC Individualized HRTF Synthesis](https://github.com/davircarvalho/Individualized_HRTF_Synthesis) was just [released as a standalone app](https://github.com/davircarvalho/Individualized_HRTF_Synthesis/releases/latest), so [generating personalized SOFAs](https://i.imgur.com/q6rRoLz.png) is now a lot easier.
However, I'm having trouble converting them to OpenAL Soft MHR using something like:
`makemhr.exe -r 44100 -i "EAC_44.1kHz.sofa" -o "EAC_44.1kHz-44100.mhr"`
If I use the makemhr from [openal-soft-1.22.2](https://openal-soft.org/openal-binaries/openal-soft-1.22.2-bin.zip) (latest stable release at the moment), I get this error:
```
Generating "EAC_44.1kHz-44100.mhr"
Using 2 threads.
Reading HRTF data from EAC_44.1kHz.sofa...
Unexpected delay attribute: _Netcdf4Coordinates = (null)
Unsupported delay dimensions: M,R
```
[here's the SOFA and script](https://www.dropbox.com/s/2tnrrorobutg2ai/%5BOpenAL%20Soft%5D%20SOFA%20to%20MHR%20test.zip?dl=1) I used to replicate this issue.

[libmysofa also got an update](https://github.com/hoene/libmysofa/releases/tag/v1.3) so perhaps [updating libmysofa in makemhr](https://github.com/hoene/libmysofa/issues/190#issuecomment-1265874608) could fix this issue just like [it fixed Mesh2HRTF SOFA conversion to HeSuVi WAV using ffmpeg](https://github.com/hoene/libmysofa/issues/186#issuecomment-1256956389).

**Comment by kcat** [comment]
Odd, I don't remember getting a message about this issue. Sorry about that.

This looks like it'll need a little more than just updating libmysofa. It seems the SOFA file specifies delay values for each of the measurements (where most SOFA files just have a global delay, with the actual impulse responses containing the delay), so makemhr will need to be updated to handle them.

But there seems to be another more significant issue. The `EAC_48kHz.sofa` file doesn't contain a usable uniform layout. The elevations go `-57.00, -30.00, -15.00, +0.00, +15.00, +30.00, +45.00, +60.00, +75.00`, where it's missing the top +90 degree response, and the bottom -57 degree response doesn't reflect position of the +60 degree response (though that might not be too important; it should just drop the -57 degree responses and synthesize the -45, -60, -75, and -90 responses, if +90 existed).

Another issue here (though it wouldn't have prevented the mhr from being made), is that there aren't that many elevations. While the number of azimuths is somewhat dense (72 at each elevation, 5 degrees apart), the number of elevations is pretty sparse (ignoring the misplaced and missing elevations, they're 15 degrees apart). This could be an issue for certain ambisonic uses, since there could be a fair amount of height error.

What I'd want here is some way to resample the soundfield. To be able to take an HRTF with less ideal coverage around the sphere, and interpolate new responses to create a uniform set at an arbitrary density. I don't think simple bilinear interpolation would be the right way to do that, though (even with a frequency-domain magnitude-only representation used prior to minimum phase reconstruction).

**Comment by ThreeDeeJay** [comment]
Interesting. I can forward these notes to the EAC developer. I just have a couple questions:
- Would it be beneficial to sync all impulse response pairs (like [align all the peaks of the louder channel in a left-right ear pair, while maintaining the delay of the quieter channel in the pair, of course](https://i.imgur.com/9zxc1jt.gif) for any given emitter position)? 
[The developer of HeSuVi recommends synced channels for stereo upmix into virtual surround](https://sourceforge.net/p/hesuvi/discussion/general/thread/5967c6c5ea/#4672/ee75), but I'm not sure if it also applies to 3D HRTFs or if there's a reason to keep some desync. And if desync is still undesired, could the MHR generator take advantage of the individual delay metadata in SOFAs to sync all IRs?

- doesn't OpenAL Soft synthesize the IR for a sound between existing IRs in realtime? or does it just use regular panning between existing IRs like virtual surround?
Perhaps syncing IRs could help reduce or even prevent phase artifacts that Mark Cerny pointed out in the [PS5 Tempest 3D HRTF presentation](https://youtu.be/ph8LyNIT9sg?t=2813).

**Comment by kcat** [comment]
> * Would it be beneficial to sync all impulse response pairs (like [align all the peaks of the louder channel in a left-right ear pair, while maintaining the delay of the quieter channel in the pair, of course](https://i.imgur.com/9zxc1jt.gif) for any given emitter position)?

I've been told no. Since the human head has width, and the two ears are approximately 18cm apart, the relative delay of a sound as it travels horizontally at a fixed radius from the center of the head is supposed to change. So to accurately simulate a ring or sphere of equidistant speakers (which is important for 3D sound reproduction), a given pair's primary delay (relative to the other pairs' primary delays) should be maintained.

Keeping the delay, however, does bring up phasing issues as you start using more responses at once. That's why for the first- and second-order ambisonic decoders for HRTF (which use 8 and 12 virtual speakers respectively, and 4 and 8 respectively for each ear) keep the relative delays, while the third-order decoder (which uses 20 total and 12 for each ear) removes the primary delays, because the third-order decoder otherwise has a high amount of high frequency attenuation due to strong phase cancellation from so many individual (virtual) speakers all playing the same sound.

> * doesn't OpenAL Soft synthesize the IR for a sound between existing IRs in realtime? or does it just use regular panning between existing IRs like virtual surround?

For "full" HRTF rendering, it blends the four nearest IRs given their proximity to the source position. This is partly why OpenAL Soft has certain requirements for HRTF layouts, so it can quickly find the nearest ones and know how to blend them given the source direction. Given how OpenAL Soft uses minimum phase HRIRs, it handles the delay separately from response itself, so it actually blends the delay separately from the frequency response (which helps cut down on the phase cancellation, but doesn't get rid of it completely; which is partly why the ambisonic decoders for HRTF don't use this blending and just use the nearest HRIR for each virtual speaker position).

> * I just noticed [e131a8e](https://github.com/kcat/openal-soft/commit/e131a8e5811e74fa7ab4e468282bddc6764b9fb5). Does it fix `Unsupported delay dimensions: M,R`?

Yes, but there's still the `Non-uniform elevations` error, so it still won't work.

> And how do you build makemhr.exe? I wanna test and it seems to be [set up to be compiled by CMake](https://github.com/kcat/openal-soft/blob/ee3142d4d605eac7e7c5f6d4df87ec5e3b345d29/CMakeLists.txt#L1574) but [I don't see the .exe being generated by CMake GitHub actions](https://github.com/ThreeDeeJay/openal-soft/actions/runs/3238475748/jobs/5306742075#step:4:120) so I'm probably missing something. I wanna avoid installing VS on my PC because it's really bloated and it's easier to share/test new code edits compiled in the cloud.

It also needs [libmysofa](https://github.com/hoene/libmysofa) installed.

**Comment by ThreeDeeJay** [comment]
Very interesting. 
and I guess since original issue was fixed and the `Non-uniform elevations` error is just the result of SOFAs not adhering to OpenAL Soft's requirements, I can go ahead and close this issue.
By the way, if you still have the new **makemhr.exe** and don't mind sharing, I'd love to test some SOFAs that do have uniform elevations 👌
