### ISSUE TITLE
Telegram has no sound when trying to play video

### ISSUE THREAD

**Issue by gbcox** [kcat/openal-soft#802]
Originally reported to Telegram here:  https://github.com/telegramdesktop/tdesktop/issues/25605
They referred me to you.

Basically what is happening is when trying to play a video from Telegram, no sound is received.  If you look at the sound applet it shows that a video is playing and that sound should be produced, but no sound at all.

Here is a comment from the Telegram folks:
Official tdesktop builds support openal's pipewire backend since it was released. I don't think Fedora package would have any difference, there's likely a bug in openal, there were similar complaints previously, but the users decided they don't want to report to openal, so the bug is still here.

**Comment by kcat** [comment]
Are you able to provide a trace log with the issue happening? Set the `ALSOFT_LOGLEVEL` environment variable to `3` when you run the app, and either forward the output of `stderr` to a file or also set the `ALSOFT_LOGFILE` env var to a full path+filename to have it write the log to the given file. If there's an issue with OpenAL Soft handling the playback, that should provide clues as to why it's not playing sound.

**Comment by ilya-fedin** [comment]
@kcat it's present in the linked issue

**Comment by ilya-fedin** [comment]
By the way, maybe you can take a look at the log file writer, tdesktop sets voth ALSOFT_LOGLEVEL and ALSOFT_LOGFILE in debug mode, mostly for Windows users, but it's quite uncomfortable to use them as openal flushes the log only on application termination

**Comment by kcat** [comment]
> @kcat it's present in the linked issue

I see. I don't notice any errors, and the audio panel shows the audio is playing. So OpenAL Soft is mixing and writing the audio to PipeWire, which is picking it up and giving the amplitude levels to apps that are monitoring it. Looks either like an issue with PipeWire, or OpenAL Soft is inadvertently doing something to mute the output (while not muting the stream itself). But there's nothing in the log to indicate anything is amiss, and if it was a general OpenAL issue, I'd expect other apps that use OpenAL to also be affected.

@gbcox Do other OpenAL apps (like mpv's `-ao openal` output driver, Super Tux, Super Tux Kart, Alien Arena, Dhewm3, ioQuake3, and others) play sound, or are they silent too? And if they're silent, does the audio panel show them playing sound like it does with Telegram?

> By the way, maybe you can take a look at the log file writer, tdesktop sets both ALSOFT_LOGLEVEL and ALSOFT_LOGFILE in debug mode, mostly for Windows users, but it's quite uncomfortable to use them as openal flushes the log only on application termination

This should be handled better since commit 8054ccd8f91fee5aacb35e01decbecb67a8da8ce (and a few fixups with commit bb751ebc4421789219cb05ca8afa4203fb1d1ed7). It now makes sure to always call `fflush` after writing each line to the file. Though oddly, it should already do that on Windows. If `fflush` doesn't flush the log, I'm not sure what's wrong.

**Comment by gbcox** [comment]
@kcat I just installed SuperTux and SuperTuxKart and hear sound in both.  Still no sound from tdesktop.

**Comment by kcat** [comment]
> @kcat I just installed SuperTux and SuperTuxKart and hear sound in both. Still no sound from tdesktop.

And the audio panels shows them all playing sound, even telegram?

**Comment by gbcox** [comment]
> > @kcat I just installed SuperTux and SuperTuxKart and hear sound in both. Still no sound from tdesktop.
> 
> And the audio panel shows them all playing sound, even telegram?

Correct.

**Comment by kcat** [comment]
How about on the Devices tab of the audio panel. Does that show any audio playing on the device with Telegram (and/or Super Tux (Kart))?

**Comment by gbcox** [comment]
> How about on the Devices tab of the audio panel. Does that show any audio playing on the device with Telegram (and/or Super Tux (Kart))?
Yes, I was looking at the devices panel, all the apps show activity on the analog output line.  It seems that Telegram is muted, but it shouldn't be, at least I don't have it muted.

**Comment by kcat** [comment]
> Yes, I was looking at the devices panel, all the apps show activity on the analog output line. It seems that Telegram is muted, but it shouldn't be, at least I don't have it muted.

Have you tried toggling the mute button on and off? What are the volume levels shown in the audio panel like, does Telegram reach appropriate levels that it should be heard, or does it stay really low?

Aside from that, I'm not seeing anything wrong on the OpenAL Soft side. There's no problem reported in the log, nothing even potentially questionable, and PipeWire is receiving and responding to audio from OpenAL Soft which it's playing on the device. Whatever's causing playback to go silent is outside of OpenAL Soft's purview.

What if you try using the PulseAudio or ALSA backends? Set the `ALSOFT_DRIVERS` env var to `pulse` or `alsa` when you run Telegram, then play the video.

**Comment by gbcox** [comment]
I'm on Fedora and pipewire is working for everything else and I'm not thrilled about starting to mess with the sound settings for just one application. Whenever I do that things seem to go south.  Could you try reaching out to the Telegram folks?  Looking on reddit, etc. other folks are complaining about this.

**Comment by gbcox** [comment]
In the meantime, I'll update my Telegram issue.  Thanks for your help!

**Comment by kcat** [comment]
This is kind of reminding me of an old issue with PulseAudio and Qt. Qt would set environment variables to change how PulseAudio streams get configured for when it created PulseAudio streams, but it also ended up influencing OpenAL Soft's PulseAudio streams. That ended up causing all streams in the process to be handled as System Sounds, so apps that used both Qt and OpenAL Soft had OpenAL Soft playback follow the event sound volume and not get listed in the audio panel. I don't think something like that is happening here with PipeWire (I've checked Telegram's environment variables, and at least when idle, I don't see anything PipeWire-related), but I also can't check during video/audio playback as I don't have any in Telegram to play, and it doesn't seem like it can play random files on my system to test it.

One more thing that might be helpful here is the output of `pw-dump`, which takes a snapshot of current PipeWire objects and configuration (which includes devices, nodes, and streams). While Telegram is trying to play audio but silent, run `pw-dump > dumplog.txt` and attach the resulting text file here.

**Comment by ilya-fedin** [comment]
> Though oddly, it should already do that on Windows.

Hm, maybe I checked myself only on Linux and thought it behaves the same on Windows...

> I don't notice any errors, and the audio panel shows the audio is playing.

Yeah, that's why I was out of ideas and redirected him here... Maybe it's a good idea to also create an issue on [PipeWire repo](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues)...

**Comment by gbcox** [comment]
@kcat I checked my notifications and I tried unmuting them just in case, but that didn't seem to have any effect.  Same result.  Here is the dumplog.txt. 
[dumplog.txt](https://github.com/kcat/openal-soft/files/10491179/dumplog.txt)
Here is the link to the video I'm trying to play, you should be able to download it and then attach it to your saved messages on telegram and then play it from within tdesktop:  [of course it's a cat video](https://drive.google.com/file/d/1gfP2s6xRdtIVjaetZhLZ27ArDConwrLf/view?usp=share_link)
@ilya-fedin Thanks for the feedback, if @kcat doesn't see anything I'll open a ticket with pipewire and reference both the telegram and openal-soft tickets.  
Thanks to you both for your help with this.

**Comment by ilya-fedin** [comment]
you can try to launch tdesktop with `ALSOFT_DRIVERS=pulse`, if it will produce the sound then the problem is somewhere between openal<->pipewire for sure

**Comment by gbcox** [comment]
@ilya-fedin tried ./Telegram ALSOFT_DRIVERS=pulse and didn't seem to make any difference. 

Was that the correct syntax to do this?

**Comment by ilya-fedin** [comment]
`ALSOFT_DRIVERS=pulse ./Telegram`

**Comment by gbcox** [comment]
Thanks, tried that and it didn't seem to make any difference.  Same result.

**Comment by ilya-fedin** [comment]
if you set `ALSOFT_LOGLEVEL=3`, does it confirm it uses the pulse driver?

**Comment by ilya-fedin** [comment]
> of course it's a cat video

wait, is the problem only with the concrete video or with all sound tdesktop? I assumed the latter.

**Comment by ilya-fedin** [comment]
> dumplog.txt

@kcat the log says @gbcox has a 8 channel output device and openal seem to report 8 channels for its stream, could it be a problem with upmixing?

**Comment by gbcox** [comment]
> if you set `ALSOFT_LOGLEVEL=3`, does it confirm it uses the pulse driver?

Yes:
[ALSOFT] (II) Initialized backend "pulse"
[ALSOFT] (II) Added "pulse" for playback
[ALSOFT] (II) Added "pulse" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found

**Comment by ilya-fedin** [comment]
@gbcox will the sound appear if you set faster playback speed?

**Comment by ilya-fedin** [comment]
@kcat looks like upmixing bugs with AL_REMIX_UNMATCHED_SOFT

**Comment by kcat** [comment]
Hmm, I'm still stumped. I am seeing an issue with the remix tables (their data is junk for some reason), but they shouldn't be affecting this case. Front left and front right exist in the output, so they should map directly without touching those tables. In either case, that's fixed with commit cc20bd01633221d4a72d03a05a8d4dc97b0eac64.

I've added the video to Telegram, and it's silent when it's in the chat window, which I think is normal (there's no open device or playing stream). I click it to make it full screen, and then audio plays fine (stereo/headphone output). I then shut down Telegram, configured OpenAL Soft to force 7.1 output (which PipeWire will accept, with downmixing to stereo for my headphones), reran Telegram and it still played fine. Then just to be extra sure, I configured OpenAL Soft to use the wave writer backend with 7.1 output, played the video to make it write the 7.1 wave file, then checked the wave file and it was also fine (there's audio in the front channels (center/lfe, side, and back channels are silent), and it plays fine).

I also did the same thing with OpenAL Soft's alffplay example; played normally, with `-direct` (remix unmatched), forced 7.1 w/ direct, wave writer forced 7.1 w/ direct, etc, and everything came out the same.

The fact that PipeWire is receiving and responding to audio from Telegram/OpenAL Soft is really throwing me off here. The audio panel shows the device getting the audio, the pw-dump log shows it playing on the correct device which is in a running state, volumes look normal, so something is being played and output, but it's only heard when it goes through an effect. I have absolutely no idea what could be going on.

**Comment by gbcox** [comment]
@kcat, does the comment above about the fact that if I change the playback speed to anything other than 1.00 I can hear the sound, but once I change the playback speed to exactly 1.00 it stops.  I can do that over and over while the video is playing and by adjusting the playback speed I can make the sound appear and disappear on demand.

**Comment by kcat** [comment]
> does the comment above about the fact that if I change the playback speed to anything other than 1.00 provide a clue.

Unfortunately not. It actually makes it more confusing. When the playback speed is set to 1, it plays directly on the output, so it mixes:
```
source  ->  output buffer
```
When it's not 1.0, it processes it through a pitch shifter effect to play it faster or slower while maintaining the same pitch:
```
source -> effect buffer -> main buffer -> output buffer
```
so it's still ultimately getting to the same point, just with a couple extra steps on the way (first to an effect buffer, where the pitch shifter processes it and writes to the main mixing buffer, then the main mixing buffer is converted from a speaker-agnostic spatial format to the discrete output channels for the device).

That might suggest there's an issue with the source mixing directly to the output buffer, except your audio applet shows PipeWire is still getting audio, so it is still getting to the output. It also works for other people, as well as for my own testing.

But that the audio is heard or goes silent depending on whether it's processed through an effect or not means PipeWire isn't simply muting the output, and PipeWire has no idea about OpenAL Soft using effects or anything about how the audio is processed, so its behavior shouldn't change from OpenAL Soft using an effect or not. So if PipeWire has no reason to change behavior from OpenAL Soft doing something different, and OpenAL Soft's behavior looks fine (it is outputting audio, since the audio applet is responding to its output), yet nothing is coming out of your device if it's not through the pitch shifter effect... I'm completely confused.

This probably needs to be brought up to the PipeWire devs. If PipeWire is getting the audio, but nothing is actually heard from the device in some situations, they may have a better idea of where to look for something going wrong.

One final thing I can think to try, since you're using KDE: go to System Settings -> Audio, and click the Test button for the device in question. Click each speaker icon individually to make sure each one plays as it should. Maybe something is off about the front left and front right outputs specifically, which gets masked by OpenAL Soft's panning mix and other apps outputting stereo (which may be getting upmixed to 7.1).

**Comment by gbcox** [comment]
@kcat Yes, I've tested the speakers before and just repeated, front, side, center, rear and subwoofer and everything works as it should.  The pitch shifter stuff (changing playback speed) is only for Telegram.  I've been using this for years and never had this issue before and all of my other applications are working perfectly fine.   The only issue I have is when I try to play videos using Telegram, no sound.  Also, @ilya-fedin had me test yesterday using pulse instead of pipewire and it didn't work either.  So that seems to tell me it isn't a pipewire issue, which just leaves Telegram and OpenAL Soft.

**Comment by kcat** [comment]
> Also, @ilya-fedin had me test yesterday using pulse instead of pipewire and it didn't work either. So that seems to tell me it isn't a pipewire issue, which just leaves Telegram and OpenAL Soft.

That's still ultimately PipeWire, just having OpenAL Soft use its PulseAudio backend and the client library. PipeWire has its own PulseAudio-compatible server, which uses the PipeWire server for playing on the device (you can't otherwise use PipeWire and PulseAudio natively together since they both try to take control of the hardware).

**Comment by gbcox** [comment]
Yeah, I just tested on my laptop that only supports 2 channels, and that worked.  Then I turned off 7 channel and just went to 2 channels on my laptop and that works.  So, apparently the software just can't handle more than 2 channels correctly.  :-(  That's what I get for being fancy and buying an expensive video card.

**Comment by kcat** [comment]
> So, apparently the software just can't handle more than 2 channels correctly.

But it should, and it does. OpenAL Soft works fine when doing 7.1 with other apps (SuperTux, SuperTuxKart, etc), and it works fine when not doing direct output.

Out of curiosity, does Fedora's OpenAL package come with alffplay, or have another package that does? (Note, not `ffplay` which comes with ffmpeg, but `alffplay` which is an example program from OpenAL Soft.) If it does, can you run `alffplay -direct somefile.foo` with some media file that has mono or stereo sound, and do you hear it while it plays? If you have a file with 5.1 or 7.1 audio, do you hear that play?

**Comment by ilya-fedin** [comment]
> never had this issue before

How much before? tdesktop updated openal somewhere right after its latest release that was in June, 2022, tdesktop also had no audio-related changes for multiple years, so if that started happening recently, the only explanation is it's a PipeWire regression...

**Comment by gbcox** [comment]
> > never had this issue before
> 
> How much before? tdesktop updated openal somewhere right after its latest release that was in June, 2022, tdesktop also had no audio-related changes for multiple years, so if that started happening recently, the only explanation is it's a PipeWire regression...

@ilya-fedin Yeah, probably not a good idea to make that assumption.  I very rarely play attached videos within Telegram.  Usually people send me video links rather than attaching files,  plus apparently this issue is only on my desktop with the 7 channel audio card.

@ilya-fedin @kcat I also did some more testing last night and found that 5.1 audio works fine also, the problem only occurs with 7.1. - that's much much better than being restricted to 2 channel.

@kcat I do have openal installed on Fedora, but did a search for alffplay and couldn't find it.  I'll do some more searching and if I can't find it, I'll reach out the maintainer and as if he can package it for Fedora.

Thanks again for you both taking the time to think about this.  It's a slog, looking for a needle in a haystack.  But at least the issue is narrowed down to just 7.1 audio now.   That will help for circumvention purposes.

**Comment by ilya-fedin** [comment]
tdesktop 4.8.0 uses openal 1.23.0 that should include fixes mentioned by @kcat, can you retest whether the bug is still present?

**Comment by gbcox** [comment]
Yes, thanks for the heads-up. I'm away from the computer with that particular sound card, so I will test when I return.  Will be approximately the first week in June.

**Comment by gbcox** [comment]
> 

Yes, that fixed the issue.  Thanks.  Closing.
