### ISSUE TITLE
Inner workings of AL_EXT_EFX

### ISSUE THREAD

**Issue by Micha0** [kcat/openal-soft#803]
Hi Kcat,

Goal: Add a new Effect which enables registering and running a basic DSP function with a signature of `void(*)(size_t samplesToDo, const float* bufferIn, float* bufferOut)`

I went ahead under the guidance of #275 and added this custom effect. In order to make it work I needed to extend the effect api to also support void* arguments. Nothing too complicated, but I might have broken the standard. (Not an issue for me personally, though.)

However, I'm having difficulties understanding the data I have to work with.
Given `virtual void EffectState::process(const size_t samplesToDo, const al::span<const FloatBufferLine> samplesIn, const al::span<FloatBufferLine> samplesOut)`
* What does `samplesIn` contain? A 1k array of floats per channel? (First level, the span, are the channels? And the second, the array, is the actual data?)
* What does `samplesOut` contain? Does it contain something valid or could it be considered garbage/uninitialized?
* Why `samplesOut.size() != samplesIn.size()`?

Studing the other implementations of `EffectState::process` it becomes clear `MixSamples` is an important factor. I'm trying to understand it and specifically the `CurrentGains` and `TargetGains` part. I'm happy to dive into literature for this one. What do I look for?
* How would a 5 year old implement `MixSamples`? 
* How would you implement a simple "copy input to output" effect in the `process` function?
* Why does a simple `memcpy` from `samplesIn` to `samplesOut` not work?

With kind regards,
Micha

**Comment by kcat** [comment]
> However, I'm having difficulties understanding the data I have to work with. Given `virtual void EffectState::process(const size_t samplesToDo, const al::span<const FloatBufferLine> samplesIn, const al::span<FloatBufferLine> samplesOut)`
> 
> * What does `samplesIn` contain? A 1k array of floats per channel? (First level, the span, are the channels? And the second, the array, is the actual data?)

Hi.

`samplesIn` contains an array of uninterleaved channels that holds up to 1k samples each. The actual number of valid samples per channel (and the number of sample frames to process) is `samplesToDo`, which will never exceed `FloatBufferLine{}.size()` (currently 1024). So `samplesIn[c][i]`, where `0 <= c < samplesIn.size()`, and `0 <= i < samplesToDo`.

The actual channel configuration may be difficult to wrap your head around if you're not familiar with spatial audio formats. In particular, it uses a B-Format configuration, ACN channel layout and N3D channel scaling, at an order that matches the device mix (this is to handle surround sound in a speaker-agnostic way). If all you need is a mono input, then it's easy: `samplesIn[0]` is a mono mix of all sources feeding the effect. Generate panning gains in the `update` method for how you want to mix that to the output, and you're pretty much good to go. Something like:

```c++
struct MyEffectState : public EffectState {
    /* Temporary output results. Should be aligned for proper SIMD handling. */
    alignas(16) FloatBufferLine mSamples;

    /* Gains used to mix the temporary results to the output. */
    float mTargetGains[MAX_OUTPUT_CHANNELS];

    /* Defines new/delete allocators that are over-alignment aware. */
    DEF_NEWDEL(MyEffectState)
};

void MyEffectState::update(const ContextBase*, const EffectSlot *slot,
    const EffectProps *props, const EffectTarget target)
{
    /* Clear the previous target gains. */
    std::fill(std::begin(mTargetGains), std::end(mTargetGains), 0.0f);

    /* Calculate the ambisonic coefficients for where the output will be positioned. This puts the output right in front. */
    auto coeffs = CalcDirectionCoeffs({0.0f, 0.0f, -1.0f});

    /* Set the output buffer target (Main, the default), and calculate the actual gain values for it. */
    mOutTarget = target.Main->Buffer;
    ComputePanGains(target.Main, coeffs.data(), slot->Gain, mTargetGains);
}

void MyEffectState::process(const size_t samplesToDo, const al::span<const FloatBufferLine> samplesIn,
    const al::span<FloatBufferLine> samplesOut)
{
    /* Process the mono input samples with your function. */
    ProcessData(samplesToDo, samplesIn[0].data(), mSamples.data());

    /* Mix the processed samples to the output. */
    MixSamples({mSamples.data(), samplesToDo}, samplesOut, mTargetGains, mTargetGains, 0, 0);
}
```

This would be a basic workflow for mono-in-mono-out processing. Note that the `update()` and `process()` methods must be real-time safe (no locks, (de)allocation, or anything that can cause the thread to get blocked). The `deviceUpdate()` method can be used for non-real-time-safe initialization (which is called when the effect is first created, and whenever the device configuration changes (e.g. changed sample rate or channel configuration)).

If you want to do effects in surround sound, so that the output direction of the processed sound is related to the input sound's direction, that can get more complicated. Some effects may work fine as-is with spatial channels, in which case it's not much different than doing that same thing for each input channel, but that relies on the processing maintaining the same gain and phase relationship between channels (e.g. applying the same IIR or FIR filter configuration or gain adjustment to each channel is fine, as any changes to the gain or phase in one channel is also done in the other channels). Effects that don't work with spatial channels would need additional work; you'd need to remix them to discrete channel feeds, process those discrete channels, then remix them back to spatial channel feeds.

> * What does `samplesOut` contain? Does it contain something valid or could it be considered garbage/uninitialized?

It contains valid samples for what's already been processed for that buffer (which is normally the device's main mixing buffer, so all the sources, along with any other active effects that were processed before the current effect). So the new samples should be added to the output buffer (which `MixSamples` does).

> * Why `samplesOut.size() != samplesIn.size()`?

If the output configuration is different from the input, which can happen if the main mixing buffer uses a 2D spatial buffer for 2D surround sound output (which has fewer channels than a 3D spatial buffer used by effects), or if the effect uses the `RealOut` output buffer (which represents the device output channels instead of the main mixing buffer).

> Studing the other implementations of `EffectState::process` it becomes clear `MixSamples` is an important factor. I'm trying to understand it and specifically the `CurrentGains` and `TargetGains` part. I'm happy to dive into literature for this one. What do I look for?

It's nothing too special. At it's core, it basically just takes one input channel (array/span of input samples), and an array/span of multiple output channels, and mixes the input into each output channel using `CurrentGains` (one gain per output channel), in a manner like
```c++
for(c = 0;c < samplesOut.size();++c)
{
    for(i = 0;i < samplesToDo;++i)
        samplesOut[c][i] += input[i] * CurrentGains[c];
}
```

`MixSamples` has a few optional extra features to it. Namely it can handle changes to the output gain smoothly, applying a per-sample linear fade from `CurrentGains` to `TargetGains` (where `TargetGains` can be changed as-desired in between calls. and `CurrentGains` is used to know what the gains last were to fade from) over a specified number of samples (separate from the number of samples to mix), and there are SSE- and NEON-specific implementations to be more efficient (which is automatically selected if the CPU can handle it).

> * How would a 5 year old implement `MixSamples`?

Here's the [non-SIMD implementation](https://github.com/kcat/openal-soft/blob/1.22.2/core/mixer/mixer_c.cpp#L163). It first calculates the delta factor for the number of samples to fade the gain over (so that Counter*delta = 1), and calculates the number of samples to do the fade loop (which is either the fade `Counter`, or the number of samples to mix if it doesn't finish fading this mix). If `Counter==0`, it just uses the target gains without any fading.

Then for each output channel, it takes the current gain and calculates the gain step (how much the gain changes per-sample to reach the target gain from the current gain). For each output sample, it multiplies the input sample by the interpolated gain value, adds it to the output, then increments the interpolation step. When the fading loop is done, it stores the now-current gain in `CurrentGains`.

Then if there's still more samples to do after fading the gain (i.e. the gain reached the target and there's still more samples to mix), it checks if the now-current gain is above some threshold for audibility (currently -100dB), and if so, adds the input to the output with the gain staying constant.

> * How would you implement a simple "copy input to output" effect in the `process` function?

Like the [equalizer effect](https://github.com/kcat/openal-soft/blob/1.22.2/alc/effects/equalizer.cpp), just remove the biquad filters and the temp buffer.

> * Why does a simple `memcpy` from `samplesIn` to `samplesOut` not work?

Aside from needing to add to samplesOut instead of overwrite, and that the effect slot has a gain that should be honored, because the channel configuration may be different. In theory, it can be nearly as simple (one input channel to one output channel, with one gain per channel) as long as you don't use the `RealOut` target, it just an index remap and a per-channel gain, like:
```c++
for(c = 0;c < samplesIn.size();++c)
{
    // If there's no valid target for this channel, it's dropped
    auto outchan = mChannelMap[c];
    if(outchan == INVALID_CHANNEL_INDEX)
        continue;

    // Apply the appropriate scale factor for the output (includes the effect slot gain).
    float gain = mChannelGain[c];
    for(i = 0;i < samplesToDo;++i)
        samplesOut[outchan][i] += samplesIn[c][i] * gain;
}
```
I'd need to make functions to generate the channel map and gains for that to work. And as noted, this would only work if the processing you want to do works with spatial channels. If you need to work with discrete channels, then you'd need to do two remixing passes on the channels (one before processing, and one after when writing to the output).

**Comment by Micha0** [comment]
Hi Kcat,

this was incredibly helpful and I have no follow up questions as you anticipated them all! Thank you!

With kind regards,
