### ISSUE TITLE
uhjdecoder and uhjencoder

### ISSUE THREAD

**Issue by ryandesign** [kcat/openal-soft#866]
If libsndfile is found when cmake is run for openal-soft, then uhjdecoder and uhjencoder are built.

https://github.com/kcat/openal-soft/blob/d3875f333fb6abe2f39d82caca329414871ae53b/CMakeLists.txt#L1577-L1595

These executables are not installed. Should they be? If not, what is their purpose?

The unanticipated optional use of libsndfile [caused a build failure of openal-soft for a MacPorts user](https://trac.macports.org/ticket/67681). If these executable should not be installed, can the detection and use of libsndfile be prevented via some cmake flag? The use of other libraries can be prevented with a flag, for example:

https://github.com/kcat/openal-soft/blob/d3875f333fb6abe2f39d82caca329414871ae53b/CMakeLists.txt#L906-L907

but I didn't see such a flag to prevent the use of libsndfile.

**Comment by kcat** [comment]
> These executables are not installed. Should they be? If not, what is their purpose?

Their purpose is to encode and decode UHJ audio files, which OpenAL Soft can use with the [AL_SOFT_UHJ](https://openal-soft.org/openal-extensions/SOFT_UHJ.txt) extension. The main reason they're not installed is because they lack distinctive names ("uhj" isn't unique to OpenAL), it's not out of the question that another package could have programs with the same names and cause conflicts. Otherwise, they're not too useful to most users, but can be useful to some that may want to work with or use UHJ content if they don't already have something else to do the job.

> The use of other libraries can be prevented with a flag, for example:

Those prevent enabling backends, some of which happen to correspond to specific libraries. libsndfile is used by the uhjdecoder and uhjencoder utilities, as well as a number of examples (alplay, alstream, etc). If you don't want to disable the utility and example programs, it is possible to prevent cmake from finding specific libraries or packages generically. Passing `-DCMAKE_DISABLE_FIND_PACKAGE_SndFile=TRUE` to cmake should prevent libsndfile from being found (`find_package(SndFile)` will fail) even if it's available, preventing the specific utilities and examples that need it from building.

**Comment by ryandesign** [comment]
> Passing `-DCMAKE_DISABLE_FIND_PACKAGE_SndFile=TRUE` to cmake should prevent libsndfile from being found

Oh yes, I keep forgetting about [`CMAKE_DISABLE_FIND_PACKAGE_*`](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html); thanks for the reminder. That does work.
