### ISSUE TITLE
Questions about loopback

### ISSUE THREAD

**Issue by MV10** [kcat/openal-soft#869]
I stumbled across the fact that OpenAL Soft has some kind of internal loopback support. How is this used? At the moment I've been working on loopback outside of OpenAL.

Loopback on Windows turned out to be easy. I'm using the [Cable](https://vb-audio.com/Cable/) virtual device driver from VB-Audio. It seems to work well enough, although it's a dependency I'd prefer to eliminate. I wrote an info-dump utility similar to the one included with OpenAL Soft, and you can see the Cable devices listed here:

<details>
<summary>Windows device list</summary>

```
Drivers:
  OpenAL Soft
  Generic Software

Default driver:
  Generic Software
  (Opening "OpenAL Soft" instead)

Playback devices:
  OpenAL Soft on CABLE Input (VB-Audio Virtual Cable)
  OpenAL Soft on Speakers (High Definition Audio Device)
  Generic Software on CABLE Input (VB-Audio Virtual Cable)
  Generic Software on Speakers (High Definition Audio Device)

Capture devices:
  OpenAL Soft on CABLE Output (VB-Audio Virtual Cable)
  OpenAL Soft on SPDIF Interface (UR23 USB SPDIF Rx)
  CABLE Output (VB-Audio Virtual
  SPDIF Interface (UR23 USB SPDIF

Default  devices:
  Playback: OpenAL Soft on CABLE Input (VB-Audio Virtual Cable)
  Capture: CABLE Output (VB-Audio Virtual
```
</details>

However, on Linux (specifically a Rasberry Pi 4B) I set up ALSA loopback (following [these](https://github.com/TheSalarKhan/Linux-Audio-Loopback-Device/blob/master/README.md) instructions), and while it works and I've made it persistent between reboots, I'm not sure how to use it from OpenAL. 

<details>
<summary>Loopback module <i>snd_aloop</i> is loaded</summary>

```
~ $ lsmod | grep snd
snd_soc_hdmi_codec     20480  2
snd_bcm2835            28672  1
snd_soc_core          274432  2 vc4,snd_soc_hdmi_codec
snd_compress           20480  1 snd_soc_core
snd_pcm_dmaengine      20480  1 snd_soc_core
snd_aloop              32768  2
snd_pcm               139264  6 snd_bcm2835,snd_soc_hdmi_codec,snd_compress,snd_soc_core,snd_aloop,snd_pcm_dmaengine
snd_timer              36864  2 snd_aloop,snd_pcm
snd                   106496  17 snd_bcm2835,snd_soc_hdmi_codec,snd_timer,snd_compress,snd_soc_core,snd_aloop,snd_pcm
```
</details>

<details>
<summary>Raspberry Pi device list</summary>

```
Drivers:
  OpenAL Soft

Default driver:
  OpenAL Soft
  Using: "OpenAL Soft"

Playback devices:
  Built-in Audio Digital Stereo (HDMI)
  Built-in Audio Analog Stereo
  Built-in Audio Analog Stereo #2

Capture devices:
  Built-in Audio Analog Stereo
  Monitor of Built-in Audio Analog Stereo
  Monitor of Built-in Audio Analog Stereo #2
  Monitor of Built-in Audio Digital Stereo (HDMI)

Default  devices:
  Playback: Built-in Audio Digital Stereo (HDMI)
  Capture: Built-in Audio Analog Stereo
```
</details>

But now that I know OpenAL Soft has a loopback support, perhaps ALSA loopback isn't necessary at all? My hope is that both Windows and Linux can rely on the same code and "It Just Works ™️"...

On a sort-of-related note,  I am unclear about how to specify a particular non-default playback device. The constructor for an audio-capture class in one of my test projects is quite simple. You can see below that it uses the defaults, and it's obvious how to select the capture device by name, but I don't see where a playback device name would be used. (Obviously this is C#, I am using the [OpenTK](https://github.com/opentk/opentk) wrapper for .NET, which might be a good candidate to add to your "Bindings" section in the README.)

```csharp
public Audio()
{
    DriverDeviceName = ALC.GetString(ALDevice.Null, AlcGetString.DefaultDeviceSpecifier);
    var devices = ALC.GetStringList(GetEnumerationStringList.DeviceSpecifier);
    foreach (var d in devices)
    {
        if (d.Contains("OpenAL Soft"))
        {
            DriverDeviceName = d;
            break;
        }
    }

    Device = ALC.OpenDevice(DriverDeviceName);
    Context = ALC.CreateContext(Device, (int[])null);
    ALC.MakeContextCurrent(Context);

    PlaybackDeviceName = ALC.GetString(Device, AlcGetString.DefaultAllDevicesSpecifier);
    CaptureDeviceName = ALC.GetString(Device, AlcGetString.CaptureDefaultDeviceSpecifier);

    CaptureDevice = ALC.CaptureOpenDevice(CaptureDeviceName, SampleRate, SampleFormat, PcmSamples);
}
```

**Comment by kcat** [comment]
OpenAL Soft's loopback support is for rendering audio on-demand to an application buffer rather than an output device. If you still want the audio played in addition to reading back the samples, you would need to find a way to play the audio separately. Otherwise, if you're just getting the samples, you use the [`ALC_SOFT_loopback`](https://openal-soft.org/openal-extensions/SOFT_loopback.txt) extension.

To use the extension, you need to be able to call C function pointers. I don't know C# well enough to say how to, but normally in C/C++, you would first check for the extension using `alcIsExtensionSupported(NULL, "ALC_SOFT_loopback")`, then you'd call `alcGetProcAddress(NULL, "...");` to get function pointers to the new `alcLoopbackOpenDeviceSOFT`, `alcIsRenderFormatSupportedSOFT` and `alcRenderSamplesSOFT` functions.

Once loaded, the idea is that you'd call `alcLoopbackOpenDeviceSOFT` to get a device handle instead of `alcOpenDevice` (with the list of potential device names being from the `GetEnumerationStringList.DeviceSpecifier` list, not the more specific `AllDevicesSpecifier`, or `null` for a default). You pass that device handle to the normal `ALC.CreateContext` function, but you must also pass an attribute array defining the format (channel configuration, sample type, sample rate) you want the mix to be, otherwise it will fail. Then you call `alcRenderSamplesSOFT` with the device handle whenever you want new samples. The [`alloopback` example](https://github.com/kcat/openal-soft/blob/master/examples/alloopback.c) shows how to do it in C.

> On a sort-of-related note, I am unclear about how to specify a particular non-default playback device.

Querying `ALC.GetStringList(GetEnumerationStringList.AllDevicesSpecifier)` should get you a list of specific playback device names available on the system. You can pass any from the list to `ALC.OpenDevice` to open that specific one.

**Comment by MV10** [comment]
Gotcha, yes, my need is an "intercept the playback" scenario. Slowly (painfully) realizing I need to do more ALSA and PulseAudio configuration to approximate what I'm getting on the Windows side.

For what it's worth, yes C# could make those calls, the OpenTK library's audio portion is a very minimal wrapper over OpenAL.

Thanks! And thanks for the library and all your work!
