### ISSUE TITLE
Audio capture on Android?

### ISSUE THREAD

**Issue by tzachshabtay** [kcat/openal-soft#87]
Getting the capture device on Android (tested on Nexus 5X) returns empty.
I looked at the opensl.c implementation and it looks like audio capture is not implemented.
Is that correct? Or is there another backend for Android which supports audio capture? Are there plans to add support for audio recording on opensl?
Thanks.

**Comment by kcat** [comment]
> I looked at the opensl.c implementation and it looks like audio capture is not implemented.
> Is that correct?

That's right, the OpenSL backend currently only supports playback. I don't have any immediate plans to add capture support for it, but I'm willing to accept any patches for it.

As for other backends that may work, the only one I can think of is the PortAudio backend. I don't know if PortAudio actually supports Android, but if it does, capture may work through that.

**Comment by DrPeeps** [comment]
I'm just curious to know ... how much work would you estimate might be involved in adding this missing audio capture support? I would also love to see it happen! I'm not sure I have the skill or time to spend on it myself though. 😿

**Comment by kcat** [comment]
It shouldn't be too much work if you're familiar with capture on OpenSL. Unfortunately I'm not, and I don't have a way to test anything I could write.

**Comment by kcat** [comment]
I've managed to add capture support to the OpenSL backend. However, beyond ensuring it compiles with my standalone toolchain, I don't know if it works. If you're able, feel free to test it and put it through its paces (in particular, how well it handles various formats, or its overrun behavior if you let its internal buffer fill up).

**Comment by DrPeeps** [comment]
> I've managed to add capture support to the OpenSL backend. However, beyond ensuring it compiles with my standalone toolchain, I don't know if it works. If you're able, feel free to test it and put it through its paces.

I'd love to start testing this now, but the platform I'm using (LÖVE2D) won't incorporate these changes until they're in an _official_ OpenALSoft release. So I'm going to have to wait until then.

**Comment by its-pointless** [comment]
i build latest version but still says capture devices available none in openal-info.
Of course i built it for termux rather than a normal android app. So i don't know if this is any help.

**Comment by its-pointless** [comment]
anyone gotten this to work?

**Comment by DrPeeps** [comment]
> anyone gotten this to work?

Unfortunately I'm _still_ waiting for my platform of choice to incorporate the latest changes. :(  I'm also anxious to see this functionality in action ....

**Comment by its-pointless** [comment]
well i kind of got this to work using master
that is alrecord works. It isn't working properly using toxic and openal-info doesn't detect it.
requirers changing this in opensl.c to work consistently though. 
` -        self->mRing = ll_ringbuffer_create(device->NumUpdates, device->UpdateSize*self->mFrameSize,`
`+        self->mRing = ll_ringbuffer_create(1 , device->UpdateSize*self->mFrameSize,`
                                            false);

**Comment by its-pointless** [comment]
Without my edit im geting this
(EE) ALCopenslCapture_captureSamples: bufferQueue->Enqueue: Buffer insufficient
i noticed while debugging another app which used 1 there. Tried it in openal-soft and it worked. 
Toxic isn't complaining now will test it properly later.

**Comment by kcat** [comment]
Can you get a trace log from trying to use toxic? Either in android's log, or setting the `ALSOFT_LOGLEVEL` environment variable to `3` when you run the app and get its `stderr` output.

**Comment by its-pointless** [comment]
Looks to be an issue on my end. So nothing for you to deal with. now just have to figure out why using 1 there allows it to work...

**Comment by its-pointless** [comment]
I can't work this out...

**Comment by its-pointless** [comment]
Okay best guess is that the call back for capture buffer isn't working. So after one chunk nothing happens. Which is why shrinking ring buffer works. Also possible im completely wrong.

**Comment by kcat** [comment]
If the callback isn't working, then capture wouldn't work at all. The callback is what tells the ringbuffer (and subsequently the app) that samples have been captured are are ready to be read. If the callback never runs, the available capture samples would remain at 0 and nothing would happen.

**Comment by its-pointless** [comment]
K latest version is working but for one issue. When the bufferqueue is filled the first time here
`result = VCALL(bufferQueue,Enqueue)(data.first.buf + chunk_size*i, chunk_size);`
android returns SL_RESULT_BUFFER_INSUFFICIENT in logcat since the buffer is full. so it needs to check if i equals device->numUpdates  and return 0; or something like that. I think once past the initial buffer fill it works as expected.

**Comment by dslc** [comment]
> Without my edit im geting this
> (EE) ALCopenslCapture_captureSamples: bufferQueue->Enqueue: Buffer insufficient

I encountered this problem also. I believe this occurs because the `size` field in the associated ring-buffer is being [rounded up to a power of two](https://github.com/kcat/openal-soft/blob/openal-soft-1.19.1/Alc/ringbuffer.c#L74). As a result the [write vectors retrieved for the buffer queue](https://github.com/kcat/openal-soft/blob/openal-soft-1.19.1/Alc/backends/opensl.c#L875) have a greater length than `device->NumUpdates`.

Ultimately, the library then tries to queue more buffers than had been [previously designated](https://github.com/kcat/openal-soft/blob/openal-soft-1.19.1/Alc/backends/opensl.c#L792).
As the OpenSL spec explains:

> If the maximum number of buffers specified in the SLDataLocator_BufferQueue structure used as the data source when creating the media object using the CreateAudioPlayer or CreateMidiPlayer method has been reached, the buffer is not added to the buffer queue and SL_RESULT_BUFFER_INSUFFICIENT is returned.

I have worked around this - for the time being at least - by setting `limit_size = true` instead of `false` when [creating the ring-buffers](https://github.com/kcat/openal-soft/blob/openal-soft-1.19.1/Alc/backends/opensl.c#L856). This prevents the ring-buffer `size` from being rounded up to a power of two, and - as a result - prevents the library from trying to queue more buffers than had been previously designated.

I am not sure if this will have other side-effects, and appreciate there may be a preferable solution.

P.S. I am working from tag `openal-soft-1.19.1`. I have tried a recent master branch also (in last few days), but was still having this problem.

**Comment by kcat** [comment]
> I encountered this problem also. I believe this occurs because the `size` field in the associated ring-buffer is being rounded up to a power of two. As a result the write vectors retrieved for the buffer queue have a greater length than `device->NumUpdates`.

Good catch. There's a couple ways to fix it, then. First would be as you did, set `limit_writes = true` which prevents having more writable space than requested (though I notice a bug in how it's handled; I'll need to fix that). Alternatively, create the ring buffer earlier and take its rounded size into account for the OpenSL buffer queue.

The `limit_writes` setting is mostly intended for playback devices to prevent excessive latency from extra storage, since it needs to keep its buffer full to prevent underruns. But for capture, the app should be reading the samples as fast as possible and not let the buffer get full to prevent overruns. OpenAL capture guarantees the opened device has at least the specified capture size, so this would be allowed and give the app a bit more of a cushion for being late with checking samples.

**Comment by dslc** [comment]
Thanks for the quick response and further info. I'll need to study the details you've shared: I'll get back to you if I have any questions. Cheers.

**Comment by kcat** [comment]
Capture support has (long) been added to the OpenSL backend. If there's any specific issues you run across, feel free to open a new issue about it.
