### ISSUE TITLE
Handling MHR v2/v3 formats

### ISSUE THREAD

**Issue by ceski-1** [kcat/openal-soft#870]
I'd like to include a few MHR files in a project that originate from SOFA files and let the user select one from a list. The project is cross-platform and unfortunately Debian/Ubuntu are still using OpenAL Soft 1.19.1. This version only supports up to v2 of the MHR format. What would be the most appropriate path for addressing this issue? I thought of the following options:

1. Convert SOFA files to v2 MHR and accept whatever quality trade-offs come with that. This assumes SOFA files can be processed by the 1.19.1 version of makemhr.
2. Request a backwards compatibility command line parameter for the makemhr utility. Maybe this also results in v2 MHR files that benefit from some or all of the changes made to makemhr utility since 1.19.1.

**Comment by kcat** [comment]
SOFA files aren't supported by 1.19.1's makemhr, I don't think. However, 1.20.1's should support it and still produce v2 format MHRs, but it may lack some enhancements and fixes made since then. An option to add v2 output to current builds may not be too difficult (aside from changing the header marker, it would just need to add a byte indicating 24-bit samples, cut the sample delay precision, and iterate the fields in reverse for multi-field data sets), so it is potentially doable.

Though ideally Debian would just update, as there are other drawbacks to using such an old version beyond lacking MHR v3 support (various performance and stability improvements, and new features). I haven't been able to find out why they're staying on a nearly 5 year old version, whether there's some compatibility issue with other packages (though other distros seem to have updated fine) or they just don't have someone to do it, and I don't know how to help make/test an update for them.

**Comment by ceski-1** [comment]
> An option to add v2 output to current builds may not be too difficult

If that's the case, I think it would be a helpful addition to makemhr. I don't know the reason for Debian using a 5 year old version either, but I suppose it's in line with the project's philosophy.

**Comment by kcat** [comment]
As an update, I noticed Debian testing and unstable has somewhat recently updated to 1.23.1. The current stable (Bookworm) is still on 1.19.1, but that's a more LTS-style release that will only see critical fixes until the next major release.

**Comment by ceski-1** [comment]
Yes, by chance the maintainer for the project I'm contributing to is also a Debian developer, so that worked out nicely. I'll have to be patient for now.
