### ISSUE TITLE
Spatialisation Issues at High Reference Distances

### ISSUE THREAD

**Issue by Vercidium** [kcat/openal-soft#878]
## Issue 1
While testing reference distance values, I discovered that spatialisation breaks when getting close to a spatialised source. The distance this occurs depends on the reference distance. I've only observed this at huge reference distance values such as 1600 and 16000.

```
Distance model: AL_INVERSE_DISTANCE
Listener gain: 1
Meters per unit: 0.7142857
Speed of sound: 480.620026

Attributes:
ALC_HRTF_SOFT: 1
ALC_HRTF_ID_SOFT: 0
ALC_FREQUENCY: 48000
ALC_MAX_AUXILIARY_SENDS: 1
```

I also remember enabling some extension/setting a while back that allows stereo buffers to be spatialised, but I can't find where that is.
No filters are applied.
All sounds are going through a global reverb effect, which is created like so:
```
var effectID = AL.GenEffect();
AL.Effecti(effectID, EFX.AL_EFFECT_TYPE, EFX.AL_EFFECT_REVERB);
AL.Effectf(effectID, EFX.AL_REVERB_DECAY_TIME, 1);

var effectSlotID = AL.GenEffectSlot();
AL.AuxiliaryEffectSloti(effectSlotID, EFX.AL_EFFECTSLOT_EFFECT, (int)effectID);
```

Video:
https://youtu.be/Hwwf6TQb8xg

## Issue 2
When standing 10 units away from the source with a reference distance of 20, the spatialised sounds are quieter than my personal non-spatialised sounds.

Personal sounds have these settings:
```
source.SetRelative(true); // Sets AL_SOURCE_RELATIVE to 1
source.SetSpatialise(false); // Sets AL_SOURCE_SPATIALIZE_SOFT to 1
source.SetGain(1.0f);
source.SetPitch(1.0f);
source.SetLooping(false);
```

Spatialised sounds have these settings:
```
source.SetRelative(false);
source.SetSpatialise(true);
source.SetReferenceDistance(20.0f);
source.SetGain(1.0f);
source.SetRolloff(1.0f);
source.SetPitch(1.0f);
source.SetLooping(false);
```

I saw this [volume-related issue](https://github.com/kcat/openal-soft/issues/874) but not sure if it's applicable here as it's dealing with non-spatialised mono sounds.

Video:
https://youtu.be/ZyiK4OV7MeI

**Comment by kcat** [comment]
What version of OpenAL Soft are you using?

For the second issue, a spatialized sound is downmixed to mono and panned in the appropriate direction, even when it's within the reference distance. That may make it sound a touch quieter since the sound isn't as wide as when played in stereo. Only when the distance gets (near) to 0 will it play in stereo again. Earlier version of OpenAL Soft may have also made non-mono sounds unintentionally quieter when downmixed and panned.

For the first issue, I'm not sure. It certainly sounds like a larger reference distance is causing OpenAL Soft to treat the sound as unpanned at larger distances. There may have been a few older releases where distances less than around 1/1000th of the reference distance were treated as 0 distance, but that should have been fixed a while ago. The reference distance shouldn't have an effect on when a sound is no longer considered panned.

**Comment by Vercidium** [comment]
I'm using 1.21.1.0 - haven't upgraded since I first started using it. Are there any API changes in 1.23.1 that may break the C# bindings I'm using from here: https://github.com/flibitijibibo/OpenAL-CS?

**Comment by Vercidium** [comment]
Thank you, `1.23.0` sounds **much** better.

In this demo video, the sound is played 8 units in-front of the camera when aiming down the sights. The first four gunshots are with `1.21.1`, the next four are with `1.23.0`. Reverb is disabled for clarity.

https://youtu.be/GkO1kJJn1Hs
