### ISSUE TITLE
Extremely poor audio quality

### ISSUE THREAD

**Issue by Khhs167** [kcat/openal-soft#891]
Hi!

I am currently working on a music player in C#, and I decided to use OpenAL for playback(seeing how that's the one library I know).

Everything in the project is fine and dandy, audio playback works great, *except* for the fact that low and high notes seem to be wiped off the surface of this planet!

I am converting from floating-point to 16-bit samples using this method due to the fact that FFmpeg(which I am using for audio loading) spits out 32-bit floats, but I'd like to stay in
int16 land(for better cross-platform support).
```cs
public static short PCMTo16(this float f)
{
    return (short)(Math.Clamp(f, -1.0f, 1.0f) * short.MaxValue);
}
```

My initialization logic for the source looks as following:
```cs
AL.Listener(ALListener3f.Position, 0, 0, 0);
AL.Listener(ALListenerfv.Orientation, new float[] { 0, 0, 1, 0, 1, 0 });

AL.Source(source, ALSourceb.SourceRelative, true);
AL.Source(source, ALSourcef.MaxDistance, float.MaxValue);
AL.Source(source, ALSourcef.RolloffFactor, 0);
AL.Source(source, ALSourcef.ConeOuterGain, 1);
AL.Source(source, ALSourcef.MaxGain, 1);
AL.Source(source, ALSourcef.MinGain, 1);
AL.Source(source, ALSource3f.Position, 0, 0, 0);
AL.Source(source, ALSource3f.Direction, 0, 0, 1);
AL.DistanceModel(ALDistanceModel.None);

if (EFX.IsExtensionPresent(audioDevice))
{
	AL.Source(source, ALSourceb.EfxAuxiliarySendFilterGainAuto, false);
	AL.Source(source, ALSourceb.EfxAuxiliarySendFilterGainHighFrequencyAuto, false);
	
	AL.Source(source, ALSourcei.EfxDirectFilter, 0);
	AL.Source(source, ALSourcef.EfxAirAbsorptionFactor, 0);
	AL.Source(source, ALSourcef.EfxRoomRolloffFactor, 0);
	AL.Source(source, ALSourcef.EfxConeOuterGainHighFrequency, 0);
}
```

I, uhm, I haven't got too much to say...
I attached a zip file that contains an ogg file which contains 2 recordings.  
First is the file being played back in VLC, secondly is the file being played back via OpenAL-soft.
I can confirm that if I just write the 16-bit PCM to disk it sounds the same as it does in VLC.
[dual.zip](https://github.com/kcat/openal-soft/files/12216295/dual.zip)

The config tool is acting kinda wack but I'll attach a couple screenshots of it too
![image](https://github.com/kcat/openal-soft/assets/34920681/db21d4b8-5a9f-4feb-8294-c625a38cfe13)
![image](https://github.com/kcat/openal-soft/assets/34920681/f9c78637-47a6-4ac0-9229-4118fe3e1678)
![image](https://github.com/kcat/openal-soft/assets/34920681/777b1fb4-f7f5-4147-9c6a-aa4b7ce2ddaf)

And a log file(with ALSOFT_LOGLEVEL=3)
[log.txt](https://github.com/kcat/openal-soft/files/12216330/log.txt)

System info:
```
OS: Arch Linux 6.4.2-arch1-1
Audio Backend: pipewire 0.3.73  (i think)
alsoft version: v1.23.1-d3875f33  (according to logs)
```

I hope this wasn't too poorly written!
And if there's anything extra you need to know from me, I'm glad to help!

**Comment by kcat** [comment]
A few things I notice about the configuration:

You seem to force Stereo 44.1khz. This is normally autodetected by the system and doesn't need to be set explicitly with OpenAL Soft, unless there's something wrong with the autodetection or you're using a backend that can't autodetect it. If the system is using something different, say 48khz, there can be adverse effects on quality from extra resampling.

You set the Stereo Mode to Speakers, but Stereo Encoding to Binaural. Binaural encoding is intended for headphones, and if you have headphones, Stereo Mode shouldn't be set to Speakers if you want output treated as headphones (which will cause OpenAL Soft to autoselect Binaural encoding when possible, so it doesn't need to be set explicitly).

Ambisonic Format is set to "ACN, FuMa", which is only used when the Channel configuration is set to one of the Ambisonic modes (which requires an appropriately configured external ambisonic decoder to listen to). "ACN, FuMa" is also an odd setup in those cases. It's best to leave that at the default if you don't know for sure what it needs to be.

Speaker Distance is set to 0.1 meters. This is only used for surround sound speaker output, when Near-Field Effects are enabled. It's best to leave that unset if not using near-field effects with quad, 5.1, etc output. Distance Compensation is also enabled, but is only used for surround sound speaker configurations with a custom decoder that has different speaker distances set. Best to leave that at the default if not needed.

You have the config file `/etc/xdg/alsoft.conf` which sets the `game_compat/drivers` config option, which isn't a recognized option and does nothing. Game Compat options also shouldn't be set in a global or user config file, since they're for game-specific tweaks, hacks, or workarounds, and shouldn't be applied to apps that don't explicitly need them.

There's also the `/etc/openal/alsoft.conf` config file that sets the `drivers=pulse` config option, forcing use of the PulseAudio backend. Unless there's a problem with the autoselected backend, that shouldn't be set so it can pick the preferred one based on availability.


All that out of the way, it seems the underlying cause is HRTF/Binaural output is being used. With that, multi-channel buffer formats are played with virtual panning and HRTF filtering, to sound as if it's played on external speakers (for more consistency with actual speaker output, and provide virtual surround sound). There are a few ways to deal with this if it's undesirable.

First, you can disable HRTF either by setting Stereo Encoding to Basic or using the [`ALC_SOFT_HRTF`](https://openal-soft.org/openal-extensions/SOFT_HRTF.txt) extension to disable it when creating a context. This will have the possibly-undesirable effect of not having any HRTF at all, even for 3D sources. It'll just be a flat stereo mix on headphones.

Alternatively, you can use the [`AL_SOFT_direct_channels_remix`](https://openal-soft.org/openal-extensions/SOFT_direct_channels_remix.txt) extension to bypass the virtual panning and HRTF filtering on specific multi-channel sources and play directly on the output channels. That'll allow you to play some sources without HRTF, while still allowing HRTF for others.

In either case, just be sure what you're playing is designed for the given output. With headphones, it's generally best to leave it on with a surround sound track to get virtual surround sound, and with a non-binaural stereo track, virtual panning may provide a better experience with less listening fatigue.

**Comment by mr-sihc** [comment]
Everything in the project is fine and dandy, audio playback works great, except for the fact that low and high notes seem to be wiped off the surface of this planet!

I wouldnt exactly call this `Extremely poor audio quality` like you did

and

YOU dont make the conversion from float to 16bit
you set `sample format` in the alsoft-config to whatever you want, 16bit for example,
DONT convert the audio

**Comment by Khhs167** [comment]
I thought I closed this issue 😅
Anyway, if I remember correctly this was an issue I managed to resolve after a couple hours of testing various settings, which eventually seemed to resolve itself with the disabling of HRTF(if I’m not mistaken).

I’ll close this now, since I solved the problem on my end.

**Comment by mr-sihc** [comment]
lol ok
