### ISSUE TITLE
Log level ignored if NDEBUG on Windows

### ISSUE THREAD

**Issue by FilippoLeon** [kcat/openal-soft#894]
Shouldn't all what is on the outside of the if be inside instead so that is only logged when the level is set accordingly?

https://github.com/kcat/openal-soft/blob/9296af5566afea4ba4cb78b374ef3ee0bf9bc04b/core/logging.cpp#L134

Not sure if it is by design, but doing that result in spamming the debug console with trace messages even if the log level is set to error.

**Comment by RusJJ** [comment]
NDEBUG - No Debug. In the code it's "!defined(NDEBUG)", which means if(DEBUG) (in other words)

**Comment by kcat** [comment]
`OutputDebugStringW` is used for debugging info. IIRC, when run under Visual Studio, it has an window pane for messages written with that call, but otherwise does nothing when run normally. It's also only called in non-Release builds. So writing that message is to provide debug info to anyone working with a debug/development build of OpenAL Soft in VS. Though the call lacks a severity parameter, putting it behind the environment variable there doesn't make much sense since it's already only for a non-release build under a development environment.

**Comment by FilippoLeon** [comment]
Makes sense.

I normally like to use RelWithDebInfo in CMake, which, if I see correctly does not set NDEBUG.

I am also using VS Code, which chooses to put OutputDebugStringW into the Debug Console.

Maybe one thing to consider would be to put it behing _DEBUG macro instead?

Anyhow, it is a non-issue then.
