### ISSUE TITLE
No spatialization when using effects

### ISSUE THREAD

**Issue by florianSasz** [kcat/openal-soft#897]
Hey! When I use an effect on a sound source it seems to disable the spatialization for the given source and also increases the volume a lot. For my uneducated ears it kind of sounds like going from a spatialized mono soure to an unspatialized stereo source? This is most apparent when I am using the flanger effect.
Am I doing something wrong or is it supposed to work like that?

**Comment by kcat** [comment]
It's somewhat expected. The effects are applied after panning/spatialization, and some effects like the equalizer effect do maintain spatialization by applying to each mixing channel. Some other effects are restricted to mono due to processing cost, like the pitch shifter effect that only processes and outputs a mono channel because the FFTs it uses are costly to apply to each channel.

Other effects, like chorus and flanger, explicitly output a stereo signal from a mono one. A mono signal is used for the input, and the left and right outputs can utilize different phase offsets for the LFO on the same input. I don't think it's supposed to act as if the sounds stay where they are while the left and right LFOs apply to the individual left and right channels, as it would create confusion for center and LFE channels that aren't left or right.

**Comment by florianSasz** [comment]
Ah ok, thank you!
