### ISSUE TITLE
alGetAuxiliaryEffectSloti -> AL_EFFECTSLOT_EFFECT result in AL_INVALID_ENUM

### ISSUE THREAD

**Issue by LordOfDragons** [kcat/openal-soft#900]
See topic. This call:

ALint value;
alGetAuxiliaryEffectSloti(effectSlot, AL_EFFECTSLOT_EFFECT, &value);

results in AL_INVALID_ENUM error. According to documentation AL_INVALID_ENUM is caused by unknown property identifier. But the documentation nlists AL_EFFECTSLOT_EFFECT as valid property identifier.

This bug makes it impossible to verify if OpenAL has an incorrect effect assigned to a slot.

**Comment by kcat** [comment]
The property can be set, but not queried. This is because, as per the EFX docs, when you set an effect on an effect slot, the effect properties are copied to the effect slot and not tied to it. You can modify or even delete the effect, and it doesn't affect the effect slot. Consequently, the effect ID value you could get back wouldn't necessarily represent the effect that the effect slot is using, or worse may not even be a valid effect ID anymore.

**Comment by LordOfDragons** [comment]
Maybe it would help then to update the documentation to state that this property can not be queried.

**Comment by kcat** [comment]
Unfortunately I'm not in control of the EFX docs, so I can't change or clarify it.

**Comment by LordOfDragons** [comment]
Forgot about that.

**Comment by kcat** [comment]
Having done some quick tests, it seems at least the Generic Software driver does allow querying it, and it returns the last set ID value regardless of whether the effect object associated with the ID has been changed or deleted. I don't know about Generic Hardware or the `ct_oal.dll` driver, but since Generic Software does, I suppose OpenAL Soft should too, for better compatibility if nothing else.

**Comment by kcat** [comment]
Fixed in commit 4b924e636b6e0651304b289a667d358d336d6d03.
