### ISSUE TITLE
makemhr feature request..... Non-uniform elevations on field distance error on sofa (EDIT!)

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#903]
Non-uniform elevations on field distance 1.000.
Got: -66.24, -61.20, -56.16, -51.12, -46.08, -41.04, -36.00, -30.96, -25.92, -20.88, -15.84, -10.80, -5.76, -0.72, +4.32, +9.36, +14.40, +19.44, +24.48, +29.52, +34.56, +39.60, +44.64, +49.68, +54.72, +59.76, +64.80, +69.84, +74.88, +79.92, +84.96
Using 0 of 2304 IRs.

EDIT: i would love to see if makemhr can be implemented the compatibilities for this type of sofa file, if at all possible. i have no clue how to use anything outside of makemhr for HRTFs, i would love to learn how to use other applications but i have a learning disability and for me to read it off a site doesnt help, i need one on one assistance till i get the hang of it.

**Comment by ThreeDeeJay** [comment]
I think makemhr has a hard requirement on elevations being uniform, but if that HRTF happens to be made in EAC, you might wanna try again with the custom option enabled https://github.com/davircarvalho/Individualized_HRTF_Synthesis/issues/7
Though you might still run into other issues like https://github.com/kcat/openal-soft/issues/774 or https://github.com/hoene/libmysofa/issues/195

That said, if you're really interested in that particular non-uniform HRTF, I'm not sure how to make it uniform 😔

**Comment by kcat** [comment]
For SOFA files, it should be possible to use `mysofa_getfilter_float` to retrieve interpolated HRIRs and construct a uniform layout from a non-uniform one. However, I can't speak to the quality if the interpolation (I've never tried it, or looked into the kind of interpolation it does), nor would I know how dense to make the reconstructed layout (it doesn't need to be too dense since OpenAL Soft interpolates the HRIRs itself when getting a filter for a given source position, but should be dense enough for the ambisonic decoders that don't interpolate HRIRs for the virtual speaker responses).

**Comment by TheBestKmanEver** [comment]
hm ok so this is outside my knowledge, thanks though
