### ISSUE TITLE
jack used as default plackback backend instead of pulse [1.19.1]

### ISSUE THREAD

**Issue by MadByteDE** [kcat/openal-soft#910]
[loginfo](https://gist.github.com/MadByteDE/f0b89f612890176429a066c3bef2bd98)

**OS:** Linux
**Distro:** Pop! OS 22.04 LTS
**Lib Version:** 1.19.1

I recently installed Pop! OS on my system and noticed that the game framework I use ([LÖVE](https://github.com/love2d/love)) was unable to play sounds. Using `ALSOFT_LOGLEVEL=3`  showed that openal is creating a new jack device for playback instead of using the pulse backend provided by pipewire-pulse.

If I set `ALSOFT_DRIVERS=pulse` the sound works as it should. 

Other apps seem to work fine (like Spotify, Firefox, Steam games).

I checked all config files but non of the shown config files existed except for the one at `/etc/openal/alsoft.conf`, but here everything seems to be commented out, nothing has been changed.

I'm not using jack at all, just alsa/pulse.

**Comment by kcat** [comment]
This is fixed in newer versions. Older versions made an (apparently bad) assumption that JACK would only be available when a user expressly wanted it, as it's more related to audio production for advanced users so normal users wouldn't be running it, so the JACK backend had a higher priority to be used when available (and skipped when not). But with PipeWire coming along with JACK compatibility, it became available even for normal users that don't know anything about it.

Starting with 1.22.0, the JACK backend priority is lowered so it's not automatically used over the PipeWire, PulseAudio, or ALSA backends.

**Comment by MadByteDE** [comment]
thanks for your explanation!

I'll try to upgrade the package and see if it works.

**Comment by MadByteDE** [comment]
Since this bug is already fixed in newer versions I'll close the issue. Thanks for the quick response.
