### ISSUE TITLE
No 3D sound on MacOS Apple Silicon

### ISSUE THREAD

**Issue by h4nkyn** [kcat/openal-soft#911]
**Platform**: MacOS 13.5.1
**Hardware**: 2021 Apple Macbook Pro 16" M1 Max
**Error**: No spatial audio

Unfortunately I have get 3D sound when using openal-soft. I am running MacOS Venture 13.5.1. I am quite familiar with spatial audio and I've exhausted just about every method of using OpenAL to create sound sources and play them in 3D space. However, even at far distances, the sound is completely centered. I'm not sure what's causing it. I can assure that I am receiving stereo audio but it is not positioned in 3D space in any sense. I am quite confused as openal-soft worked last year for me. Is there a recent update that has broken on newer MacOS versions? If anyone can help out it would be greatly appreciated.

**Comment by kcat** [comment]
The first thing to check is to make sure you're playing a mono sound. Stereo and other multi-channel buffer formats don't do 3D panning by default, so will always sound the same regardless of the source position.

Another thing to check is to make sure there aren't any errors being generated, by calling `alGetError` at various points after AL calls to get any error code there may be.

Otherwise, are you able to provide the source, at least as it pertains to using OpenAL? As far as I know, things should work fine on newer MacOS versions.

**Comment by h4nkyn** [comment]
You were absolutely right about the mono audio. I was playing a stereo the whole time. You saved me so many future headaches, thank you so much.
