### ISSUE TITLE
[Question] How does UHJ work?

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#914]
![image](https://github.com/kcat/openal-soft/assets/35676228/a468d550-e25d-421f-b4aa-5ade828937d0)
i have my stereo Encoding set to UHJ. i am curious how it treats just a plain stereo input and what it outputs. also am curious on is me not having a specific external decoder for UHJ if openal-soft will then decode it along with having my output set to s/pdif?? im really curious on how i can make the best use of it for my 2 channel stereo output? MPV is capable of downmixing audio into stereo via dl-dr channel selection and im pretty sure pipewire how a downmix too but idk if what im doing is, well... doing anything to my final heard output. the only decoder i would have is software. my audio interface is an AudioBox GO from Presonus.   researching this type of thing is such a pain on how you can actually use it without fancy hardware

**Comment by kcat** [comment]
OpenAL Soft will only decode UHJ when playing a buffer with a UHJ format.

I think there might be some confusion with what UHJ is. It's a transmission format that doubles as an alternate method of stereo mixing. There's no point to decode UHJ right after encoding it; you just get a slightly worse version of the original input. Since you say you have a stereo system, the only reason to encode to UHJ is if you prefer the way it sounds over a plain pairwise/panpot mix, or if you want to make a recording (or stream) in stereo that can optionally be decoded back to surround sound later (or by the listener of the stream).

**Comment by TheBestKmanEver** [comment]
ok so for me set alsoft.conf with stereo-encoding=uhj is pointless for my use case??

**Comment by kcat** [comment]
> ok so for me set alsoft.conf with stereo-encoding=uhj is pointless for my use case??

Depends if you like how UHJ sounds or not. It's perfectly fine to use even if it's just to play as stereo, since it is designed to be compatible with stereo playback. The way UHJ works creates a wide stereo effect, which can make sufficiently panned sounds seem to come from outside the two speakers. So it wouldn't be pointless if you like the way it sounds.

> and what about setting my channels=ambi# instead?? will that do anything for my use case? or is ambisonics only compatible for use on 3+ speaker setups?

As the configuration option says, "Note that the ambi* configurations output ambisonic channels of the given order (using ACN ordering and SN3D normalization by default), which need to be decoded to play correctly on speakers." If you try to output ambi* channels, it will output ambisonic channels if possible, which aren't intended to play directly on speakers no matter how many there are.

> what i'm wanting to achieve is to run a 3D-ish (180 degree) sound for things like movies

If UHJ isn't good enough for that, there isn't really a good option if you just have stereo speakers. People have tried over the decades to create a surround sound effect with stereo speakers, but they're finicky, often requiring very specific listener placement with specialized filters and/or specialized setups.

**Comment by TheBestKmanEver** [comment]
hm ok. well that kinda sucks... thanks for the info on this though
