### ISSUE TITLE
[request] display which HRTF is selected in 'openal-info'

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#927]
i would like to see which HRTF is selected when i run 'openal-info'
preferably as an asterisk (*) beside it like how it lists which resampler is in use 
"Available resamplers:
    Nearest
    ...
    23rd order Sinc *"

running openal-info shows this for HRTF
"Available HRTFs:
    mesh2
    Default HRTF
    Built-In HRTF  
Device output mode: Stereo (HRTF)"

**Comment by kcat** [comment]
With HRTF, it's currently such that the first listed HRTF is the default that gets used, if the app doesn't request otherwise. Unless it fails to load for some reason, then it goes down the list. Though that behavior can change if a default HRTF ID query gets added instead of always making the default first.

That said, commit a90d8a6f92536111b970e12b4c83da8a82e48f2f adds a "Device HRTF profile: ..." line to report what HRTF (if any) is being used.
