### ISSUE TITLE
Gears of War (2007) no audio

### ISSUE THREAD

**Issue by AronNemeth2001** [kcat/openal-soft#929]
I tired replacing the Creative Openal32.dll in the game's directory for HRTF support by copying the proper OpenAL Soft binary and renaming it, but the game has no audio whatsoever if I do that.

Alsoft log contents:

[ALSOFT] (II) Initializing library v1.23.1-d3875f33 master
[ALSOFT] (II) Supported backends: wasapi, dsound, winmm, null, wave
[ALSOFT] (II) Loading config C:\Users\Aaron\AppData\Roaming\alsoft.ini...
[ALSOFT] (II) Got binary: C:\Games\DODI-Repacks\Gears of War\Binaries, wargame-g4wlive.exe
[ALSOFT] (II) Loading config C:\Games\DODI-Repacks\Gears of War\Binaries\alsoft.ini...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD Ryzen 5 5600 6-Core Processor"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key rt-time-limit not found
[ALSOFT] (II) Key game_compat/enable-sub-data-ext not found
[ALSOFT] (II) Key game_compat/reverse-x not found
[ALSOFT] (II) Key game_compat/reverse-y not found
[ALSOFT] (II) Key game_compat/reverse-z not found
[ALSOFT] (II) Key game_compat/nfc-scale not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key uhj/decode-filter not found
[ALSOFT] (II) Key uhj/filter not found
[ALSOFT] (II) Key uhj/encode-filter not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Initialized backend "wasapi"
[ALSOFT] (II) Added "wasapi" for playback
[ALSOFT] (II) Added "wasapi" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Key eax/enable not found
[ALSOFT] (II) Opening playback device "Generic Software"
[ALSOFT] (II) Starting message thread
[ALSOFT] (II) Starting message loop
[ALSOFT] (II) Got message "Enumerate Playback" (0x0005, this=1b375cf0, param=00000000)
[ALSOFT] (II) Got device "Hangszórók (Realtek(R) Audio)", "{16FA2F64-A4AB-4114-9DAF-BE11C1CFD8AD}", "{0.0.0.00000000}.{16fa2f64-a4ab-4114-9daf-be11c1cfd8ad}"
[ALSOFT] (II) Got device "XB253Q (NVIDIA High Definition Audio)", "{087222DB-0708-4B14-9EAF-AC1E2EB12C83}", "{0.0.0.00000000}.{087222db-0708-4b14-9eaf-ac1e2eb12c83}"
[ALSOFT] (II) Got device "Realtek Digital Output (Realtek(R) Audio)", "{FBF0CAAF-3199-4001-8A1B-44EE985A4888}", "{0.0.0.00000000}.{fbf0caaf-3199-4001-8a1b-44ee985a4888}"
[ALSOFT] (II) Got message "Open Device" (0x0000, this=1b375cf0, param=024dd9f0)
[ALSOFT] (WW) Failed to find device name matching "Generic Software"
[ALSOFT] (II) Message loop finished
[ALSOFT] (WW) Failed to open playback device: Device init failed: 0x80004005
[ALSOFT] (WW) Error generated on device 00000000, code 0xa004
[ALSOFT] (II) Freeing device 1b377cc0
[ALSOFT] (WW) Error generated on device 00000000, code 0xa002
[ALSOFT] (WW) Error generated on device 00000000, code 0xa002
[ALSOFT] (WW) Error generated on device 00000000, code 0xa001

**Comment by kcat** [comment]
Looks like the game is trying to open `"Generic Software"`. Is there a setting somewhere in the game's options or config file, or is it hardcoded to always open that device name? If the game's hardcoded to use it, OpenAL Soft will need a new feature to support that name.

**Comment by AronNemeth2001** [comment]
Thanks for your tip: I checked the games config file, and there was an option for the name of the audio device. I changed it to OpenAL Soft, and it now works perfectly!

**Comment by mirh** [comment]
So... I almost got scammed by the decrepit unreal warfare leaked sources (which are hardcoded to use *DirectSound*), and by some lazy disassemble of `WarGame-G4WLive.exe` (the audio player widget in FaceFX studio's animation tab can use openal, and somefuckinghow it ends up linked in the game executable).
Then, miraculously, I found the v3340 build leak (i.e. the final 1.2 retail release) and it turns out the \*code\* doesn't really have any sort of preferential selection mechanism or bias (besides whatever opportunistic order the device/dll names create alphabetically). 

On the other hand both the "root" `BaseEngine.ini`, `BaseEngineUserSettings.ini`, `WarEngine.ini`, `WarEngineG4WLive.ini` and `WarEngineUserSettings.ini` already ship with ALAudioDevice set to *Generic Software* (god knows how their precedence relations and initialization work though). While satsun didn't seem to [report](https://satsun.org/audio/) any particular problem with his top notch ideal setup. 

So, I'm kinda split 50-50 on whether this would be that one UE3 game where *for once* the ***DeviceName=*** trick is actually 100% required.. Or if everybody and their aunt on the net have been recommending it (like in mass effect) just because of the ever missing #757 not selecting the native openal device for ALC_DEFAULT_DEVICE_SPECIFIER.

**Comment by ThreeDeeJay** [comment]
> Looks like the game is trying to open `"Generic Software"`. Is there a setting somewhere in the game's options or config file, or is it hardcoded to always open that device name? If the game's hardcoded to use it, OpenAL Soft will need a new feature to support that name.

@kcat A [masquerade](http://www.blueripplesound.com/compatible_openal_games) feature would be neat in case OpenAL Soft ignoring the requested device (or maybe even faking it on-the-fly) doesn't work and for [games that may reset/overwrite the INI values](https://www.youtube.com/watch?v=zO1XuqJUPu0) (perhaps because people don't edit the base INIs?). Maybe even take it a step further: adding settings for user-specified device name and even [vendor, etc. for those pesky game/Creative hardware locks](https://github.com/kcat/openal-soft/issues/1001#issuecomment-2327609551) without needing wrap_oal "Generic Software"/"Generic Hardware">DirectSound3D>DSOAL>OpenAL Soft if possible.

> While satsun didn't seem to [report](https://satsun.org/audio/) any particular problem with his top notch ideal setup.

There's this:

> **Gears of War** initially had some strange issues for me, such as the side surround speakers not working properly. WarEngine.ini seems to indicate that it's an OpenAL game, but if I use ALchemy, which puts its own DSOUND.DLL file in the game directory, the game won't load because it doesn't like the DSOUND.DLL file. While the game appears to be using OpenAL, I believe that in the end it's routing through DirectSound. I've removed any OpenAL-related files from the BINARIES directory and while the INI updates OpenAL parameters, it still wants to talk to DSOUND.DLL.

Wonder if he forgot to remove wrap_oal or if the game just uses dsound for non-positional audio like FMVs and such

**Comment by mirh** [comment]
> A masquerade feature would be neat 

That's a bit of a silly workaround tbh.. Very weird from people that supposedly did know how to browse the router source code.

> in case OpenAL Soft ignoring the requested device (or maybe even faking it on-the-fly) doesn't work

The masquerade ***is*** faking the device on the fly.. ?

> and for games that may reset/overwrite the INI values

That has [always](https://old.reddit.com/r/masseffect/comments/f6s91y/me_modding/fi8imq0/) been BS. A ini resetting itself doesn't make sense because (duh) the whole point is that you save your settings, isn't it? And it wouldn't just affect audio. 

>  for those pesky game/Creative hardware locks 

To be super fair I'm kinda re-evaluating their evil here. Having checks left and right in the oal 1.0 times wasn't that odd, and admittedly by the time 1.1 was out the renderer=device names expectations still seemed solid.

> Wonder if he forgot to remove wrap_oal or if the game just uses dsound for non-positional audio like FMVs and such

Just about any game uses it for bink. 
That aside, if the game was already started once and it had set a *DeviceName* already that could be it too

**Comment by ThreeDeeJay** [comment]
> The masquerade _**is**_ faking the device on the fly.. ?

My understanding is that masquerading uses a specific device name like/only? "Generic Software"
By faking I meant OpenAL Soft would automatically pretend to be whatever device name is requested, if that makes sense.

> That has [always](https://old.reddit.com/r/masseffect/comments/f6s91y/me_modding/fi8imq0/) been BS. A ini resetting itself doesn't make sense because (duh) the whole point is that you save your settings, isn't it? And it wouldn't just affect audio.

I think I've ran into that problem myself at one point so I just wanted to be on the safe side.

**Comment by mirh** [comment]
> By faking I meant OpenAL Soft would automatically pretend to be whatever device name is requested, if that makes sense.

Yes and no, their explanations are a bit strange. 
Despite the fact that if it was just up to your own dll exclusively, you could just return success to every query regardless of the name and call it a day.. I can see why they might not have wanted to also overwrite the system openal32.dll (fear that potentially newer openal installers could overwrite it, respect, courtesy or simply not wanting to disrupt the system too much). 
And once that's decided, it follows that you might then start to look for other shortcuts (for instance I timidly believe Mass Effect SHOULD just go with the wind of whatever the router chooses for it.. but if on the first launch you just have generic software or if you toggle the in-game "hardware audio" button then you it will default to it and stay like that unless you touch the .ini). 

But it's strange that the games they are actually recommending this with are the relatively new ones, which aren't discriminating against anybody (and in fact don't even tend to handle enumeration themselves).
Meanwhile with the *actually old* UE2 stuff they just said to replace the default dll. 

> I think I've ran into that problem myself at one point so I just wanted to be on the safe side.

The problem is just #757.
(the .inis are like meant to be modified, duh.. putting aside there should be also command line parameters to avoid auto-refresh)
