### ISSUE TITLE
Creating to many threads

### ISSUE THREAD

**Issue by DevAlgos** [kcat/openal-soft#946]
Currently I am making an audio system using openal, however on initializing the library seems to create 31 threads , is there any way to set a limit? The code I am using is the example code in alplay.c, and I have not seen anything in the documentation where I can control this.

**Comment by kcat** [comment]
OpenAL Soft only creates the threads it needs (one for handling event callbacks, and one for handling the actual audio processing and device output). Any other threads are either necessary backend-specific functionality (e.g. PipeWire needs another thread for handling non-device-specific events from the server, WASAPI has another thread to make COM calls on), or are internal to the audio API itself (e.g. ALSA plugins may have their own threads running to handle external events or processing). In either case, there's not really anything OpenAL can do to limit them since they're necessary to function.
