### ISSUE TITLE
[Request] display selected reverb in 'openal-info' 

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#949]
and also add the ability to change the reverb boost within 'alsoft-config'

**Comment by kcat** [comment]
There isn't a "selected reverb" in OpenAL, just whatever effect parameters the app sets on a given effect slot object. The "default reverb" is a hack that sets up an internal reverb effect that's applied to sources that don't have a send set.

The reverb boost needs to be handled carefully since it can result in the reverb being too loud or too quiet than intended.
