### ISSUE TITLE
Openal crashes Minecraft with pipewire

### ISSUE THREAD

**Issue by Farmer-Markus** [kcat/openal-soft#957]
Sometimes when i'm starting minecraft, the game crashes 3 to 4 times befor launching correctly. After putting an .alsoftrc file with (drivers=alsa) into my home direktory all works fine.

**Comment by kcat** [comment]
Are you able to get a crash log or backtrace? I'm not sure if Java may get in the way, but you can also try to get an OpenAL Soft log, by setting the `ALSOFT_LOGLEVEL` environment variable to `3` when running the game (and maybe also `ALSOFT_LOGFILE` to a full path+filename to write the log to; make sure you have write permission to the given path).

**Comment by Farmer-Markus** [comment]
I'm using ATLauncher to start  minecraft. This is my first report, if I should post my log as text tell me please...
[ATLauncherLog.txt](https://github.com/kcat/openal-soft/files/13849775/ATLauncherLog.txt)

**Comment by Farmer-Markus** [comment]
how can i post a comment without closing issue?

**Comment by Farmer-Markus** [comment]
oh i'm just clicking on wrong button :D sorry

**Comment by Farmer-Markus** [comment]
And alsoft log: 
[alsoftlog.txt](https://github.com/kcat/openal-soft/files/13849798/alsoftlog.txt)

**Comment by kcat** [comment]
It looks like it's an older version from before PipeWire was natively supported, and is trying to use the JACK backend with PipeWire's JACK compatibility. That should generally work (if not ideal), though, and those logs unfortunately don't show where the crash is actually happening. It does mention there should be a `**USERSDIR**/instances/Minecraft1201CreatePack/hs_err_pid5277.log` log file with more information. Does that file still exist?

As a workaround, you can disable the JACK backend by adding the lines:
```
[general]
drivers=-jack,
```
to the alsoft config file, which will make older versions of OpenAL Soft use the PulseAudio backend instead, which should work better than both JACK and ALSA with PipeWire.

**Comment by Farmer-Markus** [comment]
Is there another way to force alsoft to use an other driver without creating an file? Set an variable or launch command?

the file still exists
[hs_err_pid5277.log](https://github.com/kcat/openal-soft/files/13853722/hs_err_pid5277.log)

**Comment by kcat** [comment]
You can set the `ALSOFT_DRIVERS` environment variable to the same thing ("`-jack,`"), assuming Java doesn't clear the environment variables that native libraries can see. If it does clear the environment variables, and there's no way to specify custom ones for the app when launching Java, then unfortunately the config file is the only other way to influence OpenAL Soft's backend selection.

That log file does narrow it down a bit, though the actual issue is still elusive. It seems to be crashing in a call to `alcGetIntegerv` when it tries to calculate `device->Frequency / device->UpdateSize`, with a `SIGFPE` indicating an integer-divide-by-zero. That would mean `UpdateSize` is 0, although the log shows it was 1024. I don't know why `jack_get_buffer_size` suddenly returns 0 afterward, it's not something I see happen here (with either PipeWire-JACK, or native JACK without PipeWire). The crash log shows it loaded PipeWire's libjack, so it's got the correct library to use with PipeWire.

Perhaps there's an issue with that version of PipeWire-JACK you have, that OpenAL Soft doesn't handle well. I have 1.0.0 installed here, which might be a bit out of date by now. Otherwise if it's not PipeWire-JACK misbehaving and reporting 0, perhaps there's some memory corruption overwriting that struct member with 0, but I don't know where or why that would happen either.

**Comment by Farmer-Markus** [comment]
Ok thanks for the information, I will close this issue if you don't want another log file or questions. Thank you very much for your answer and have a nice day :)
