### ISSUE TITLE
Ok to add ALC_API to alcReopenDeviceSOFT?

### ISSUE THREAD

**Issue by doobah** [kcat/openal-soft#959]
I'm attempting to write pinvoke bindings to openal-soft for a .net wrapper, and was wondering whether there is any reason why alcReopenDeviceSOFT shouldn't be exported? As in prepending it with ALC_API
https://github.com/kcat/openal-soft/blame/b81a270f6c1e795ca70d7684e0ccf35a19f247e2/include/AL/alext.h#L574

**Comment by kcat** [comment]
The main reason is because it's not standard, and calling it directly puts a runtime requirement on the function existing so it wouldn't work with OpenAL DLLs that don't have it (e.g. the router on Windows, where it would still be available on OpenAL Soft devices but not directly from `OpenAL32.dll` itself).

**Comment by okaniku** [comment]
I see, I'm guessing the proper way then would be to make a binding for alcGetProcAddress(), then use that to get pointers to the non-standard functions?
