### ISSUE TITLE
Severe Audio Degredation over recent builds

### ISSUE THREAD

**Issue by Jenavieve-Rose** [kcat/openal-soft#967]
Over the last week or two noticed some odd audio issues starting to pop up kept trying newer updates (using builds from artifacts) and the issue has progressively gotten worse. You can here it most distinctly in this video of Dhewm3 using the latest build. I have included the alsoft log file as well. 

build used
https://github.com/kcat/openal-soft/commit/358fee381e2d0d6f56f8dcc4e2eeda7449270545

https://www.youtube.com/watch?v=dUUuwJj1g0s

[alsoft_error.txt](https://github.com/kcat/openal-soft/files/14106170/alsoft_error.txt)

**Comment by kcat** [comment]
Are you able to make a recording and provide a log file from an earlier build that was working?

I can hear something wrong in that video, which I'm not hearing in my builds. Which suggests something different with what MSVC is doing with recent changes. If you're able to find the latest build that sounds fine, that would also be helpful to pinpoint the change causing the issue.

**Comment by Jenavieve-Rose** [comment]
So went back to the 25th and the severe audio issues are gone that you heard in Doom 3 however this is around when i started to notice the sound issues. It started off as an echo present in a lot of OpenAl-Soft games. It's best heard here in Prey 06. 

Build Used 
https://github.com/kcat/openal-soft/commit/c40720363be8411f0a6098f956484e60cf586f4a

https://www.youtube.com/watch?v=py1sVmpf2AY

Video May still be processing as I post this.

[alsoft_error.txt](https://github.com/kcat/openal-soft/files/14107065/alsoft_error.txt)

**Comment by kcat** [comment]
The echo in Prey and other games may be due to earlier changes trying to balance the reverb levels (late December and early January). Something that's proving to be impossible, as something always ends up too loud (where you get a kind of buzz or very sharp echo) or too quiet (where it's basically inaudible). It's not helped by my attempts to find examples of real hardware having very different levels too, some way worse/louder than OpenAL Soft ever was. As it is, it's applying the gains more or less as specified, and is close to the output levels of Generic Software. There's certainly room for tweaking it more, but there needs to be more detailed tests and comparisons.

Prey also uses the legacy EAX API, which may introduce issues with the conversion from EAX to EFX.

The audio in the Dhewm3 video seems to be unexpectedly scratchy, though. I don't think that's the reverb causing it since it happens in the intro video, which I don't think uses the reverb effect. Especially since it doesn't seem to be happening for me, that may mean it's a more general OS/backend or compiler-based issue.

**Comment by Jenavieve-Rose** [comment]
So The info to Doom 3 does use reverb. Now I can't say for certain the scratchiness is related to reverb but it only shows up in games that use reverb. Games that don't have reverb it mostly does not seem to show up at all. And it is most noticeable in heavy reverb scenes. It seems to affect OpenAL games the most. So any game that uses OpenAL or a port or mod that incorporates it. Games that use DSOAL to access it don't seem to have the issue or its not as noticeable.

**Comment by kcat** [comment]
Okay, I found an issue introduced in commit e8f8b16aee71fc6832e8f6c75b3771ea00582057 that could be triggered by an update size that's not a clean multiple of 256 or an update size that regularly changes. Some of the feedback buffers in the reverb effect got misaligned, causing the feedback duration to constantly change. That would explain why I didn't hear it, since PipeWire provides a consistent update size that's a power of 2, whereas WASAPI uses multiples of 10ms (1/100th the same rate). This should be fixed now in commit b8b207ab97e52c2bbf391505e984008c2e01784a.

The reverb issue in Prey is different, and may indicate some changes to the gain are needed. It's interesting to note that the game seems to use all 4 effect slots available to EAX, which suggests more dynamic environment effect modelling and steering. There aren't too many games that do that, which could compound any gain balance issues.

**Comment by Jenavieve-Rose** [comment]
yeah that absolutely did fix the static issue on my end thanks.
