### ISSUE TITLE
Remove limitation of of 256 sources

### ISSUE THREAD

**Issue by DebugBSD** [kcat/openal-soft#972]
Hi, good morning!

I don't know if this question has been solved before. I have been looking for something similar but I haven't found anything. 

My question is about removing the limit of 256 sources. I mean, I have one scene with thousands of game objects and most of those objest have sounds. The problem is on Windows, when I run the application I get the error:

`[ALSOFT] (WW) Error generated on context 0000024264BFAE10, code 0xa005, "Exceeding 256 source limit (256 + 1)"`

After that error, there is no sound. (I mean, the sound does not works for each object in the scene).

I don't have this kind of problem on Linux. Just on Windows 11.

The version of OpenAL I'm using comes from main branch of github. I built the version from source code.

**Comment by kcat** [comment]
If you request a higher number of sources at context creation, you can allocate more:
```c
ALCint attributes[] = {
    ALC_MONO_SOURCES, 1024,
    0 /* end of list */
};
context = alcCreateContext(device, attributes);
```
You can then query the device with `alcGetIntegerv` to see how many `ALC_MONO_SOURCES` and `ALC_STEREO_SOURCES` are available. (OpenAL Soft treats all sources equally; it doesn't matter how many are set to be "mono" or "stereo", if you have a source you can play a buffer of any available channel configuration with it).

However, it's generally a good idea to use a dynamic source pool, where you have a pool of available sources and take a source when a sound needs to be played, and put it back when it's done playing, rather than assigning a source to an object for the lifetime of the object. Especially given a distance threshold (you don't need to play sounds that are far enough away that you can't hear them) and a priority system (where more important sounds can preempt/stop less important ones and take their source if there are none available), you won't normally need more than a few dozen or maybe a hundred sources playing simultaneously.

**Comment by DebugBSD** [comment]
Thank you so much for your support and suggestion. I'll look for dynamic source pool to see how to use it.
