### ISSUE TITLE
Resampled delay exceeds max (84.50 > 63) when at 96k (non-issue)

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#974]
not really an issue as it's just a Warn but if my system is at 96k 'openal-info' will have "[ALSOFT] (WW) Resampled delay exceeds max (84.50 > 63)" spat out under 'available events'

**Comment by kcat** [comment]
The delay is referring to the HRTF ear delay, how many samples between the sound being started and it reaching one of the ears from the given position. Since it's sample-based, and there's a limit to the number of samples it can delay in the mixing buffer, higher sample rates will have a higher number of samples to delay, which can exceed that limit.

With HRTF in particular, higher sample rates have a significant impact on performance. Playback shouldn't really be higher than 48khz, there's no real benefit but many downsides.
