### ISSUE TITLE
Muffled sound with Cubic resampler ever since using Gaussian filter.

### ISSUE THREAD

**Issue by geneotech** [kcat/openal-soft#985]
Hello! [My game](https://github.com/TeamHypersomnia/Hypersomnia) currently ships with 44.1 kHz sound effects and I'm testing on 48.0 kHz headphones - the quality was perfect until I recently upgraded to the latest OpenAL-soft version.

I narrowed it down to the commit that replaces Cubic Spline with Gaussian Filter for the Cubic resampler.
For reference:

Last good commit ba12551b69eeea411ea46593fc1f0d2c87b9d65c :

https://github.com/kcat/openal-soft/assets/3588717/82241914-59ab-44b9-b6f3-85013afe5259

Breaking commit e6c2df10e91d6bdb888e32520a4f32587e8c7c13 :

https://github.com/kcat/openal-soft/assets/3588717/ad14ea07-c5fa-48b8-b28a-974f8deb2a99

It's subtle, but the second clip sounds a little muffled (as if heard through wall).
As it stands even Linear/Point are way closer than Cubic to the original.
These clips were recorded with identical conditions, sound/device/volume settings etc. The only thing that differed is the commit, and it's reproducible every time.
Also - for some reason this mostly happens on Windows (testing on Windows 11). I had this issue for a while on my Arch Linux but it disappeared after upgrading the system today (it did update pipewire and libpipewire but I'm still surprised since PulseAudio is the chosen backend - the resampler is still being run as I checked it by inserting junk values into ``GaussFilterArray::GetCoeff``).
Maybe the gaussian filter is applied over all samples by accident? I'm also using clang 16.0.4 to build on Windows and 17.0.6 on Linux.

Original muzzle shot sound for reference:
https://github.com/TeamHypersomnia/Hypersomnia/raw/master/hypersomnia/content/sfx/szturm_muzzle_1.ogg

**Comment by geneotech** [comment]
Hey, thank you for the prompt and detailed response! And thank you for creating such an amazing library, I've been happily shipping with it for nearly a decade now!

I confirmed HRTF is not a factor here as:
- I'm using ``AL_DIRECT_CHANNELS_SOFT`` for the shot sounds.
- To double-check, I tried with HRTF both enabled/disabled - checked status on device too - and the behavior is identical.
(I'm well aware that HRTF _without_ direct channels causes the exact same muffled effect)

To debug, I just tried to output to ``wave`` backend on both OSes.
I'm now getting consistent results - the exact discrepancy can be heard on Linux.
Here are the completely unedited ``wave`` outputs for reference:

Commit e6c2df10e91d6bdb888e32520a4f32587e8c7c13 (bad):
https://sndup.net/q3f2/

Commit ba12551b69eeea411ea46593fc1f0d2c87b9d65c (good):
https://sndup.net/qf3d/

I'm not well versed in sound physics, however from your description I understand the Gaussian filter is supposed to be cutting the high frequencies - but once again should this effect be this much noticeable? It seems that the cubic spline at the very least is way closer to the original. Is Gaussian supposed to be muffling so much? Here's a test of these same two sound effects put next to each other in Audacity and exported to 48.0 kHz: http://sndup.net/v2wz/ For me it sounds almost exactly like the 'good' version one commit before the Gaussian filter.

_(The first sound here is a backpack wear sound)_

Also - I just realized the reason this _didn't_ happen for me on Linux (i.e. I had crisp playback on both the _good_ and _bad_ commit) was ``pulse`` - outputting to ``alsa`` again reproduces the bad behavior. I was wondering if it's because ``pulse`` has a ``fix-rate`` option, but the playback is for some reason crisp with both ``true`` and ``false`` values, on both _good_ and _bad_ commits.

**Comment by kcat** [comment]
> Still, it seems that the cubic spline at the very least is way closer to the original.

The spline filter keeps more of the high frequencies unattenuated, but that comes at the cost of more harmonic distortion. When it comes to a lot of DSP operations, you're very often faced with trade-offs like these. Less attenuation of the original sound will lead to more distortion with the sound, while suppressing the distortion will affect more of the original sound. Improving the quality overall will require more CPU use, while reducing CPU use will make the distortion trade-off more apparent.

> Is Gaussian supposed to be muffling so much?

It's about what I'd expect, given the size of the filter being only 4 samples. The amount of high frequency attenuation is rather subtle, relatively speaking, having a non-negligible effect on the distortion and not being too aggressive on the original sound. Possibly there's room to improve the coefficients for a higher cutoff frequency, but I wouldn't expect too much wiggleroom without sacrificing quality.

The available resamplers are intended to give users the option to balance performance vs quality given how much CPU power is available and how important audio quality is. The current gaussian filter I feel fits well between linear and bsinc12 in both metrics. It does better at suppressing distortion than linear but not as much as bsinc12, while it is more efficient than bsinc12 but not as fast as linear. In comparison, the spline filter seems closer to linear in terms of quality, not having as much effect on the high frequencies or distortion, but is the same performance as gaussian despite that.

That's why I suggested the linear resampler if you wanted to keep more of the higher frequencies without being too concerned about harmonic distortion, as it gives a similar filter response while being more efficient to process than spline. So it really comes down to how different linear and spline are, and if the latter is needed given the former. If there's enough quality difference between linear and spline, it could be worth having spline and guassian as separate options, but I'd need more convincing since my measurements only show a very minor difference in the highest frequencies.

**Comment by geneotech** [comment]
So - I followed your advice about checking out Linear. Indeed - it's a **lot better** than Gaussian for my aesthetic. I tested it against the original Cubic however, and it makes some key sounds like silenced gunshots _marginally_ less snappier which makes me still prefer Cubic.

For what it's worth, I'm now porting the game to the Web and the Web Audio API seems to choose a resampling method that preserves the higher frequencies and thus the _snappiness_ of the gunshot, thus sounding almost exactly like the original, just like the Cubic. Here's the test:  

https://github.com/kcat/openal-soft/assets/3588717/4c41ad88-aa9b-4c42-a7ec-aaab5c054dbf

1. Playing the original sound directly via mpv
2. Build with the original Cubic (sounds identical to the original)
3. Build on the Web (sounds identical to the original)
4. Build with Linear (marginally muffled although barely noticeable)
5. Once again Cubic for reference
6. Once Linear for reference

Opened in audacity:
![image](https://github.com/kcat/openal-soft/assets/3588717/4e176c8a-28ff-4411-9b79-ff1a25a4b092)


This does confirm my impression that the Linear filter tends to remove the initial _snap_ which is very important for how the gunshot feels, whereas Cubic, is, well, just plain awesome :grin:

Of course, this is all just my biased aesthetic preference, and it might be because 1) I've been using Cubic so long and Hypersomnia is _extremely_ competitive so you're getting _really familiar_ with specific sounds 2) the game has a pixely art style so it goes better even with a little harmonic distortion rather than a muffle. I understand others may have different requirements.

I even saw the commit dc61e7c59d24fb4422c3ea939eeb32ef2f4038c4 that introduced the original Cubic as claiming it's better than Linear - therefore if the issue is performance vs quality tradeoff - I see Cubic as a perfect library default since any potential library user will likely first test it in a low-overhead scenario, and it will right away appease audiophiles like us who can spot the marginal quality difference. In the unlikely event that it starts causing lags when they start using it at scale (I honestly never had problems with OpenAL-Soft even in chaotic battles), they can always choose a cheaper resampler to squeeze every CPU cycle - especially since it's way easier to measure, no need to have good headphones etc. This seems to me like the way to go rather than choosing a safe and fast resampler that could potentially make a bad first impression on audiophiles who first use the library.

**Comment by kcat** [comment]
It's possible `pulse` could be setting 44.1khz playback for some reason, causing OpenAL Soft to skip its resampler when playing a 44.1khz sound. PulseAudio (and PipeWire, WASAPI, etc) can then use its own higher quality resamplers to do 44.1->48khz since they don't have to worry about resampling possibly hundreds of sounds at the same time (or necessarily be concerned with on-the-fly rate changes). Audacity can use even higher quality resamplers since it doesn't need to work in real-time. But like I said, there's potentially room for at least some improvement with OpenAL Soft's resamplers.

In either case, I added back the cubic spline resampler with commit fdd16434c663b68fbddd6fe2c97a9e0c66b1f15e. The previous (recent) cubic resampler was renamed to `gaussian` (`cubic` will be treated as `guassian` and is still the default), and `spline` is a new option alongside it.

**Comment by geneotech** [comment]
Nice! 🎉🎉 God's work sir, just tested it, ``spline`` sounds again just like I loved it before. Thank you so much for your consideration!
