### ISSUE TITLE
EFX echo effect sounds incorrect on Windows with v17.

### ISSUE THREAD

**Issue by hgsz** [kcat/openal-soft#99]
The EFX echo effect does not sound correct on Windows 7 in version 17.  It sounds fine with version 16, Creative's version, and on *nix with any version.

I've also noticed that sounds (specifically mono sounds) are a bit muffled in v17 on Windows.  I'm not sure if this is related to [this issue](https://github.com/kcat/openal-soft/issues/72).  Like with the echo issue, everything sounds fine with version 16, Creative's version, and on *nix with any version.

I put together a small [sample project](https://github.com/hgsz/OpenALSoftEchoBug) reproducing the issue.  I've included the [sound I tested with and recordings](https://github.com/hgsz/OpenALSoftEchoBug/tree/master/sounds) of the sound on different systems and OpenAL versions.

**Comment by kcat** [comment]
From what I can tell, the "muffling" seems to be caused by the high-quality ```bsinc``` (band-limited sinc) resampler in combination with the low sample rate of the sound file. The default ```linear``` resampler, along with the ```sinc4``` resampler, don't perform any anti-aliasing, so on a 11025hz sound, you'll get aliasing noise at and above 5512hz. This can make the sound seem "brighter" and less muffled, since the noise is well within the audible range, but it's purely an aliasing artifact since a sound file can't contain any frequency content above half its sample rate (the nyquist frequency).

The ```bsinc``` resampler reduces this aliasing noise by -60dB, so it can seem like higher frequencies are missing that you otherwise hear with ```linear``` or ```sinc4```. But those frequencies never really existed with such a low sample rate sound. It should be noted that, since signal processing algorithms like this are inherently imperfect, the 0dB to -60dB transition isn't instantaneous. Some of the higher frequencies that do exist will start attenuating a bit as it goes to reach -60dB at the nyquist frequency, which can add to the "muffling". So there is room for improvement by making a sharper transition, but it would come at the cost of more processing time and/or memory. And even with a perfect resampler, a 11025hz sample rate sound can't have frequency content above 5512hz, so it can only do so much.

The proper fix would be to get the original sound with a higher sample rate (22 or 44khz, instead of 11khz), so that you have more of the missing frequency content and it's naturally "bright". Alternatively, if you want the aliasing noise to make the sound "brighter" regardless of the resampler being used, you can pre-apply a linear resampler to make a 22khz sound.

**Comment by hgsz** [comment]
What about the echo effect?  Why does it sound different on Windows versus *nix?  Is this an algorithm issue or a backend issue?

**Comment by kcat** [comment]
Looks like there was also a bug with calculating the echo damping amount too, so the higher frequencies were being over-attenuated in the echo feedback.

But other than that, I don't know. It sounds like ```version17_win.wav``` doesn't have the echo effect. Are you sure you didn't accidentally disable the effect in your test for that one? Do you have any config file for OpenAL Soft (have you used alsoft-config, or otherwise made a ```%AppData%\alsoft.ini``` on Windows)? I've cross-compiled your test for Windows, and it sounds just like the Linux build.

**Comment by hgsz** [comment]
`version17_win.wav` was recorded with the echo effect enabled using OpenAL soft v17.  If I use v16 or Creative's OpenAL32.dll (note: I'm only swapping the DLL, I'm not recompiling), then I do hear the echo effect.  I am not using an `alsoft.ini` on Windows.

I did just try adding an `alsoft.ini` and I cycled through all the backends I listed in my [README](https://github.com/hgsz/OpenALSoftEchoBug/blob/master/sounds/README.md).  No echo effect with any of them.

**The Solution**: The echo effect works with the [latest master](https://github.com/kcat/openal-soft/tree/9ca92be0b87c97fccf613acb14b5c121cc881a88).  The issue seems to exclusively appear with v17.  Would you be able to try  [v1.17.2](https://github.com/kcat/openal-soft/releases/tag/openal-soft-1.17.2) on Windows to confirm?

**Comment by kcat** [comment]
You're right, for some reason 1.17 doesn't seem to be playing the echo effect, or is playing it extremely quietly, while master seems fine. I don't remember fixing any bug relating to the echo effect, and nothing in the git log is jumping out at me. Weird.

**Comment by hgsz** [comment]
I'm glad you were able to reproduce the issue.  I'm not curious enough to go track down the cause :smile:.  Would you know when 1.18.0 will have an official release?  Since the issue is fixed in master, if you have no objection, I'm fine closing this issue.

**Comment by kcat** [comment]
No firm date, but it should be "soon". I'm mainly waiting for some necessary reverb patches from someone, then it shouldn't be more than a couple days to get it into a release candidate stage for some final feedback and testing, and then the release soon after.

**Comment by hgsz** [comment]
Sounds good.  I'm closing the issue.  Thanks again!
