### ISSUE TITLE
No matching function for call

### ISSUE THREAD

**Issue by Switch0621** [kcat/openal-soft#994]
Hi all, i've got an issue with build openal in linux "No matching function for call ...". GCC version is 10.3.1. CMake configure and build result is attached.
[configure_log.txt](https://github.com/kcat/openal-soft/files/15209135/configure_log.txt)
[build_log.txt](https://github.com/kcat/openal-soft/files/15209136/build_log.txt)

**Comment by kcat** [comment]
I'm not quite sure what's causing that error since the function type is correct, and AFAIK, it works fine on later versions of GCC 8 (as well as 11, 12, 13, and Clang, MSVC, etc). Unless there happens to be a bug in that particular version of GCC, and a workaround isn't immediately obvious. Does it happen to work with the latest commit (0036434d7c9894f99bb35add5c45a87a28cd1b85, or more directly, 8a522c2c7f8625c4bbf428044e0781010242ba23)?

**Comment by Switch0621** [comment]
Yes! I've sync my fork with last commits and try to configure and build again and it's help! Thank you very match for solve issue.
